// PAGES
export const PAGES = {
  PAGE_HOME: 'Home',
  STARTUP_VIDEO: 'StartupVideo',
  PAGE_CATEGORY: 'Category',
  PAGE_VIDEO_PLAYER: 'VideoPlayer',
};

export const ALPHABETICAL_CATEGORY_NAME_ES = 'ALFABETO DACTILOLÓGICO';
export const RESTART_CATEGORIES = 'RESTART_CATEGORIES';
export const CATEGORIES_RESTARTED = 'CATEGORIES_RESTARTED';
export const RESTART_ALPHABETICAL_PAGE = 'RESTART_ALPHABETICAL_PAGE';
export const ALPHABETICAL_PAGE_RESTARTED = 'ALPHABETICAL_PAGE_RESTARTED';
export const RESTART_SEARCH_PAGE = 'RESTART_SEARCH_PAGE';
export const SEARCH_PAGE_RESTARTED = 'SEARCH_PAGE_RESTARTED';
