export const actions = uri => ({
  name_es: 'ACCIONES',
  icon: require('../res/icon/acciones.png'),
  videos: [
    {
      name_es: 'ABRAZAR',
      search_name_es: 'ABRAZAR',
      image: require('../res/image/abrazar.png'),
      video: `${uri}/abrazar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ACOSTARSE',
      search_name_es: 'ACOSTARSE',
      image: require('../res/image/acostarse.png'),
      video: `${uri}/acostarse.mp4`,
      downloaded: false,
    },
    {
      name_es: 'APLAUDIR (OYENTES)',
      search_name_es: 'APLAUDIR (OYENTES)',
      image: require('../res/image/aplaudir-(oyentes).png'),
      video: `${uri}/aplaudir-(oyentes).mp4`,
      downloaded: false,
    },
    {
      name_es: 'APLAUDIR (SORDOS)',
      search_name_es: 'APLAUDIR (SORDOS)',
      image: require('../res/image/aplaudir-(sordos).png'),
      video: `${uri}/aplaudir-(sordos).mp4`,
      downloaded: false,
    },
    {
      name_es: 'ARREGLAR',
      search_name_es: 'ARREGLAR',
      image: require('../res/image/arreglar.png'),
      video: `${uri}/arreglar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AYUDAR',
      search_name_es: 'AYUDAR',
      image: require('../res/image/ayudar.png'),
      video: `${uri}/ayudar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BAILAR',
      search_name_es: 'BAILAR',
      image: require('../res/image/bailar.png'),
      video: `${uri}/bailar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BAÑAR',
      search_name_es: 'BAÑAR',
      image: require('../res/image/banar.png'),
      video: `${uri}/banar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BARRER',
      search_name_es: 'BARRER',
      image: require('../res/image/barrer.png'),
      video: `${uri}/barrer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BESAR',
      search_name_es: 'BESAR',
      image: require('../res/image/besar.png'),
      video: `${uri}/besar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COCINAR',
      search_name_es: 'COCINAR',
      image: require('../res/image/cocinar.png'),
      video: `${uri}/cocinar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COMUNICAR',
      search_name_es: 'COMUNICAR',
      image: require('../res/image/comunicar.png'),
      video: `${uri}/comunicar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CONOCER',
      search_name_es: 'CONOCER',
      image: require('../res/image/conocer.png'),
      video: `${uri}/conocer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CONVERSAR',
      search_name_es: 'CONVERSAR',
      image: require('../res/image/conversar.png'),
      video: `${uri}/conversar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CRECER',
      search_name_es: 'CRECER',
      image: require('../res/image/crecer.png'),
      video: `${uri}/crecer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CUIDAR',
      search_name_es: 'CUIDAR',
      image: require('../res/image/cuidar.png'),
      video: `${uri}/cuidar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DORMIR',
      search_name_es: 'DORMIR',
      image: require('../res/image/dormir.png'),
      video: `${uri}/dormir.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GRITAR',
      search_name_es: 'GRITAR',
      image: require('../res/image/gritar.png'),
      video: `${uri}/gritar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HABLAR ORAL',
      search_name_es: 'HABLAR ORAL',
      image: require('../res/image/hablar-oral.png'),
      video: `${uri}/hablar-oral.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LAVAR LOS PLATOS',
      search_name_es: 'LAVAR LOS PLATOS',
      image: require('../res/image/lavar-los-platos.png'),
      video: `${uri}/lavar-los-platos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LAVAR ROPA',
      search_name_es: 'LAVAR ROPA',
      image: require('../res/image/lavar-ropa.png'),
      video: `${uri}/lavar-ropa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LAVARSE LAS MANOS',
      search_name_es: 'LAVARSE LAS MANOS',
      image: require('../res/image/lavarse-las-manos.png'),
      video: `${uri}/lavarse-las-manos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LEVANTARSE',
      search_name_es: 'LEVANTARSE',
      image: require('../res/image/levantarse.png'),
      video: `${uri}/levantarse.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LIMPIAR',
      search_name_es: 'LIMPIAR',
      image: require('../res/image/limpiar.png'),
      video: `${uri}/limpiar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OIR',
      search_name_es: 'OIR',
      image: require('../res/image/oir.png'),
      video: `${uri}/oir.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OLER',
      search_name_es: 'OLER',
      image: require('../res/image/oler.png'),
      video: `${uri}/oler.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PEINAR',
      search_name_es: 'PEINAR',
      image: require('../res/image/peinar.png'),
      video: `${uri}/peinar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PLANCHAR',
      search_name_es: 'PLANCHAR',
      image: require('../res/image/planchar.png'),
      video: `${uri}/planchar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'REIR',
      search_name_es: 'REIR',
      image: require('../res/image/reir.png'),
      video: `${uri}/reir.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RESPIRAR',
      search_name_es: 'RESPIRAR',
      image: require('../res/image/respirar.png'),
      video: `${uri}/respirar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SACAR FOTOS',
      search_name_es: 'SACAR FOTOS',
      image: require('../res/image/sacar-fotos.png'),
      video: `${uri}/sacar-fotos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SEÑAR',
      search_name_es: 'SEÑAR',
      image: require('../res/image/senar.png'),
      video: `${uri}/senar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TENER SUEÑO',
      search_name_es: 'TENER SUEÑO',
      image: require('../res/image/tener-sueno.png'),
      video: `${uri}/tener-sueno.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TOCAR',
      search_name_es: 'TOCAR',
      image: require('../res/image/tocar.png'),
      video: `${uri}/tocar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VER',
      search_name_es: 'VER',
      image: require('../res/image/ver.png'),
      video: `${uri}/ver.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VISITAR',
      search_name_es: 'VISITAR',
      image: require('../res/image/visitar.png'),
      video: `${uri}/visitar.mp4`,
      downloaded: false,
    },
  ],
});
