export const argentina = (uri) => ({
  name_es: 'ARGENTINA',
  icon: require('../res/icon/argentina.png'),
  hasSubcategories: true,
  videos: [
    {
      name_es: 'ANTÁRTIDA ARGENTINA',
      search_name_es: 'ANTARTIDA ARGENTINA',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/antartida-argentina.png'),
      video: `${uri}/antartida-argentina.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ARGENTINA',
      search_name_es: 'ARGENTINA',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/argentina.png'),
      video: `${uri}/argentina.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BUENOS AIRES',
      search_name_es: 'BUENOS AIRES',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/buenos-aires.png'),
      video: `${uri}/buenos-aires.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CATAMARCA',
      search_name_es: 'CATAMARCA',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/catamarca.png'),
      video: `${uri}/catamarca.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CHACO',
      search_name_es: 'CHACO',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/chaco.png'),
      video: `${uri}/chaco.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CHUBUT',
      search_name_es: 'CHUBUT',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/chubut.png'),
      video: `${uri}/chubut.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CÓRDOBA',
      search_name_es: 'CORDOBA',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/cordoba.png'),
      video: `${uri}/cordoba.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CORRIENTES',
      search_name_es: 'CORRIENTES',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/corrientes.png'),
      video: `${uri}/corrientes.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ENTRE RÍOS',
      search_name_es: 'ENTRE RIOS',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/entre-rios.png'),
      video: `${uri}/entre-rios.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FORMOSA',
      search_name_es: 'FORMOSA',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/formosa.png'),
      video: `${uri}/formosa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ISLAS MALVINAS',
      search_name_es: 'ISLAS MALVINAS',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/islas-malvinas.png'),
      video: `${uri}/islas-malvinas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'JUJUY',
      search_name_es: 'JUJUY',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/jujuy.png'),
      video: `${uri}/jujuy.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LA PAMPA',
      search_name_es: 'LA PAMPA',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/la-pampa.png'),
      video: `${uri}/la-pampa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LA RIOJA',
      search_name_es: 'LA RIOJA',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/la-rioja.png'),
      video: `${uri}/la-rioja.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MENDOZA',
      search_name_es: 'MENDOZA',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/mendoza.png'),
      video: `${uri}/mendoza.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MISIONES',
      search_name_es: 'MISIONES',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/misiones.png'),
      video: `${uri}/misiones.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NEUQUÉN',
      search_name_es: 'NEUQUEN',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/neuquen.png'),
      video: `${uri}/neuquen.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RIO NEGRO',
      search_name_es: 'RIO NEGRO',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/rio-negro.png'),
      video: `${uri}/rio-negro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SALTA',
      search_name_es: 'SALTA',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/salta.png'),
      video: `${uri}/salta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SAN JUAN',
      search_name_es: 'SAN JUAN',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/san-juan.png'),
      video: `${uri}/san-juan.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SAN LUIS',
      search_name_es: 'SAN LUIS',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/san-luis.png'),
      video: `${uri}/san-luis.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SANTA CRUZ',
      search_name_es: 'SANTA CRUZ',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/santa-cruz.png'),
      video: `${uri}/santa-cruz.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SANTA FÉ',
      search_name_es: 'SANTA FE',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/santa-fe.png'),
      video: `${uri}/santa-fe.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SANTIAGO DEL ESTERO',
      search_name_es: 'SANTIAGO DEL ESTERO',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/santiago-del-estero.png'),
      video: `${uri}/santiago-del-estero.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TIERRA DEL FUEGO',
      search_name_es: 'TIERRA DEL FUEGO',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/tierra-del-fuego.png'),
      video: `${uri}/tierra-del-fuego.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TUCUMÁN',
      search_name_es: 'TUCUMAN',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/tucuman.png'),
      video: `${uri}/tucuman.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PROVINCIAS',
      search_name_es: 'PROVINCIAS',
      subcategory: 'PROVINCIAS',
      image: require('../res/image/provincias.png'),
      video: `${uri}/provincias.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CABA',
      search_name_es: 'CABA',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/caba.png'),
      video: `${uri}/caba.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AGRONOMÍA',
      search_name_es: 'AGRONOMIA',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/agronomia.png'),
      video: `${uri}/agronomia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ALMAGRO',
      search_name_es: 'ALMAGRO',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/almagro.png'),
      video: `${uri}/almagro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BARRACAS',
      search_name_es: 'BARRACAS',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/barracas.png'),
      video: `${uri}/barracas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BELGRANO',
      search_name_es: 'BELGRANO',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/belgrano.png'),
      video: `${uri}/belgrano.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BOEDO',
      search_name_es: 'BOEDO',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/boedo.png'),
      video: `${uri}/boedo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CABALLITO',
      search_name_es: 'CABALLITO',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/caballito.png'),
      video: `${uri}/caballito.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CHACARITA',
      search_name_es: 'CHACARITA',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/chacarita.png'),
      video: `${uri}/chacarita.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CONSTITUCIÓN',
      search_name_es: 'CONSTITUCION',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/constitucion.png'),
      video: `${uri}/constitucion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FLORES',
      search_name_es: 'FLORES',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/flores.png'),
      video: `${uri}/flores.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LINIERS',
      search_name_es: 'LINIERS',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/liniers.png'),
      video: `${uri}/liniers.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MATADEROS',
      search_name_es: 'MATADEROS',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/mataderos.png'),
      video: `${uri}/mataderos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PALERMO',
      search_name_es: 'PALERMO',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/palermo.png'),
      video: `${uri}/palermo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PARQUE PATRICIOS',
      search_name_es: 'PARQUE PATRICIOS',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/parque-patricios.png'),
      video: `${uri}/parque-patricios.mp4`,
      downloaded: false,
    },
    {
      name_es: 'POMPEYA',
      search_name_es: 'POMPEYA',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/pompeya.png'),
      video: `${uri}/pompeya.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RECOLETA',
      search_name_es: 'RECOLETA',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/recoleta.png'),
      video: `${uri}/recoleta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RETIRO',
      search_name_es: 'RETIRO',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/retiro.png'),
      video: `${uri}/retiro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SAN TELMO',
      search_name_es: 'SAN TELMO',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/san-telmo.png'),
      video: `${uri}/san-telmo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VILLA DEL PARQUE',
      search_name_es: 'VILLA DEL PARQUE',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/villa-del-parque.png'),
      video: `${uri}/villa-del-parque.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VILLA DEVOTO',
      search_name_es: 'VILLA DEVOTO',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/villa-devoto.png'),
      video: `${uri}/villa-devoto.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VILLA LUGANO',
      search_name_es: 'VILLA LUGANO',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/villa-lugano.png'),
      video: `${uri}/villa-lugano.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VILLA URQUIZA',
      search_name_es: 'VILLA URQUIZA',
      subcategory: 'BARRIOS CABA',
      image: require('../res/image/villa-urquiza.png'),
      video: `${uri}/villa-urquiza.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CONURBANO',
      search_name_es: 'CONURBANO',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/conurbano.png'),
      video: `${uri}/conurbano.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AVELLANEDA',
      search_name_es: 'AVELLANEDA',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/avellaneda.png'),
      video: `${uri}/avellaneda.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BANFIELD',
      search_name_es: 'BANFIELD',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/banfield.png'),
      video: `${uri}/banfield.mp4`,
      downloaded: false,
    },
    {
      name_es: 'EZEIZA',
      search_name_es: 'EZEIZA',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/ezeiza.png'),
      video: `${uri}/ezeiza.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ITUZAINGÓ',
      search_name_es: 'ITUZAINGO',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/ituzaingo.png'),
      video: `${uri}/ituzaingo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LA MATANZA',
      search_name_es: 'LA MATANZA',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/la-matanza.png'),
      video: `${uri}/la-matanza.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LAFERRERE',
      search_name_es: 'LAFERRERE',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/laferrere.png'),
      video: `${uri}/laferrere.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LANÚS',
      search_name_es: 'LANUS',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/lanus.png'),
      video: `${uri}/lanus.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LOMAS DE ZAMORA',
      search_name_es: 'LOMAS DE ZAMORA',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/lomas-de-zamora.png'),
      video: `${uri}/lomas-de-zamora.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MERLO',
      search_name_es: 'MERLO',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/merlo.png'),
      video: `${uri}/merlo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MORENO',
      search_name_es: 'MORENO',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/moreno.png'),
      video: `${uri}/moreno.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MORÓN',
      search_name_es: 'MORON',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/moron.png'),
      video: `${uri}/moron.mp4`,
      downloaded: false,
    },
    {
      name_es: 'QUILMES',
      search_name_es: 'QUILMES',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/quilmes.png'),
      video: `${uri}/quilmes.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RAMOS MEJÍA',
      search_name_es: 'RAMOS MEJIA',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/ramos-mejia.png'),
      video: `${uri}/ramos-mejia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SAN ISIDRO',
      search_name_es: 'SAN ISIDRO',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/san-isidro.png'),
      video: `${uri}/san-isidro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SAN JUSTO',
      search_name_es: 'SAN JUSTO',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/san-justo.png'),
      video: `${uri}/san-justo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SAN MARTÍN',
      search_name_es: 'SAN MARTIN',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/san-martin.png'),
      video: `${uri}/san-martin.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SAN MIGUEL',
      search_name_es: 'SAN MIGUEL',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/san-miguel.png'),
      video: `${uri}/san-miguel.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TEMPERLEY',
      search_name_es: 'TEMPERLEY',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/temperley.png'),
      video: `${uri}/temperley.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TIGRE',
      search_name_es: 'TIGRE',
      subcategory: 'BARRIOS CONURBANO',
      image: require('../res/image/tigre-caba.png'),
      video: `${uri}/tigre-caba.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BARRIO',
      search_name_es: 'BARRIO',
      subcategory: 'UBICACIÓN',
      image: require('../res/image/barrio.png'),
      video: `${uri}/barrio.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CALLE - DIRECCIÓN',
      search_name_es: 'CALLE - DIRECCION',
      subcategory: 'UBICACIÓN',
      image: require('../res/image/calle-direccion.png'),
      video: `${uri}/calle-direccion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CIUDAD',
      search_name_es: 'CIUDAD',
      subcategory: 'UBICACIÓN',
      image: require('../res/image/ciudad.png'),
      video: `${uri}/ciudad.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NORTE',
      search_name_es: 'NORTE',
      subcategory: 'UBICACIÓN',
      image: require('../res/image/norte.png'),
      video: `${uri}/norte.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SUR',
      search_name_es: 'SUR',
      subcategory: 'UBICACIÓN',
      image: require('../res/image/sur.png'),
      video: `${uri}/sur.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESTE',
      search_name_es: 'ESTE',
      subcategory: 'UBICACIÓN',
      image: require('../res/image/este.png'),
      video: `${uri}/este.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OESTE',
      search_name_es: 'OESTE',
      subcategory: 'UBICACIÓN',
      image: require('../res/image/oeste.png'),
      video: `${uri}/oeste.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MUNDO',
      search_name_es: 'MUNDO',
      subcategory: 'UBICACIÓN',
      image: require('../res/image/mundo.png'),
      video: `${uri}/mundo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OTROS PAÍSES',
      search_name_es: 'OTROS PAISES',
      subcategory: 'UBICACIÓN',
      image: require('../res/image/otros-paises.png'),
      video: `${uri}/otros-paises.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PUEBLO',
      search_name_es: 'PUEBLO',
      subcategory: 'UBICACIÓN',
      image: require('../res/image/pueblo.png'),
      video: `${uri}/pueblo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VIVIR',
      search_name_es: 'VIVIR',
      subcategory: 'UBICACIÓN',
      image: require('../res/image/vivir.png'),
      video: `${uri}/vivir.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VIAJAR',
      search_name_es: 'VIAJAR',
      subcategory: 'UBICACIÓN',
      image: require('../res/image/viajar.png'),
      video: `${uri}/viajar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ABORIGEN',
      search_name_es: 'ABORIGEN',
      subcategory: 'UBICACIÓN',
      image: require('../res/image/aborigen.png'),
      video: `${uri}/aborigen.mp4`,
      downloaded: false,
    },
    {
      name_es: 'EXTRANJERO',
      search_name_es: 'EXTRANJERO',
      subcategory: 'UBICACIÓN',
      image: require('../res/image/extranjero.png'),
      video: `${uri}/extranjero.mp4`,
      downloaded: false,
    },
  ],
});
