export const body = uri => ({
  name_es: 'CUERPO HUMANO',
  icon: require('../res/icon/el-cuerpo-humano.png'),
  hasSubcategories: true,
  videos: [
    {
      name_es: 'BOCA',
      search_name_es: 'BOCA',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/boca.png'),
      video: `${uri}/boca.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BRAZO',
      search_name_es: 'BRAZO',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/brazo.png'),
      video: `${uri}/brazo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CABEZA',
      search_name_es: 'CABEZA',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/cabeza.png'),
      video: `${uri}/cabeza.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CACA',
      search_name_es: 'CACA',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/caca.png'),
      video: `${uri}/caca.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CARA',
      search_name_es: 'CARA',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/cara.png'),
      video: `${uri}/cara.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CODO',
      search_name_es: 'CODO',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/codo.png'),
      video: `${uri}/codo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COLA',
      search_name_es: 'COLA',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/cola.png'),
      video: `${uri}/cola.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CUELLO',
      search_name_es: 'CUELLO',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/cuello.png'),
      video: `${uri}/cuello.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CUERPO HUMANO',
      search_name_es: 'CUERPO HUMANO',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/el-cuerpo-humano.png'),
      video: `${uri}/el-cuerpo-humano.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DEDO',
      search_name_es: 'DEDO',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/dedo.png'),
      video: `${uri}/dedo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DIENTE',
      search_name_es: 'DIENTE',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/diente.png'),
      video: `${uri}/diente.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESPALDA',
      search_name_es: 'ESPALDA',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/espalda.png'),
      video: `${uri}/espalda.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HOMBRO',
      search_name_es: 'HOMBRO',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/hombro.png'),
      video: `${uri}/hombro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LENGUA',
      search_name_es: 'LENGUA',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/la-lengua.png'),
      video: `${uri}/la-lengua.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MANO',
      search_name_es: 'MANO',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/mano.png'),
      video: `${uri}/mano.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NARIZ',
      search_name_es: 'NARIZ',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/nariz.png'),
      video: `${uri}/nariz.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NENA',
      search_name_es: 'NENA',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/nena.png'),
      video: `${uri}/nena.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NENE',
      search_name_es: 'NENE',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/nene.png'),
      video: `${uri}/nene.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OJOS',
      search_name_es: 'OJOS',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/ojos.png'),
      video: `${uri}/ojos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OREJA',
      search_name_es: 'OREJA',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/oreja.png'),
      video: `${uri}/oreja.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PANZA',
      search_name_es: 'PANZA',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/panza.png'),
      video: `${uri}/panza.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PELO',
      search_name_es: 'PELO',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/pelo.png'),
      video: `${uri}/pelo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PENE',
      search_name_es: 'PENE',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/pene.png'),
      video: `${uri}/pene.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PIERNA',
      search_name_es: 'PIERNA',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/pierna.png'),
      video: `${uri}/pierna.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PIS',
      search_name_es: 'PIS',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/pis.png'),
      video: `${uri}/pis.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RODILLA',
      search_name_es: 'RODILLA',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/rodilla.png'),
      video: `${uri}/rodilla.mp4`,
      downloaded: false,
    },
    {
      name_es: 'UÑA',
      search_name_es: 'UÑA',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/una.png'),
      video: `${uri}/una.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VAGINA',
      search_name_es: 'VAGINA',
      subcategory: 'CUERPO HUMANO',
      image: require('../res/image/vagina.png'),
      video: `${uri}/vagina.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CRECER',
      search_name_es: 'CRECER',
      subcategory: 'ACCIONES',
      image: require('../res/image/crecer.png'),
      video: `${uri}/crecer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MORIR',
      search_name_es: 'MORIR',
      subcategory: 'ACCIONES',
      image: require('../res/image/morir.png'),
      video: `${uri}/morir.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NACER',
      search_name_es: 'NACER',
      subcategory: 'ACCIONES',
      image: require('../res/image/nacer.png'),
      video: `${uri}/nacer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OIR',
      search_name_es: 'OIR',
      subcategory: 'ACCIONES',
      image: require('../res/image/oir.png'),
      video: `${uri}/oir.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OLER',
      search_name_es: 'OLER',
      subcategory: 'ACCIONES',
      image: require('../res/image/oler.png'),
      video: `${uri}/oler.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RESPIRAR',
      search_name_es: 'RESPIRAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/respirar.png'),
      video: `${uri}/respirar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TOCAR',
      search_name_es: 'TOCAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/tocar.png'),
      video: `${uri}/tocar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VER',
      search_name_es: 'VER',
      subcategory: 'ACCIONES',
      image: require('../res/image/ver.png'),
      video: `${uri}/ver.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VIDA',
      search_name_es: 'VIDA',
      subcategory: 'ACCIONES',
      image: require('../res/image/vida.png'),
      video: `${uri}/vida.mp4`,
      downloaded: false,
    },
  ],
});
