export const calendar = uri => ({
  name_es: 'CALENDARIO',
  icon: require('../res/icon/el-calendario.png'),
  subcategories: [
    {
      name_es: 'DÍAS',
      videos: [
        {
          name_es: 'LUNES',
          search_name_es: 'LUNES',
          image: require('../res/image/lunes.png'),
          video: `${uri}/lunes.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MARTES',
          search_name_es: 'MARTES',
          image: require('../res/image/martes.png'),
          video: `${uri}/martes.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MIERCOLES',
          search_name_es: 'MIERCOLES',
          image: require('../res/image/miercoles.png'),
          video: `${uri}/miercoles.mp4`,
          downloaded: false,
        },
        {
          name_es: 'JUEVES',
          search_name_es: 'JUEVES',
          image: require('../res/image/jueves.png'),
          video: `${uri}/jueves.mp4`,
          downloaded: false,
        },
        {
          name_es: 'VIERNES',
          search_name_es: 'VIERNES',
          image: require('../res/image/viernes.png'),
          video: `${uri}/viernes.mp4`,
          downloaded: false,
        },
        {
          name_es: 'SÁBADO',
          search_name_es: 'SABADO',
          image: require('../res/image/sabado.png'),
          video: `${uri}/sabado.mp4`,
          downloaded: false,
        },
        {
          name_es: 'DOMINGO',
          search_name_es: 'DOMINGO',
          image: require('../res/image/domingo.png'),
          video: `${uri}/domingo.mp4`,
          downloaded: false,
        },
        {
          name_es: 'SEMANA',
          search_name_es: 'SEMANA',
          image: require('../res/image/semana.png'),
          video: `${uri}/semana.mp4`,
          downloaded: false,
        },
        {
          name_es: 'TODOS LOS DÍAS',
          search_name_es: 'TODOS LOS DIAS',
          image: require('../res/image/todos-los-dias.png'),
          video: `${uri}/todos-los-dias.mp4`,
          downloaded: false,
        },
        {
          name_es: 'FIN DE SEMANA',
          search_name_es: 'FIN DE SEMANA',
          image: require('../res/image/fin-de-semana.png'),
          video: `${uri}/fin-de-semana.mp4`,
          downloaded: false,
        },
        {
          name_es: 'DÍA',
          search_name_es: 'DIA',
          image: require('../res/image/dia.png'),
          video: `${uri}/dia.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'MESES',
      videos: [
        {
          name_es: 'ENERO',
          search_name_es: 'ENERO',
          image: require('../res/image/enero.png'),
          video: `${uri}/enero.mp4`,
          downloaded: false,
        },
        {
          name_es: 'FEBRERO',
          search_name_es: 'FEBRERO',
          image: require('../res/image/febrero.png'),
          video: `${uri}/febrero.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MARZO',
          search_name_es: 'MARZO',
          image: require('../res/image/marzo.png'),
          video: `${uri}/marzo.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ABRIL',
          search_name_es: 'ABRIL',
          image: require('../res/image/abril.png'),
          video: `${uri}/abril.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MAYO',
          search_name_es: 'MAYO',
          image: require('../res/image/mayo.png'),
          video: `${uri}/mayo.mp4`,
          downloaded: false,
        },
        {
          name_es: 'JUNIO',
          search_name_es: 'JUNIO',
          image: require('../res/image/junio.png'),
          video: `${uri}/junio.mp4`,
          downloaded: false,
        },
        {
          name_es: 'JULIO',
          search_name_es: 'JULIO',
          image: require('../res/image/julio.png'),
          video: `${uri}/julio.mp4`,
          downloaded: false,
        },
        {
          name_es: 'AGOSTO',
          search_name_es: 'AGOSTO',
          image: require('../res/image/agosto.png'),
          video: `${uri}/agosto.mp4`,
          downloaded: false,
        },
        {
          name_es: 'SEPTIEMBRE',
          search_name_es: 'SEPTIEMBRE',
          image: require('../res/image/septiembre.png'),
          video: `${uri}/septiembre.mp4`,
          downloaded: false,
        },
        {
          name_es: 'OCTUBRE',
          search_name_es: 'OCTUBRE',
          image: require('../res/image/octubre.png'),
          video: `${uri}/octubre.mp4`,
          downloaded: false,
        },
        {
          name_es: 'NOVIEMBRE',
          search_name_es: 'NOVIEMBRE',
          image: require('../res/image/noviembre.png'),
          video: `${uri}/noviembre.mp4`,
          downloaded: false,
        },
        {
          name_es: 'DICIEMBRE',
          search_name_es: 'DICIEMBRE',
          image: require('../res/image/diciembre.png'),
          video: `${uri}/diciembre.mp4`,
          downloaded: false,
        },
        {
          name_es: 'AÑO',
          search_name_es: 'AÑO',
          image: require('../res/image/ano.png'),
          video: `${uri}/ano.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MES',
          search_name_es: 'MES',
          image: require('../res/image/mes.png'),
          video: `${uri}/mes.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'GENERAL',
      videos: [
        {
          name_es: 'AYER',
          search_name_es: 'AYER',
          image: require('../res/image/ayer.png'),
          video: `${uri}/ayer.mp4`,
          downloaded: false,
        },
        {
          name_es: 'HOY',
          search_name_es: 'HOY',
          image: require('../res/image/hoy.png'),
          video: `${uri}/hoy.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MAÑANA',
          search_name_es: 'MAÑANA',
          image: require('../res/image/manana.png'),
          video: `${uri}/manana.mp4`,
          downloaded: false,
        },
        {
          name_es: 'PRIMERA VEZ',
          search_name_es: 'PRIMERA VEZ',
          image: require('../res/image/primera-vez.png'),
          video: `${uri}/primera-vez.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MUCHAS VECES',
          search_name_es: 'MUCHAS VECES',
          image: require('../res/image/muchas-veces.png'),
          video: `${uri}/muchas-veces.mp4`,
          downloaded: false,
        },
        {
          name_es: 'FERIADO',
          search_name_es: 'FERIADO',
          image: require('../res/image/feriado.png'),
          video: `${uri}/feriado.mp4`,
          downloaded: false,
        },
        {
          name_es: 'CALENDARIO',
          search_name_es: 'CALENDARIO',
          image: require('../res/image/calendario.png'),
          video: `${uri}/calendario.mp4`,
          downloaded: false,
        },
        {
          name_es: 'NUNCA',
          search_name_es: 'NUNCA',
          image: require('../res/image/nunca.png'),
          video: `${uri}/nunca.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MEDIODIA',
          search_name_es: 'MEDIODIA',
          image: require('../res/image/mediodia.png'),
          video: `${uri}/mediodia.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MADRUGADA',
          search_name_es: 'MADRUGADA',
          image: require('../res/image/madrugada.png'),
          video: `${uri}/madrugada.mp4`,
          downloaded: false,
        },
      ],
    },
  ],
});
