export const clothes = uri => ({
  name_es: 'ROPA',
  icon: require('../res/icon/la-ropa.png'),
  hasSubcategories: true,
  videos: [
    {
      name_es: 'BOTAS',
      search_name_es: 'BOTAS',
      subcategory: 'CALZADOS',
      image: require('../res/image/botas.png'),
      video: `${uri}/botas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OJOTAS',
      search_name_es: 'OJOTAS',
      subcategory: 'CALZADOS',
      image: require('../res/image/ojotas.png'),
      video: `${uri}/ojotas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ZAPATILLAS',
      search_name_es: 'ZAPATILLAS',
      subcategory: 'CALZADOS',
      image: require('../res/image/zapatillas.png'),
      video: `${uri}/zapatillas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ZAPATOS',
      search_name_es: 'ZAPATOS',
      subcategory: 'CALZADOS',
      image: require('../res/image/zapatos.png'),
      video: `${uri}/zapatos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BUFANDA',
      search_name_es: 'BUFANDA',
      subcategory: 'ROPA DE INVIERNO',
      image: require('../res/image/bufanda.png'),
      video: `${uri}/bufanda.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAMPERA',
      search_name_es: 'CAMPERA',
      subcategory: 'ROPA DE INVIERNO',
      image: require('../res/image/campera.png'),
      video: `${uri}/campera.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GUANTES',
      search_name_es: 'GUANTES',
      subcategory: 'ROPA DE INVIERNO',
      image: require('../res/image/guantes.png'),
      video: `${uri}/guantes.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PANTALÓN',
      search_name_es: 'PANTALON',
      subcategory: 'ROPA DE INVIERNO',
      image: require('../res/image/pantalon.png'),
      video: `${uri}/pantalon.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PARAGUAS',
      search_name_es: 'PARAGUAS',
      subcategory: 'ROPA DE INVIERNO',
      image: require('../res/image/paraguas.png'),
      video: `${uri}/paraguas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PULLOVER',
      search_name_es: 'PULLOVER',
      subcategory: 'ROPA DE INVIERNO',
      image: require('../res/image/pullover.png'),
      video: `${uri}/pullover.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAMISA',
      search_name_es: 'CAMISA',
      subcategory: 'ROPA DE VERANO',
      image: require('../res/image/camisa.png'),
      video: `${uri}/camisa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MALLA DE HOMBRE',
      search_name_es: 'MALLA DE HOMBRE',
      subcategory: 'ROPA DE VERANO',
      image: require('../res/image/malla-de-hombre.png'),
      video: `${uri}/malla-de-hombre.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MALLA DE MUJER',
      search_name_es: 'MALLA DE MUJER',
      subcategory: 'ROPA DE VERANO',
      image: require('../res/image/malla-de-mujer.png'),
      video: `${uri}/malla-de-mujer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'POLLERA',
      search_name_es: 'POLLERA',
      subcategory: 'ROPA DE VERANO',
      image: require('../res/image/pollera.png'),
      video: `${uri}/pollera.mp4`,
      downloaded: false,
    },
    {
      name_es: 'REMERA',
      search_name_es: 'REMERA',
      subcategory: 'ROPA DE VERANO',
      image: require('../res/image/remera.png'),
      video: `${uri}/remera.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SHORT',
      search_name_es: 'SHORT',
      subcategory: 'ROPA DE VERANO',
      image: require('../res/image/short.png'),
      video: `${uri}/short.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VESTIDO',
      search_name_es: 'VESTIDO',
      subcategory: 'ROPA DE VERANO',
      image: require('../res/image/vestido.png'),
      video: `${uri}/vistiendose.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BOMBACHA',
      search_name_es: 'BOMBACHA',
      subcategory: 'ROPA INTERIOR',
      image: require('../res/image/bombacha.png'),
      video: `${uri}/bombacha.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CALZONCILLO',
      search_name_es: 'CALZONCILLO',
      subcategory: 'ROPA INTERIOR',
      image: require('../res/image/calzoncillo.png'),
      video: `${uri}/calzoncillo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MEDIAS',
      search_name_es: 'MEDIAS',
      subcategory: 'ROPA INTERIOR',
      image: require('../res/image/medias.png'),
      video: `${uri}/medias.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAÑAL',
      search_name_es: 'PAÑAL',
      subcategory: 'ROPA INTERIOR',
      image: require('../res/image/panal.png'),
      video: `${uri}/panal.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAMBIARSE LA ROPA',
      search_name_es: 'CAMBIARSE LA ROPA',
      subcategory: 'ACCIONES',
      image: require('../res/image/cambiarse-la-ropa.png'),
      video: `${uri}/cambiarse-la-ropa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GUARDAR LA ROPA',
      search_name_es: 'GUARDAR LA ROPA',
      subcategory: 'ACCIONES',
      image: require('../res/image/guardar-la-ropa.png'),
      video: `${uri}/guardar-la-ropa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PONERSE LA ROPA',
      search_name_es: 'PONERSE LA ROPA',
      subcategory: 'ACCIONES',
      image: require('../res/image/ponerse-la-ropa.png'),
      video: `${uri}/ponerse-la-ropa.mp4`,
      downloaded: false,
    },
  ],
});
