export const communicating = uri => ({
  name_es: 'COMUNICÁNDONOS',
  icon: require('../res/icon/comunicandonos.png'),
  hasSubcategories: true,
  videos: [
    {
      name_es: 'APELLIDO',
      search_name_es: 'APELLIDO',
      subcategory: 'PRESENTÁNDONOS',
      image: require('../res/image/apellido.png'),
      video: `${uri}/apellido.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NOMBRE',
      search_name_es: 'NOMBRE',
      subcategory: 'PRESENTÁNDONOS',
      image: require('../res/image/nombre.png'),
      video: `${uri}/nombre.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DNI',
      search_name_es: 'DNI',
      subcategory: 'PRESENTÁNDONOS',
      image: require('../res/image/dni.png'),
      video: `${uri}/dni.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OYENTE',
      search_name_es: 'OYENTE',
      subcategory: 'PRESENTÁNDONOS',
      image: require('../res/image/oyente.png'),
      video: `${uri}/oyente.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PRESENTÁNDONOS',
      search_name_es: 'PRESENTANDONOS',
      subcategory: 'PRESENTÁNDONOS',
      image: require('../res/image/presentandonos.png'),
      video: `${uri}/presentandonos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SEÑA PERSONAL',
      search_name_es: 'SEÑA PERSONAL',
      subcategory: 'PRESENTÁNDONOS',
      image: require('../res/image/sena-personal.png'),
      video: `${uri}/sena-personal.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SORDO',
      search_name_es: 'SORDO',
      subcategory: 'PRESENTÁNDONOS',
      image: require('../res/image/sordo.png'),
      video: `${uri}/sordo.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿CÓMO ESTÁS?',
      search_name_es: '¿COMO ESTAS?',
      subcategory: 'PREGUNTAS',
      image: require('../res/image/como-estas.png'),
      video: `${uri}/como-estas.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿CÓMO?',
      search_name_es: '¿COMO?',
      subcategory: 'PREGUNTAS',
      image: require('../res/image/como.png'),
      video: `${uri}/como.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿CUÁL?',
      search_name_es: '¿CUAL?',
      subcategory: 'PREGUNTAS',
      image: require('../res/image/cual.png'),
      video: `${uri}/cual.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿CUÁNDO?',
      search_name_es: '¿CUANDO?',
      subcategory: 'PREGUNTAS',
      image: require('../res/image/cuando.png'),
      video: `${uri}/cuando.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿CUÁNTO?',
      search_name_es: '¿CUANTO?',
      subcategory: 'PREGUNTAS',
      image: require('../res/image/cuanto.png'),
      video: `${uri}/cuanto.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿CUÁL ES TÚ EDAD?',
      search_name_es: '¿CUAL ES TU EDAD?',
      subcategory: 'PREGUNTAS',
      image: require('../res/image/cual-es-tu-edad.png'),
      video: `${uri}/cual-es-tu-edad.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿DÓNDE?',
      search_name_es: '¿DONDE?',
      subcategory: 'PREGUNTAS',
      image: require('../res/image/donde.png'),
      video: `${uri}/donde.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿PARA QUÉ?',
      search_name_es: '¿PARA QUE?',
      subcategory: 'PREGUNTAS',
      image: require('../res/image/para-que.png'),
      video: `${uri}/para-que.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿POR QUÉ?',
      search_name_es: '¿POR QUE?',
      subcategory: 'PREGUNTAS',
      image: require('../res/image/por-que.png'),
      video: `${uri}/por-que.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿QUÉ DICE?',
      search_name_es: '¿QUE DICE?',
      subcategory: 'PREGUNTAS',
      image: require('../res/image/que-dice.png'),
      video: `${uri}/que-dice.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿QUÉ?',
      search_name_es: '¿QUE?',
      subcategory: 'PREGUNTAS',
      image: require('../res/image/que.png'),
      video: `${uri}/que.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿QUIÉN?',
      search_name_es: '¿QUIEN?',
      subcategory: 'PREGUNTAS',
      image: require('../res/image/quien.png'),
      video: `${uri}/quien.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿CÓMO TE LLAMAS?',
      search_name_es: '¿COMO TE LLAMAS?',
      subcategory: 'PREGUNTAS',
      image: require('../res/image/como-te-llamas.png'),
      video: `${uri}/como-te-llamas.mp4`,
      downloaded: false,
    },
    {
      name_es: '¿DE QUÉ?',
      search_name_es: '¿DE QUE?',
      subcategory: 'PREGUNTAS',
      image: require('../res/image/de-que.png'),
      video: `${uri}/de-que.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BUENOS DÍAS',
      search_name_es: 'BUENOS DIAS',
      subcategory: 'SALUDOS',
      image: require('../res/image/buenos-dias.png'),
      video: `${uri}/buenos-dias.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BUENAS TARDES',
      search_name_es: 'BUENAS TARDES',
      subcategory: 'SALUDOS',
      image: require('../res/image/buenas-tardes.png'),
      video: `${uri}/buenas-tardes.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BUENAS NOCHES',
      search_name_es: 'BUENAS NOCHES',
      subcategory: 'SALUDOS',
      image: require('../res/image/buenas-noches.png'),
      video: `${uri}/buenas-noches.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CHAU',
      search_name_es: 'CHAU',
      subcategory: 'SALUDOS',
      image: require('../res/image/chau.png'),
      video: `${uri}/chau.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HOLA',
      search_name_es: 'HOLA',
      subcategory: 'SALUDOS',
      image: require('../res/image/hola.png'),
      video: `${uri}/hola.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SALUDOS',
      search_name_es: 'SALUDOS',
      subcategory: 'SALUDOS',
      image: require('../res/image/saludos.png'),
      video: `${uri}/saludos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BIENVENIDA',
      search_name_es: 'BIENVENIDA',
      subcategory: 'FRASES DE CORTESÍA',
      image: require('../res/image/bienvenida.png'),
      video: `${uri}/bienvenida.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DE NADA',
      search_name_es: 'DE NADA',
      subcategory: 'FRASES DE CORTESÍA',
      image: require('../res/image/de-nada.png'),
      video: `${uri}/de-nada.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GRACIAS',
      search_name_es: 'GRACIAS',
      subcategory: 'FRASES DE CORTESÍA',
      image: require('../res/image/gracias.png'),
      video: `${uri}/gracias.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PERDÓN',
      search_name_es: 'PERDON',
      subcategory: 'FRASES DE CORTESÍA',
      image: require('../res/image/perdon.png'),
      video: `${uri}/perdon.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PERMISO',
      search_name_es: 'PERMISO',
      subcategory: 'FRASES DE CORTESÍA',
      image: require('../res/image/permiso.png'),
      video: `${uri}/permiso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'POR FAVOR',
      search_name_es: 'POR FAVOR',
      subcategory: 'FRASES DE CORTESÍA',
      image: require('../res/image/por-favor.png'),
      video: `${uri}/por-favor.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BASTA',
      search_name_es: 'BASTA',
      subcategory: 'RESPUESTAS',
      image: require('../res/image/basta.png'),
      video: `${uri}/basta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BIEN',
      search_name_es: 'BIEN',
      subcategory: 'RESPUESTAS',
      image: require('../res/image/bien.png'),
      video: `${uri}/bien.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MAL',
      search_name_es: 'MAL',
      subcategory: 'RESPUESTAS',
      image: require('../res/image/mal.png'),
      video: `${uri}/mal.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SÍ',
      search_name_es: 'SI',
      subcategory: 'RESPUESTAS',
      image: require('../res/image/si.png'),
      video: `${uri}/si.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NO',
      search_name_es: 'NO',
      subcategory: 'RESPUESTAS',
      image: require('../res/image/no.png'),
      video: `${uri}/no.mp4`,
      downloaded: false,
    },
    {
      name_es: 'POR EJEMPLO',
      search_name_es: 'POR EJEMPLO',
      subcategory: 'RESPUESTAS',
      image: require('../res/image/por-ejemplo.png'),
      video: `${uri}/por-ejemplo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COMUNICAR',
      search_name_es: 'COMUNICAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/comunicar.png'),
      video: `${uri}/comunicar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CONVERSAR',
      search_name_es: 'CONVERSAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/conversar.png'),
      video: `${uri}/conversar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HABLAR ORAL',
      search_name_es: 'HABLAR ORAL',
      subcategory: 'ACCIONES',
      image: require('../res/image/hablar-oral.png'),
      video: `${uri}/hablar-oral.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HABLAR SEÑAS',
      search_name_es: 'HABLAR SEÑAS',
      subcategory: 'ACCIONES',
      image: require('../res/image/hablar-senas.png'),
      video: `${uri}/hablar-senas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LLAMAR',
      search_name_es: 'LLAMAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/llamar.png'),
      video: `${uri}/llamar.mp4`,
      downloaded: false,
    },
  ],
});
