export const feelings = uri => ({
  name_es: 'SENTIMIENTOS',
  icon: require('../res/icon/los-sentimientos.png'),
  hasSubcategories: false,
  videos: [
    {
      name_es: 'ABURRIDO',
      search_name_es: 'ABURRIDO',
      image: require('../res/image/aburrido.png'),
      video: `${uri}/aburrido.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ALEGRE',
      search_name_es: 'ALEGRE',
      image: require('../res/image/alegre.png'),
      video: `${uri}/alegre.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AMAR',
      search_name_es: 'AMAR',
      image: require('../res/image/amar.png'),
      video: `${uri}/amar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASUSTADO',
      search_name_es: 'ASUSTADO',
      image: require('../res/image/asustado.png'),
      video: `${uri}/asustado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CANSADO',
      search_name_es: 'CANSADO',
      image: require('../res/image/cansado.png'),
      video: `${uri}/cansado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAPRICHOSO',
      search_name_es: 'CAPRICHOSO',
      image: require('../res/image/caprichoso.png'),
      video: `${uri}/caprichoso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CONTENTO',
      search_name_es: 'CONTENTO',
      image: require('../res/image/contento.png'),
      video: `${uri}/contento.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CULPA',
      search_name_es: 'CULPA',
      image: require('../res/image/culpa.png'),
      video: `${uri}/culpa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DEPRIMIDO',
      search_name_es: 'DEPRIMIDO',
      image: require('../res/image/deprimido.png'),
      video: `${uri}/deprimido.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ENOJADO',
      search_name_es: 'ENOJADO',
      image: require('../res/image/enojado.png'),
      video: `${uri}/enojado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FELIZ',
      search_name_es: 'FELIZ',
      image: require('../res/image/feliz.png'),
      video: `${uri}/feliz.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GRACIOSO',
      search_name_es: 'GRACIOSO',
      image: require('../res/image/gracioso.png'),
      video: `${uri}/gracioso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LLORAR',
      search_name_es: 'LLORAR',
      image: require('../res/image/llorar.png'),
      video: `${uri}/llorar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MIEDOSO',
      search_name_es: 'MIEDOSO',
      image: require('../res/image/miedoso.png'),
      video: `${uri}/miedoso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NERVIOSO',
      search_name_es: 'NERVIOSO',
      image: require('../res/image/nervioso.png'),
      video: `${uri}/nervioso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ORGULLOSO',
      search_name_es: 'ORGULLOSO',
      image: require('../res/image/orgulloso.png'),
      video: `${uri}/orgulloso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PREOCUPADO',
      search_name_es: 'PREOCUPADO',
      image: require('../res/image/preocupado.png'),
      video: `${uri}/preocupado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SENTIMIENTOS',
      search_name_es: 'SENTIMIENTOS',
      image: require('../res/image/los-sentimientos.png'),
      video: `${uri}/los-sentimientos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SORPRENDIDO',
      search_name_es: 'SORPRENDIDO',
      image: require('../res/image/sorprendido.png'),
      video: `${uri}/sorprendido.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TÍMIDO',
      search_name_es: 'TIMIDO',
      image: require('../res/image/timido.png'),
      video: `${uri}/timido.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TRANQUILO',
      search_name_es: 'TRANQUILO',
      image: require('../res/image/tranquilo.png'),
      video: `${uri}/tranquilo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TRISTE',
      search_name_es: 'TRISTE',
      image: require('../res/image/triste.png'),
      video: `${uri}/triste.mp4`,
      downloaded: false,
    },
  ],
});
