export const food = uri => ({
  name_es: 'ALIMENTOS',
  icon: require('../res/icon/los-alimentos.png'),
  hasSubcategories: true,
  videos: [
    {
      name_es: 'BANANA',
      search_name_es: 'BANANA',
      subcategory: 'FRUTAS',
      image: require('../res/image/banana.png'),
      video: `${uri}/banana.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FRUTA',
      search_name_es: 'FRUTA',
      subcategory: 'FRUTAS',
      image: require('../res/image/fruta.png'),
      video: `${uri}/fruta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FRUTILLA',
      search_name_es: 'FRUTILLA',
      subcategory: 'FRUTAS',
      image: require('../res/image/frutilla.png'),
      video: `${uri}/frutilla.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LIMÓN',
      search_name_es: 'LIMON',
      subcategory: 'FRUTAS',
      image: require('../res/image/limon.png'),
      video: `${uri}/limon.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MANDARINA',
      search_name_es: 'MANDARINA',
      subcategory: 'FRUTAS',
      image: require('../res/image/mandarina.png'),
      video: `${uri}/mandarina.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MANZANA',
      search_name_es: 'MANZANA',
      subcategory: 'FRUTAS',
      image: require('../res/image/manzana.png'),
      video: `${uri}/manzana.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NARANJA',
      search_name_es: 'NARANJA',
      subcategory: 'FRUTAS',
      image: require('../res/image/naranja-fruta.png'),
      video: `${uri}/naranja-fruta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'UVA',
      search_name_es: 'UVA',
      subcategory: 'FRUTAS',
      image: require('../res/image/uva.png'),
      video: `${uri}/uva.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CEBOLLA',
      search_name_es: 'CEBOLLA',
      subcategory: 'VERDURAS',
      image: require('../res/image/cebolla.png'),
      video: `${uri}/cebolla.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CHOCLO',
      search_name_es: 'CHOCLO',
      subcategory: 'VERDURAS',
      image: require('../res/image/choclo.png'),
      video: `${uri}/choclo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ENSALADA',
      search_name_es: 'ENSALADA',
      subcategory: 'VERDURAS',
      image: require('../res/image/ensalada.png'),
      video: `${uri}/ensalada.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LECHUGA',
      search_name_es: 'LECHUGA',
      subcategory: 'VERDURAS',
      image: require('../res/image/lechuga.png'),
      video: `${uri}/lechuga.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAPA',
      search_name_es: 'PAPA',
      subcategory: 'VERDURAS',
      image: require('../res/image/papa.png'),
      video: `${uri}/papa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TOMATE',
      search_name_es: 'TOMATE',
      subcategory: 'VERDURAS',
      image: require('../res/image/tomate.png'),
      video: `${uri}/tomate.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VERDURA',
      search_name_es: 'VERDURA',
      subcategory: 'VERDURAS',
      image: require('../res/image/verdura.png'),
      video: `${uri}/verdura.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ZANAHORIA',
      search_name_es: 'ZANAHORIA',
      subcategory: 'VERDURAS',
      image: require('../res/image/zanahoria.png'),
      video: `${uri}/zanahoria.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ALIMENTOS',
      search_name_es: 'ALIMENTOS',
      subcategory: 'COMIDAS',
      image: require('../res/image/los-alimentos.png'),
      video: `${uri}/los-alimentos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ARROZ',
      search_name_es: 'ARROZ',
      subcategory: 'COMIDAS',
      image: require('../res/image/arroz.png'),
      video: `${uri}/arroz.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASADO',
      search_name_es: 'ASADO',
      subcategory: 'COMIDAS',
      image: require('../res/image/asado.png'),
      video: `${uri}/asado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CARNE',
      search_name_es: 'CARNE',
      subcategory: 'COMIDAS',
      image: require('../res/image/carne.png'),
      video: `${uri}/carne.mp4`,
      downloaded: false,
    },
    {
      name_es: 'EMPANADA',
      search_name_es: 'EMPANADA',
      subcategory: 'COMIDAS',
      image: require('../res/image/empanada.png'),
      video: `${uri}/empanada.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FIAMBRE',
      search_name_es: 'FIAMBRE',
      subcategory: 'COMIDAS',
      image: require('../res/image/fiambre.png'),
      video: `${uri}/fiambre.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FIDEOS',
      search_name_es: 'FIDEOS',
      subcategory: 'COMIDAS',
      image: require('../res/image/fideos.png'),
      video: `${uri}/fideos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GUISO',
      search_name_es: 'GUISO ',
      subcategory: 'COMIDAS',
      image: require('../res/image/guiso.png'),
      video: `${uri}/guiso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HAMBURGUESA',
      search_name_es: 'HAMBURGUESA',
      subcategory: 'COMIDAS',
      image: require('../res/image/hamburguesa.png'),
      video: `${uri}/hamburguesa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HUEVO',
      search_name_es: 'HUEVO',
      subcategory: 'COMIDAS',
      image: require('../res/image/huevo.png'),
      video: `${uri}/huevo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MEDIALUNA',
      search_name_es: 'MEDIALUNA',
      subcategory: 'COMIDAS',
      image: require('../res/image/medialuna.png'),
      video: `${uri}/medialuna.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MILANESA',
      search_name_es: 'MILANESA',
      subcategory: 'COMIDAS',
      image: require('../res/image/milanesa.png'),
      video: `${uri}/milanesa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ÑOQUIS',
      search_name_es: 'ÑOQUIS',
      subcategory: 'COMIDAS',
      image: require('../res/image/noquis.png'),
      video: `${uri}/noquis.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAN',
      search_name_es: 'PAN',
      subcategory: 'COMIDAS',
      image: require('../res/image/pan.png'),
      video: `${uri}/pan.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PANCHO',
      search_name_es: 'PANCHO',
      subcategory: 'COMIDAS',
      image: require('../res/image/pancho.png'),
      video: `${uri}/pancho.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAPAS FRITAS',
      search_name_es: 'PAPAS FRITAS',
      subcategory: 'COMIDAS',
      image: require('../res/image/papas-fritas.png'),
      video: `${uri}/papas-fritas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PIZZA',
      search_name_es: 'PIZZA',
      subcategory: 'COMIDAS',
      image: require('../res/image/pizza.png'),
      video: `${uri}/pizza.mp4`,
      downloaded: false,
    },
    {
      name_es: 'POLLO',
      search_name_es: 'POLLO',
      subcategory: 'COMIDAS',
      image: require('../res/image/pollo.png'),
      video: `${uri}/pollo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'QUESO',
      search_name_es: 'QUESO',
      subcategory: 'COMIDAS',
      image: require('../res/image/queso.png'),
      video: `${uri}/queso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SALCHICHA',
      search_name_es: 'SALCHICHA',
      subcategory: 'COMIDAS',
      image: require('../res/image/salchicha.png'),
      video: `${uri}/salchicha.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SALSA',
      search_name_es: 'SALSA',
      subcategory: 'COMIDAS',
      image: require('../res/image/salsa.png'),
      video: `${uri}/salsa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SANDWICH',
      search_name_es: 'SANDWICH',
      subcategory: 'COMIDAS',
      image: require('../res/image/sandwich.png'),
      video: `${uri}/sandwich.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SOPA',
      search_name_es: 'SOPA',
      subcategory: 'COMIDAS',
      image: require('../res/image/sopa.png'),
      video: `${uri}/sopa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'YOGUR',
      search_name_es: 'YOGUR',
      subcategory: 'COMIDAS',
      image: require('../res/image/yogur.png'),
      video: `${uri}/yogur.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ALFAJOR',
      search_name_es: 'ALFAJOR',
      subcategory: 'POSTRES Y DULCES',
      image: require('../res/image/alfajor.png'),
      video: `${uri}/alfajor.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AZÚCAR',
      search_name_es: 'AZUCAR',
      subcategory: 'POSTRES Y DULCES',
      image: require('../res/image/azucar.png'),
      video: `${uri}/azucar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CARAMELO',
      search_name_es: 'CARAMELO',
      subcategory: 'POSTRES Y DULCES',
      image: require('../res/image/caramelo.png'),
      video: `${uri}/caramelo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CHOCOLATE',
      search_name_es: 'CHOCOLATE',
      subcategory: 'POSTRES Y DULCES',
      image: require('../res/image/chocolate.png'),
      video: `${uri}/chocolate.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DULCE',
      search_name_es: 'DULCE',
      subcategory: 'POSTRES Y DULCES',
      image: require('../res/image/dulce.png'),
      video: `${uri}/dulce.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FLAN',
      search_name_es: 'FLAN',
      subcategory: 'POSTRES Y DULCES',
      image: require('../res/image/flan.png'),
      video: `${uri}/flan.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GALLETITAS',
      search_name_es: 'GALLETITAS',
      subcategory: 'POSTRES Y DULCES',
      image: require('../res/image/galletitas.png'),
      video: `${uri}/galletitas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GELATINA',
      search_name_es: 'GELATINA ',
      subcategory: 'POSTRES Y DULCES',
      image: require('../res/image/gelatina.png'),
      video: `${uri}/gelatina.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HELADO',
      search_name_es: 'HELADO',
      subcategory: 'POSTRES Y DULCES',
      image: require('../res/image/helado.png'),
      video: `${uri}/helado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'POSTRE',
      search_name_es: 'POSTRE',
      subcategory: 'POSTRES Y DULCES',
      image: require('../res/image/postre.png'),
      video: `${uri}/postre.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TORTA',
      search_name_es: 'TORTA',
      subcategory: 'POSTRES Y DULCES',
      image: require('../res/image/torta.png'),
      video: `${uri}/torta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAFÉ',
      search_name_es: 'CAFE',
      subcategory: 'INFUSIONES',
      image: require('../res/image/cafe.png'),
      video: `${uri}/cafe.mp4`,
      downloaded: false,
    },
    {
      name_es: 'JUGO',
      search_name_es: 'JUGO',
      subcategory: 'INFUSIONES',
      image: require('../res/image/jugo.png'),
      video: `${uri}/jugo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MATE',
      search_name_es: 'MATE',
      subcategory: 'INFUSIONES',
      image: require('../res/image/mate.png'),
      video: `${uri}/mate.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TÉ',
      search_name_es: 'TE',
      subcategory: 'INFUSIONES',
      image: require('../res/image/te.png'),
      video: `${uri}/te.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ACEITE',
      search_name_es: 'ACEITE',
      subcategory: 'INGREDIENTES BÁSICOS',
      image: require('../res/image/aceite.png'),
      video: `${uri}/aceite.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AGUA',
      search_name_es: 'AGUA',
      subcategory: 'INGREDIENTES BÁSICOS',
      image: require('../res/image/agua.png'),
      video: `${uri}/agua.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LECHE',
      search_name_es: 'LECHE',
      subcategory: 'INGREDIENTES BÁSICOS',
      image: require('../res/image/leche.png'),
      video: `${uri}/leche.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MANTECA',
      search_name_es: 'MANTECA',
      subcategory: 'INGREDIENTES BÁSICOS',
      image: require('../res/image/manteca.png'),
      video: `${uri}/manteca.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SAL',
      search_name_es: 'SAL',
      subcategory: 'INGREDIENTES BÁSICOS',
      image: require('../res/image/sal.png'),
      video: `${uri}/sal.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ALMUERZO',
      search_name_es: 'ALMUERZO',
      subcategory: 'CONCEPTOS GENERALES',
      image: require('../res/image/almuerzo.png'),
      video: `${uri}/almuerzo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CENA',
      search_name_es: 'CENA',
      subcategory: 'CONCEPTOS GENERALES',
      image: require('../res/image/cena.png'),
      video: `${uri}/cena.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DESAYUNO',
      search_name_es: 'DESAYUNO',
      subcategory: 'CONCEPTOS GENERALES',
      image: require('../res/image/desayuno.png'),
      video: `${uri}/desayuno.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MERIENDA',
      search_name_es: 'MERIENDA',
      subcategory: 'CONCEPTOS GENERALES',
      image: require('../res/image/merienda.png'),
      video: `${uri}/merienda.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ME GUSTA',
      search_name_es: 'ME GUSTA',
      subcategory: 'CONCEPTOS GENERALES',
      image: require('../res/image/me-gusta.png'),
      video: `${uri}/me-gusta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NO ME GUSTA',
      search_name_es: 'NO ME GUSTA',
      subcategory: 'CONCEPTOS GENERALES',
      image: require('../res/image/no-me-gusta.png'),
      video: `${uri}/no-me-gusta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PLATO',
      search_name_es: 'PLATO',
      subcategory: 'CONCEPTOS GENERALES',
      image: require('../res/image/plato.png'),
      video: `${uri}/plato.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RICO',
      search_name_es: 'RICO',
      subcategory: 'CONCEPTOS GENERALES',
      image: require('../res/image/rico.png'),
      video: `${uri}/rico.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SALADO',
      search_name_es: 'SALADO',
      subcategory: 'CONCEPTOS GENERALES',
      image: require('../res/image/salado.png'),
      video: `${uri}/salado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SERVILLETA',
      search_name_es: 'SERVILLETA',
      subcategory: 'CONCEPTOS GENERALES',
      image: require('../res/image/servilleta.png'),
      video: `${uri}/servilleta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TENEDOR',
      search_name_es: 'TENEDOR',
      subcategory: 'CONCEPTOS GENERALES',
      image: require('../res/image/tenedor.png'),
      video: `${uri}/tenedor.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TENER HAMBRE',
      search_name_es: 'TENER HAMBRE',
      subcategory: 'CONCEPTOS GENERALES',
      image: require('../res/image/tener-hambre.png'),
      video: `${uri}/tener-hambre.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TENER SED',
      search_name_es: 'TENER SED',
      subcategory: 'CONCEPTOS GENERALES',
      image: require('../res/image/tener-sed.png'),
      video: `${uri}/tener-sed.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VASO',
      search_name_es: 'VASO',
      subcategory: 'CONCEPTOS GENERALES',
      image: require('../res/image/vaso.png'),
      video: `${uri}/vaso.mp4`,
      downloaded: false,
    },
  ],
});
