export const freeTime = (uri) => ({
  name_es: 'TIEMPO LIBRE',
  icon: require('../res/icon/tiempo-libre.png'),
  hasSubcategories: true,
  videos: [
    {
      name_es: 'AMIGOS',
      search_name_es: 'AMIGOS',
      subcategory: 'CUMPLEAÑOS',
      image: require('../res/image/amigos.png'),
      video: `${uri}/amigos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DISFRAZ',
      search_name_es: 'DISFRAZ',
      subcategory: 'CUMPLEAÑOS',
      image: require('../res/image/disfraz.png'),
      video: `${uri}/disfraz.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FIESTA DE CUMPLEAÑOS',
      search_name_es: 'FIESTA DE CUMPLEAÑOS',
      subcategory: 'CUMPLEAÑOS',
      image: require('../res/image/la-fiesta-de-cumpleanos.png'),
      video: `${uri}/la-fiesta-de-cumpleanos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GLOBOS',
      search_name_es: 'GLOBOS',
      subcategory: 'CUMPLEAÑOS',
      image: require('../res/image/globos.png'),
      video: `${uri}/globos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MÚSICA',
      search_name_es: 'MUSICA',
      subcategory: 'CUMPLEAÑOS',
      image: require('../res/image/musica.png'),
      video: `${uri}/musica.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAYASO',
      search_name_es: 'PAYASO',
      subcategory: 'CUMPLEAÑOS',
      image: require('../res/image/payaso.png'),
      video: `${uri}/payaso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RUIDO',
      search_name_es: 'RUIDO',
      subcategory: 'CUMPLEAÑOS',
      image: require('../res/image/ruido.png'),
      video: `${uri}/ruido.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VELA',
      search_name_es: 'VELA',
      subcategory: 'CUMPLEAÑOS',
      image: require('../res/image/vela.png'),
      video: `${uri}/vela.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VIBRACIÓN',
      search_name_es: 'VIBRACION',
      subcategory: 'CUMPLEAÑOS',
      image: require('../res/image/vibracion.png'),
      video: `${uri}/vibracion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ÁRBOL',
      search_name_es: 'ARBOL',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/arbol.png'),
      video: `${uri}/arbol.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BOTE',
      search_name_es: 'BOTE',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/bote.png'),
      video: `${uri}/bote.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CARPA',
      search_name_es: 'CARPA',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/carpa.png'),
      video: `${uri}/carpa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CIELO',
      search_name_es: 'CIELO',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/cielo.png'),
      video: `${uri}/cielo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAMPAMENTO',
      search_name_es: 'CAMPAMENTO',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/el-campamento.png'),
      video: `${uri}/el-campamento.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESTRELLA',
      search_name_es: 'ESTRELLA',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/estrella.png'),
      video: `${uri}/estrella.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FLOR',
      search_name_es: 'FLOR',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/flor.png'),
      video: `${uri}/flor.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FUEGO',
      search_name_es: 'FUEGO',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/fuego.png'),
      video: `${uri}/fuego.mp4`,
      downloaded: false,
    },
    {
      name_es: 'JARDÍN',
      search_name_es: 'JARDIN',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/jardin.png'),
      video: `${uri}/jardin.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LAGO',
      search_name_es: 'LAGO',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/lago.png'),
      video: `${uri}/lago.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LINTERNA',
      search_name_es: 'LINTERNA',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/linterna.png'),
      video: `${uri}/linterna.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LUNA',
      search_name_es: 'LUNA',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/luna.png'),
      video: `${uri}/luna.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MONTAÑAS',
      search_name_es: 'MONTAÑAS',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/montanas.png'),
      video: `${uri}/montanas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PASTO',
      search_name_es: 'PASTO',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/pasto.png'),
      video: `${uri}/pasto.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PIEDRA',
      search_name_es: 'PIEDRA',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/piedra.png'),
      video: `${uri}/piedra.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RÍO',
      search_name_es: 'RIO',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/rio.png'),
      video: `${uri}/rio.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SOL',
      search_name_es: 'SOL',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/sol.png'),
      video: `${uri}/sol.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TIERRA',
      search_name_es: 'TIERRA',
      subcategory: 'CAMPAMENTO',
      image: require('../res/image/tierra.png'),
      video: `${uri}/tierra.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ARENA',
      search_name_es: 'ARENA',
      subcategory: 'PLAYA',
      image: require('../res/image/arena.png'),
      video: `${uri}/arena.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BALDE',
      search_name_es: 'BALDE',
      subcategory: 'PLAYA',
      image: require('../res/image/balde.png'),
      video: `${uri}/balde.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BARCO',
      search_name_es: 'BARCO',
      subcategory: 'PLAYA',
      image: require('../res/image/barco.png'),
      video: `${uri}/barco.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GORRO',
      search_name_es: 'GORRO',
      subcategory: 'PLAYA',
      image: require('../res/image/gorro.png'),
      video: `${uri}/gorro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PLAYA',
      search_name_es: 'PLAYA',
      subcategory: 'PLAYA',
      image: require('../res/image/la-playa.png'),
      video: `${uri}/la-playa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MAR',
      search_name_es: 'MAR',
      subcategory: 'PLAYA',
      image: require('../res/image/mar.png'),
      video: `${uri}/mar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PALITA',
      search_name_es: 'PALITA',
      subcategory: 'PLAYA',
      image: require('../res/image/palita.png'),
      video: `${uri}/palita.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SOMBRILLA',
      search_name_es: 'SOMBRILLA',
      subcategory: 'PLAYA',
      image: require('../res/image/sombrilla.png'),
      video: `${uri}/sombrilla.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VACACIONES',
      search_name_es: 'VACACIONES',
      subcategory: 'PLAYA',
      image: require('../res/image/vacaciones.png'),
      video: `${uri}/vacaciones.mp4`,
      downloaded: false,
    },
    {
      name_es: 'APLAUDIR (OYENTES)',
      search_name_es: 'APLAUDIR (OYENTES)',
      subcategory: 'ACCIONES',
      image: require('../res/image/aplaudir-(oyentes).png'),
      video: `${uri}/aplaudir-(oyentes).mp4`,
      downloaded: false,
    },
    {
      name_es: 'APLAUDIR (SORDOS)',
      search_name_es: 'APLAUDIR (SORDOS)',
      subcategory: 'ACCIONES',
      image: require('../res/image/aplaudir-(sordos).png'),
      video: `${uri}/aplaudir-(sordos).mp4`,
      downloaded: false,
    },
    {
      name_es: 'AYUDAR',
      search_name_es: 'AYUDAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/ayudar.png'),
      video: `${uri}/ayudar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BAILAR',
      search_name_es: 'BAILAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/bailar.png'),
      video: `${uri}/bailar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CANTAR',
      search_name_es: 'CANTAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/cantar.png'),
      video: `${uri}/cantar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CONOCER',
      search_name_es: 'CONOCER',
      subcategory: 'ACCIONES',
      image: require('../res/image/conocer.png'),
      video: `${uri}/conocer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CUIDAR',
      search_name_es: 'CUIDAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/cuidar.png'),
      video: `${uri}/cuidar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DESENCHUFAR',
      search_name_es: 'DESENCHUFAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/desenchufar.png'),
      video: `${uri}/desenchufar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FILMAR',
      search_name_es: 'FILMAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/filmar.png'),
      video: `${uri}/filmar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PESCAR',
      search_name_es: 'PESCAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/pescar.png'),
      video: `${uri}/pescar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'REGALAR',
      search_name_es: 'REGALAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/regalar.png'),
      video: `${uri}/regalar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SACAR FOTOS',
      search_name_es: 'SACAR FOTOS',
      subcategory: 'ACCIONES',
      image: require('../res/image/sacar-fotos.png'),
      video: `${uri}/sacar-fotos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VISITAR',
      search_name_es: 'VISITAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/visitar.png'),
      video: `${uri}/visitar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAMPO',
      search_name_es: 'CAMPO',
      subcategory: 'LUGARES',
      image: require('../res/image/campo.png'),
      video: `${uri}/campo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'IGLESIA',
      search_name_es: 'IGLESIA',
      subcategory: 'LUGARES',
      image: require('../res/image/iglesia.png'),
      video: `${uri}/iglesia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PARQUE DE DIVERSIONES',
      search_name_es: 'PARQUE DE DIVERSIONES',
      subcategory: 'LUGARES',
      image: require('../res/image/parque-de-diversiones.png'),
      video: `${uri}/parque-de-diversiones.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PILETA',
      search_name_es: 'PILETA',
      subcategory: 'LUGARES',
      image: require('../res/image/pileta.png'),
      video: `${uri}/pileta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ZOOLÓGICO',
      search_name_es: 'ZOOLOGICO',
      subcategory: 'LUGARES',
      image: require('../res/image/zoologico.png'),
      video: `${uri}/el-zoologico.mp4`,
      downloaded: false,
    },
  ],
});
