export const geography = uri => ({
  name_es: 'GEOGRAFIA',
  icon: require('../res/icon/geografia.png'),
  hasSubcategories: true,
  videos: [
    {
      name_es: 'AFRICA',
      search_name_es: 'AFRICA',
      subcategory: 'CONTINENTES',
      image: require('../res/image/africa.png'),
      video: `${uri}/africa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AMÉRICA',
      search_name_es: 'AMERICA',
      subcategory: 'CONTINENTES',
      image: require('../res/image/america.png'),
      video: `${uri}/america.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AMÉRICA DEL SUR',
      search_name_es: 'AMERICA DEL SUR',
      subcategory: 'CONTINENTES',
      image: require('../res/image/america-del-sur.png'),
      video: `${uri}/america-del-sur.webm`,
      downloaded: false,
    },
    {
      name_es: 'AMÉRICA DEL NORTE',
      search_name_es: 'AMERICA DEL NORTE',
      subcategory: 'CONTINENTES',
      image: require('../res/image/america-norte.png'),
      video: `${uri}/america-norte.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AMÉRICA CENTRAL',
      search_name_es: 'AMERICA CENTRAL',
      subcategory: 'CONTINENTES',
      image: require('../res/image/america-central.png'),
      video: `${uri}/america-central.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AMÉRICA LATINA',
      search_name_es: 'AMERICA LATINA',
      subcategory: 'CONTINENTES',
      image: require('../res/image/latinoamerica.png'),
      video: `${uri}/latinoamerica.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ASIA',
      search_name_es: 'ASIA',
      subcategory: 'CONTINENTES',
      image: require('../res/image/asia.png'),
      video: `${uri}/asia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'EUROPA',
      search_name_es: 'EUROPA',
      subcategory: 'CONTINENTES',
      image: require('../res/image/europa.png'),
      video: `${uri}/europa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OCEANIA',
      search_name_es: 'OCEANIA',
      subcategory: 'CONTINENTES',
      image: require('../res/image/oceania.png'),
      video: `${uri}/oceania.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ALEMANIA',
      search_name_es: 'ALEMANIA',
      subcategory: 'PAÍSES DE EUROPA',
      image: require('../res/image/alemania.png'),
      video: `${uri}/alemania.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESPAÑA',
      search_name_es: 'ESPANA',
      subcategory: 'PAÍSES DE EUROPA',
      image: require('../res/image/espana.png'),
      video: `${uri}/espana.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FRANCIA',
      search_name_es: 'FRANCIA',
      subcategory: 'PAÍSES DE EUROPA',
      image: require('../res/image/francia.png'),
      video: `${uri}/francia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'INGLATERRA',
      search_name_es: 'INGLATERRA',
      subcategory: 'PAÍSES DE EUROPA',
      image: require('../res/image/inglaterra.png'),
      video: `${uri}/inglaterra.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ITALIA',
      search_name_es: 'ITALIA',
      subcategory: 'PAÍSES DE EUROPA',
      image: require('../res/image/italia.png'),
      video: `${uri}/italia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAÍSES BAJOS',
      search_name_es: 'PAISES BAJOS',
      subcategory: 'PAÍSES DE EUROPA',
      image: require('../res/image/paises-bajos.png'),
      video: `${uri}/paises-bajos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RUSIA',
      search_name_es: 'RUSIA',
      subcategory: 'PAÍSES DE EUROPA',
      image: require('../res/image/rusia.png'),
      video: `${uri}/rusia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SUECIA',
      search_name_es: 'SUECIA',
      subcategory: 'PAÍSES DE EUROPA',
      image: require('../res/image/suecia.png'),
      video: `${uri}/suecia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BOLIVIA',
      search_name_es: 'BOLIVIA',
      subcategory: 'PAÍSES DE AMÉRICA',
      image: require('../res/image/bolivia.png'),
      video: `${uri}/bolivia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BRASIL',
      search_name_es: 'BRASIL',
      subcategory: 'PAÍSES DE AMÉRICA',
      image: require('../res/image/brasil.png'),
      video: `${uri}/brasil.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CANADA',
      search_name_es: 'CANADA',
      subcategory: 'PAÍSES DE AMÉRICA',
      image: require('../res/image/canada.png'),
      video: `${uri}/canada.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CHILE',
      search_name_es: 'CHILE',
      subcategory: 'PAÍSES DE AMÉRICA',
      image: require('../res/image/chile.png'),
      video: `${uri}/chile.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COLOMBIA',
      search_name_es: 'COLOMBIA',
      subcategory: 'PAÍSES DE AMÉRICA',
      image: require('../res/image/colombia.png'),
      video: `${uri}/colombia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CUBA',
      search_name_es: 'CUBA',
      subcategory: 'PAÍSES DE AMÉRICA',
      image: require('../res/image/cuba.png'),
      video: `${uri}/cuba.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ECUADOR',
      search_name_es: 'ECUADOR',
      subcategory: 'PAÍSES DE AMÉRICA',
      image: require('../res/image/ecuador.png'),
      video: `${uri}/ecuador.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESTADOS UNIDOS',
      search_name_es: 'ESTADOS UNIDOS',
      subcategory: 'PAÍSES DE AMÉRICA',
      image: require('../res/image/estados-unidos.png'),
      video: `${uri}/estados-unidos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MEJICO',
      search_name_es: 'MEJICO',
      subcategory: 'PAÍSES DE AMÉRICA',
      image: require('../res/image/mejico.png'),
      video: `${uri}/mejico.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PARAGUAY',
      search_name_es: 'PARAGUAY',
      subcategory: 'PAÍSES DE AMÉRICA',
      image: require('../res/image/paraguay.png'),
      video: `${uri}/paraguay.mp4`,
      downloaded: false,
    },
    {
      name_es: 'URUGUAY',
      search_name_es: 'URUGUAY',
      subcategory: 'PAÍSES DE AMÉRICA',
      image: require('../res/image/uruguay.png'),
      video: `${uri}/uruguay.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VENEZUELA',
      search_name_es: 'VENEZUELA',
      subcategory: 'PAÍSES DE AMÉRICA',
      image: require('../res/image/venezuela.png'),
      video: `${uri}/venezuela.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CHINA',
      search_name_es: 'CHINA',
      subcategory: 'PAÍSES DE ASIA',
      image: require('../res/image/china.png'),
      video: `${uri}/china.mp4`,
      downloaded: false,
    },
    {
      name_es: 'JAPÓN',
      search_name_es: 'JAPON',
      subcategory: 'PAÍSES DE ASIA',
      image: require('../res/image/japon.png'),
      video: `${uri}/japon.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AUSTRALIA',
      search_name_es: 'AUSTRALIA',
      subcategory: 'PAÍSES DE OCEANIA',
      image: require('../res/image/australia.png'),
      video: `${uri}/australia.mp4`,
      downloaded: false,
    },
  ],
});
