export const house = uri => ({
  name_es: 'CASA',
  icon: require('../res/icon/la-casa.png'),
  hasSubcategories: true,
  videos: [
    {
      name_es: 'COCINA',
      search_name_es: 'COCINA',
      subcategory: 'COCINA',
      image: require('../res/image/la-cocina.png'),
      video: `${uri}/la-cocina.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COCINA',
      search_name_es: 'COCINA',
      subcategory: 'COCINA',
      image: require('../res/image/cocina.png'),
      video: `${uri}/cocina.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CUCHARA',
      search_name_es: 'CUCHARA',
      subcategory: 'COCINA',
      image: require('../res/image/cuchara.png'),
      video: `${uri}/cuchara.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CUCHILLO',
      search_name_es: 'CUCHILLO',
      subcategory: 'COCINA',
      image: require('../res/image/cuchillo.png'),
      video: `${uri}/cuchillo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESTÁ CALIENTE',
      search_name_es: 'ESTA CALIENTE',
      subcategory: 'COCINA',
      image: require('../res/image/esta-caliente.png'),
      video: `${uri}/esta-caliente.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HELADERA',
      search_name_es: 'HELADERA',
      subcategory: 'COCINA',
      image: require('../res/image/heladera.png'),
      video: `${uri}/heladera.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HORNO',
      search_name_es: 'HORNO',
      subcategory: 'COCINA',
      image: require('../res/image/horno.png'),
      video: `${uri}/horno.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LAVARROPAS',
      search_name_es: 'LAVARROPAS',
      subcategory: 'COCINA',
      image: require('../res/image/lavarropas.png'),
      video: `${uri}/lavarropas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAVA',
      search_name_es: 'PAVA',
      subcategory: 'COCINA',
      image: require('../res/image/pava.png'),
      video: `${uri}/pava.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TACHO DE BASURA',
      search_name_es: 'TACHO DE BASURA',
      subcategory: 'COCINA',
      image: require('../res/image/tacho-de-basura.png'),
      video: `${uri}/tacho-de-basura.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ALMOHADA',
      search_name_es: 'ALMOHADA',
      subcategory: 'DORMITORIO',
      image: require('../res/image/almohada.png'),
      video: `${uri}/almohada.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAMA',
      search_name_es: 'CAMA',
      subcategory: 'DORMITORIO',
      image: require('../res/image/cama.png'),
      video: `${uri}/cama.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DIARIO',
      search_name_es: 'DIARIO',
      subcategory: 'DORMITORIO',
      image: require('../res/image/diario.png'),
      video: `${uri}/diario.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DORMITORIO',
      search_name_es: 'DORMITORIO',
      subcategory: 'DORMITORIO',
      image: require('../res/image/el-dormitorio.png'),
      video: `${uri}/el-dormitorio.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FRAZADA',
      search_name_es: 'FRAZADA',
      subcategory: 'DORMITORIO',
      image: require('../res/image/frazada.png'),
      video: `${uri}/frazada.mp4`,
      downloaded: false,
    },
    {
      name_es: 'JUGUETES',
      search_name_es: 'JUGUETES',
      subcategory: 'DORMITORIO',
      image: require('../res/image/juguetes.png'),
      video: `${uri}/juguetes.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LIBRO DE CUENTOS',
      search_name_es: 'LIBRO DE CUENTOS',
      subcategory: 'DORMITORIO',
      image: require('../res/image/libro-de-cuentos.png'),
      video: `${uri}/libro-de-cuentos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MESITA DE LUZ',
      search_name_es: 'MESITA DE LUZ',
      subcategory: 'DORMITORIO',
      image: require('../res/image/mesita-de-luz.png'),
      video: `${uri}/mesita-de-luz.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PLACARD',
      search_name_es: 'PLACARD',
      subcategory: 'DORMITORIO',
      image: require('../res/image/placard.png'),
      video: `${uri}/placard.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ROPA',
      search_name_es: 'ROPA',
      subcategory: 'DORMITORIO',
      image: require('../res/image/ropa.png'),
      video: `${uri}/ropa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SÁBANA',
      search_name_es: 'SABANA',
      subcategory: 'DORMITORIO',
      image: require('../res/image/sabana.png'),
      video: `${uri}/sabana.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BAÑO',
      search_name_es: 'BAÑO',
      subcategory: 'BAÑO',
      image: require('../res/image/el-bano.png'),
      video: `${uri}/el-bano.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CANILLA',
      search_name_es: 'CANILLA',
      subcategory: 'BAÑO',
      image: require('../res/image/canilla.png'),
      video: `${uri}/canilla.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DUCHA',
      search_name_es: 'DUCHA',
      subcategory: 'BAÑO',
      image: require('../res/image/ducha.png'),
      video: `${uri}/ducha.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESPEJO',
      search_name_es: 'ESPEJO',
      subcategory: 'BAÑO',
      image: require('../res/image/espejo.png'),
      video: `${uri}/espejo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'INODORO',
      search_name_es: 'INODORO',
      subcategory: 'BAÑO',
      image: require('../res/image/inodoro.png'),
      video: `${uri}/inodoro.mp4`,
      downloaded: false,
    },
    {
      name_es: 'JABÓN',
      search_name_es: 'JABON',
      subcategory: 'BAÑO',
      image: require('../res/image/jabon.png'),
      video: `${uri}/jabon.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OCUPADO',
      search_name_es: 'OCUPADO',
      subcategory: 'BAÑO',
      image: require('../res/image/ocupado.png'),
      video: `${uri}/ocupado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAPEL HIGIÉNICO',
      search_name_es: 'PAPEL HIGIENICO',
      subcategory: 'BAÑO',
      image: require('../res/image/papel-higienico.png'),
      video: `${uri}/papel-higienico.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TACHO DE BASURA',
      search_name_es: 'TACHO DE BASURA',
      subcategory: 'BAÑO',
      image: require('../res/image/tacho-de-basura.png'),
      video: `${uri}/tacho-de-basura.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TOALLA',
      search_name_es: 'TOALLA',
      subcategory: 'BAÑO',
      image: require('../res/image/toalla.png'),
      video: `${uri}/toalla.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CONTROL REMOTO',
      search_name_es: 'CONTROL REMOTO',
      subcategory: 'LIVING COMEDOR',
      image: require('../res/image/control-remoto.png'),
      video: `${uri}/control-remoto.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LIVING',
      search_name_es: 'LIVING',
      subcategory: 'LIVING COMEDOR',
      image: require('../res/image/living.png'),
      video: `${uri}/living.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MUEBLES',
      search_name_es: 'MUEBLES',
      subcategory: 'LIVING COMEDOR',
      image: require('../res/image/muebles.png'),
      video: `${uri}/muebles.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MESA',
      search_name_es: 'MESA',
      subcategory: 'LIVING COMEDOR',
      image: require('../res/image/mesa.png'),
      video: `${uri}/mesa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SENTARSE',
      search_name_es: 'SENTARSE',
      subcategory: 'LIVING COMEDOR',
      image: require('../res/image/sentarse.png'),
      video: `${uri}/sentarse.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SILLA',
      search_name_es: 'SILLA',
      subcategory: 'LIVING COMEDOR',
      image: require('../res/image/silla.png'),
      video: `${uri}/silla.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SOFÁ',
      search_name_es: 'SOFA',
      subcategory: 'LIVING COMEDOR',
      image: require('../res/image/sofa.png'),
      video: `${uri}/sofa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TELEVISOR',
      search_name_es: 'TELEVISOR',
      subcategory: 'LIVING COMEDOR',
      image: require('../res/image/televisor.png'),
      video: `${uri}/televisor.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VENTILADOR',
      search_name_es: 'VENTILADOR',
      subcategory: 'LIVING COMEDOR',
      image: require('../res/image/ventilador.png'),
      video: `${uri}/ventilador.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CASA',
      search_name_es: 'CASA',
      subcategory: 'GENERAL',
      image: require('../res/image/la-casa.png'),
      video: `${uri}/la-casa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LLAVE',
      search_name_es: 'LLAVE',
      subcategory: 'GENERAL',
      image: require('../res/image/llave.png'),
      video: `${uri}/llave.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LIMPIO',
      search_name_es: 'LIMPIO',
      subcategory: 'GENERAL',
      image: require('../res/image/limpio.png'),
      video: `${uri}/limpio.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PUERTA',
      search_name_es: 'PUERTA',
      subcategory: 'GENERAL',
      image: require('../res/image/puerta.png'),
      video: `${uri}/puerta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SUCIO',
      search_name_es: 'SUCIO',
      subcategory: 'GENERAL',
      image: require('../res/image/sucio.png'),
      video: `${uri}/sucio.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TOCAR TIMBRE',
      search_name_es: 'TOCAR TIMBRE',
      subcategory: 'GENERAL',
      image: require('../res/image/tocar-timbre.png'),
      video: `${uri}/tocar-timbre.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VENTANA',
      search_name_es: 'VENTANA',
      subcategory: 'GENERAL',
      image: require('../res/image/ventana.png'),
      video: `${uri}/ventana.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BARRER',
      search_name_es: 'BARRER',
      subcategory: 'ACCIONES',
      image: require('../res/image/barrer.png'),
      video: `${uri}/barrer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BAÑAR',
      search_name_es: 'BAÑAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/banar.png'),
      video: `${uri}/banar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CEPILLAR LOS DIENTES',
      search_name_es: 'CEPILLAR LOS DIENTES',
      subcategory: 'ACCIONES',
      image: require('../res/image/cepillar-los-dientes.png'),
      video: `${uri}/cepillar-los-dientes.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COCINAR',
      search_name_es: 'COCINAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/cocinar.png'),
      video: `${uri}/cocinar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DORMIR',
      search_name_es: 'DORMIR',
      subcategory: 'ACCIONES',
      image: require('../res/image/dormir.png'),
      video: `${uri}/dormir.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LAVAR LOS PLATOS',
      search_name_es: 'LAVAR LOS PLATOS',
      subcategory: 'ACCIONES',
      image: require('../res/image/lavar-los-platos.png'),
      video: `${uri}/lavar-los-platos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LAVAR ROPA',
      search_name_es: 'LAVAR ROPA',
      subcategory: 'ACCIONES',
      image: require('../res/image/lavar-ropa.png'),
      video: `${uri}/lavar-ropa.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LAVARSE LAS MANOS',
      search_name_es: 'LAVARSE LAS MANOS',
      subcategory: 'ACCIONES',
      image: require('../res/image/lavarse-las-manos.png'),
      video: `${uri}/lavarse-las-manos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LEER',
      search_name_es: 'LEER',
      subcategory: 'ACCIONES',
      image: require('../res/image/leer.png'),
      video: `${uri}/leer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LIMPIAR',
      search_name_es: 'LIMPIAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/limpiar.png'),
      video: `${uri}/limpiar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LLEVAR',
      search_name_es: 'LLEVAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/llevar.png'),
      video: `${uri}/llevar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PLANCHAR',
      search_name_es: 'PLANCHAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/planchar.png'),
      video: `${uri}/planchar.mp4`,
      downloaded: false,
    },
  ],
});
