export const professions = uri => ({
  name_es: 'PROFESIONES',
  icon: require('../res/icon/las-profesiones.png'),
  subcategories: [
    {
      name_es: 'PROFESIONES',
      videos: [
        {
          name_es: 'ABOGADO',
          search_name_es: 'ABOGADO',
          image: require('../res/image/abogado.png'),
          video: `${uri}/abogado.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ACOMPAÑANTE TERAPÉUTICO',
          search_name_es: 'ACOMPAÑANTE TERAPEUTICO',
          image: require('../res/image/acompanante-terapeutico.png'),
          video: `${uri}/acompanante-terapeutico.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ADMINISTRATIVO',
          search_name_es: 'ADMINISTRATIVO',
          image: require('../res/image/administrativo.png'),
          video: `${uri}/administrativo.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ARQUITECTO',
          search_name_es: 'ARQUITECTO',
          image: require('../res/image/arquitecto.png'),
          video: `${uri}/arquitecto.mp4`,
          downloaded: false,
        },
        {
          name_es: 'BOMBEROS',
          search_name_es: 'BOMBEROS',
          image: require('../res/image/bomberos.png'),
          video: `${uri}/bomberos.mp4`,
          downloaded: false,
        },
        {
          name_es: 'CARPINTERO',
          search_name_es: 'CARPINTERO',
          image: require('../res/image/carpintero.png'),
          video: `${uri}/carpintero.mp4`,
          downloaded: false,
        },
        {
          name_es: 'CHEF',
          search_name_es: 'CHEF',
          image: require('../res/image/chef.png'),
          video: `${uri}/chef.mp4`,
          downloaded: false,
        },
        {
          name_es: 'CHOFER',
          search_name_es: 'CHOFER',
          image: require('../res/image/chofer.png'),
          video: `${uri}/chofer.mp4`,
          downloaded: false,
        },
        {
          name_es: 'CONTADOR',
          search_name_es: 'CONTADOR',
          image: require('../res/image/contador.png'),
          video: `${uri}/contador.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ELECTRICISTA',
          search_name_es: 'ELECTRICISTA',
          image: require('../res/image/electricista.png'),
          video: `${uri}/electricista.mp4`,
          downloaded: false,
        },
        {
          name_es: 'EMPLEADO',
          search_name_es: 'EMPLEADO',
          image: require('../res/image/empleado.png'),
          video: `${uri}/empleado.mp4`,
          downloaded: false,
        },
        {
          name_es: 'GASISTA',
          search_name_es: 'GASISTA',
          image: require('../res/image/gasista.png'),
          video: `${uri}/gasista.mp4`,
          downloaded: false,
        },
        {
          name_es: 'PINTOR',
          search_name_es: 'PINTOR',
          image: require('../res/image/pintor.png'),
          video: `${uri}/pintor.mp4`,
          downloaded: false,
        },
        {
          name_es: 'PLOMERO',
          search_name_es: 'PLOMERO',
          image: require('../res/image/plomero.png'),
          video: `${uri}/plomero.mp4`,
          downloaded: false,
        },
        {
          name_es: 'POLICÍA',
          search_name_es: 'POLICIA',
          image: require('../res/image/policia.png'),
          video: `${uri}/policia.mp4`,
          downloaded: false,
        },
        {
          name_es: 'PROFESIONALES',
          search_name_es: 'PROFESIONALES',
          image: require('../res/image/profesionales.png'),
          video: `${uri}/profesionales.mp4`,
          downloaded: false,
        },
        {
          name_es: 'SECRETARIA',
          search_name_es: 'SECRETARIA',
          image: require('../res/image/secretaria.png'),
          video: `${uri}/secretaria.mp4`,
          downloaded: false,
        },
        {
          name_es: 'TAXISTA',
          search_name_es: 'TAXISTA',
          image: require('../res/image/taxista.png'),
          video: `${uri}/taxista.mp4`,
          downloaded: false,
        },
        {
          name_es: 'VETERINARIO',
          search_name_es: 'VETERINARIO',
          image: require('../res/image/veterinario.png'),
          video: `${uri}/veterinario.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'MATERIALES',
      videos: [
        {
          name_es: 'MADERA',
          search_name_es: 'MADERA',
          image: require('../res/image/madera.png'),
          video: `${uri}/madera.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MATERIALES',
          search_name_es: 'MATERIALES',
          image: require('../res/image/materiales.png'),
          video: `${uri}/materiales.mp4`,
          downloaded: false,
        },
        {
          name_es: 'METAL',
          search_name_es: 'METAL',
          image: require('../res/image/metal.png'),
          video: `${uri}/metal.mp4`,
          downloaded: false,
        },
        {
          name_es: 'PLÁSTICO',
          search_name_es: 'PLASTICO',
          image: require('../res/image/plastico.png'),
          video: `${uri}/plastico.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'ACCIONES',
      videos: [
        {
          name_es: 'ARREGLAR',
          search_name_es: 'ARREGLAR',
          image: require('../res/image/arreglar.png'),
          video: `${uri}/arreglar.mp4`,
          downloaded: false,
        },
        {
          name_es: 'TRABAJAR',
          search_name_es: 'TRABAJAR',
          image: require('../res/image/trabajar.png'),
          video: `${uri}/trabajar.mp4`,
          downloaded: false,
        },
      ],
    },
  ],
});
