export const school = uri => ({
  name_es: 'ESCUELA',
  icon: require('../res/icon/la-escuela.png'),
  hasSubcategories: true,
  videos: [
    {
      name_es: 'ALUMNOS',
      search_name_es: 'ALUMNOS',
      subcategory: 'PERSONAS',
      image: require('../res/image/alumnos.png'),
      video: `${uri}/alumnos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COMPAÑERO',
      search_name_es: 'COMPAÑERO',
      subcategory: 'PERSONAS',
      image: require('../res/image/companero.png'),
      video: `${uri}/companero.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DIRECTOR',
      search_name_es: 'DIRECTOR',
      subcategory: 'PERSONAS',
      image: require('../res/image/director.png'),
      video: `${uri}/director.mp4`,
      downloaded: false,
    },
    {
      name_es: 'INTÉRPRETE',
      search_name_es: 'INTERPRETE',
      subcategory: 'PERSONAS',
      image: require('../res/image/interprete.png'),
      video: `${uri}/interprete.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PROFESOR',
      search_name_es: 'PROFESOR',
      subcategory: 'PERSONAS',
      image: require('../res/image/profesor.png'),
      video: `${uri}/profesor.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ADHESIVO ESCOLAR',
      search_name_es: 'ADHESIVO ESCOLAR',
      subcategory: 'OBJETOS Y ÚTILES',
      image: require('../res/image/adhesivo-escolar.png'),
      video: `${uri}/adhesivo-escolar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BIROME',
      search_name_es: 'BIROME',
      subcategory: 'OBJETOS Y ÚTILES',
      image: require('../res/image/birome.png'),
      video: `${uri}/birome.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BORRADOR',
      search_name_es: 'BORRADOR',
      subcategory: 'OBJETOS Y ÚTILES',
      image: require('../res/image/borrador.png'),
      video: `${uri}/borrador.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CARTUCHERA',
      search_name_es: 'CARTUCHERA',
      subcategory: 'OBJETOS Y ÚTILES',
      image: require('../res/image/cartuchera.png'),
      video: `${uri}/cartuchera.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DICCIONARIO',
      search_name_es: 'DICCIONARIO',
      subcategory: 'OBJETOS Y ÚTILES',
      image: require('../res/image/diccionario.png'),
      video: `${uri}/diccionario.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GOMA',
      search_name_es: 'GOMA',
      subcategory: 'OBJETOS Y ÚTILES',
      image: require('../res/image/goma.png'),
      video: `${uri}/goma.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GUARDAPOLVO',
      search_name_es: 'GUARDAPOLVO',
      subcategory: 'OBJETOS Y ÚTILES',
      image: require('../res/image/guardapolvo.png'),
      video: `${uri}/guardapolvo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LÁPIZ',
      search_name_es: 'LAPIZ',
      subcategory: 'OBJETOS Y ÚTILES',
      image: require('../res/image/lapiz.png'),
      video: `${uri}/lapiz.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LIBRO DE CUENTOS',
      search_name_es: 'LIBRO DE CUENTOS',
      subcategory: 'OBJETOS Y ÚTILES',
      image: require('../res/image/libro-de-cuentos.png'),
      video: `${uri}/libro-de-cuentos.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MOCHILA',
      search_name_es: 'MOCHILA',
      subcategory: 'OBJETOS Y ÚTILES',
      image: require('../res/image/mochila.png'),
      video: `${uri}/mochila.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAPEL',
      search_name_es: 'PAPEL',
      subcategory: 'OBJETOS Y ÚTILES',
      image: require('../res/image/papel.png'),
      video: `${uri}/papel.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PIZARRÓN',
      search_name_es: 'PIZARRON',
      subcategory: 'OBJETOS Y ÚTILES',
      image: require('../res/image/pizarron.png'),
      video: `${uri}/pizarron.mp4`,
      downloaded: false,
    },
    {
      name_es: 'REGLA',
      search_name_es: 'REGLA',
      subcategory: 'OBJETOS Y ÚTILES',
      image: require('../res/image/regla.png'),
      video: `${uri}/regla.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SACAPUNTAS',
      search_name_es: 'SACAPUNTAS',
      subcategory: 'OBJETOS Y ÚTILES',
      image: require('../res/image/sacapuntas.png'),
      video: `${uri}/sacapuntas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TIJERA',
      search_name_es: 'TIJERA',
      subcategory: 'OBJETOS Y ÚTILES',
      image: require('../res/image/tijera.png'),
      video: `${uri}/tijera.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TÍTULO',
      search_name_es: 'TITULO',
      subcategory: 'OBJETOS Y ÚTILES',
      image: require('../res/image/titulo.png'),
      video: `${uri}/titulo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TIZA',
      search_name_es: 'TIZA',
      subcategory: 'OBJETOS Y ÚTILES',
      image: require('../res/image/tiza.png'),
      video: `${uri}/t.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AULA',
      search_name_es: 'AULA',
      subcategory: 'LUGARES',
      image: require('../res/image/mi-aula.png'),
      video: `${uri}/mi-aula.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BIBLIOTECA',
      search_name_es: 'BIBLIOTECA',
      subcategory: 'LUGARES',
      image: require('../res/image/biblioteca.png'),
      video: `${uri}/biblioteca.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESCUELA',
      search_name_es: 'ESCUELA',
      subcategory: 'LUGARES',
      image: require('../res/image/la-escuela.png'),
      video: `${uri}/la-escuela.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GRADO',
      search_name_es: 'GRADO',
      subcategory: 'LUGARES',
      image: require('../res/image/grado.png'),
      video: `${uri}/grado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'JARDÍN DE INFANTES',
      search_name_es: 'JARDIN DE INFANTES',
      subcategory: 'LUGARES',
      image: require('../res/image/jardin-de-infantes.png'),
      video: `${uri}/jardin-de-infantes.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AGARRAR',
      search_name_es: 'AGARRAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/agarrar.png'),
      video: `${uri}/agarrar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'APRENDER',
      search_name_es: 'APRENDER',
      subcategory: 'ACCIONES',
      image: require('../res/image/aprender.png'),
      video: `${uri}/aprender.mp4`,
      downloaded: false,
    },
    {
      name_es: 'APROBAR',
      search_name_es: 'APROBAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/aprobar.png'),
      video: `${uri}/aprobar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BUSCAR',
      search_name_es: 'BUSCAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/buscar.png'),
      video: `${uri}/buscar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAER',
      search_name_es: 'CAER',
      subcategory: 'ACCIONES',
      image: require('../res/image/caer.png'),
      video: `${uri}/caer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CONTESTAR',
      search_name_es: 'CONTESTAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/contestar.png'),
      video: `${uri}/contestar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COPIAR',
      search_name_es: 'COPIAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/copiar.png'),
      video: `${uri}/copiar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CORREGIR',
      search_name_es: 'CORREGIR',
      subcategory: 'ACCIONES',
      image: require('../res/image/corregir.png'),
      video: `${uri}/corregir.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DIBUJAR',
      search_name_es: 'DIBUJAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/dibujar.png'),
      video: `${uri}/dibujar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DESAPROBAR',
      search_name_es: 'DESAPROBAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/desaprobar.png'),
      video: `${uri}/desaprobar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ENSEÑAR',
      search_name_es: 'ENSEÑAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/ensenar.png'),
      video: `${uri}/ensenar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ENTENDER',
      search_name_es: 'ENTENDER',
      subcategory: 'ACCIONES',
      image: require('../res/image/entender.png'),
      video: `${uri}/entender.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESCRIBIR',
      search_name_es: 'ESCRIBIR',
      subcategory: 'ACCIONES',
      image: require('../res/image/escribir.png'),
      video: `${uri}/escribir.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESTAR PRESENTE',
      search_name_es: 'ESTAR PRESENTE',
      subcategory: 'ACCIONES',
      image: require('../res/image/presente.png'),
      video: `${uri}/presente.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESTUDIAR',
      search_name_es: 'ESTUDIAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/estudiar.png'),
      video: `${uri}/estudiar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'EXPLICAR',
      search_name_es: 'EXPLICAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/explicar.png'),
      video: `${uri}/explicar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FALTAR',
      search_name_es: 'FALTAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/faltar.png'),
      video: `${uri}/faltar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FORMAR FILA',
      search_name_es: 'FORMAR FILA',
      subcategory: 'ACCIONES',
      image: require('../res/image/formar-fila.png'),
      video: `${uri}/formar-fila.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HACIENDO LA TAREA',
      search_name_es: 'HACIENDO LA TAREA',
      subcategory: 'ACCIONES',
      image: require('../res/image/haciendo-la-tarea.png'),
      video: `${uri}/haciendo-la-tarea.mp4`,
      downloaded: false,
    },
    {
      name_es: 'INVESTIGACIÓN',
      search_name_es: 'INVESTIGACION',
      subcategory: 'ACCIONES',
      image: require('../res/image/investigacion.png'),
      video: `${uri}/investigacion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'IR',
      search_name_es: 'IR',
      subcategory: 'ACCIONES',
      image: require('../res/image/ir.png'),
      video: `${uri}/ir.mp4`,
      downloaded: false,
    },
    {
      name_es: 'IZAR LA BANDERA',
      search_name_es: 'IZAR LA BANDERA',
      subcategory: 'ACCIONES',
      image: require('../res/image/izar-la-bandera.png'),
      video: `${uri}/izar-la-bandera.mp4`,
      downloaded: false,
    },
    {
      name_es: 'JUGAR',
      search_name_es: 'JUGAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/jugar.png'),
      video: `${uri}/jugar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LEER',
      search_name_es: 'LEER',
      subcategory: 'ACCIONES',
      image: require('../res/image/leer.png'),
      video: `${uri}/leer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'LLEVAR',
      search_name_es: 'LLEVAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/llevar.png'),
      video: `${uri}/llevar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PEGAR',
      search_name_es: 'PEGAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/pegar.png'),
      video: `${uri}/pegar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NECESITAR',
      search_name_es: 'NECESITAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/necesitar.png'),
      video: `${uri}/necesitar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NO ENTENDER',
      search_name_es: 'NO ENTENDER',
      subcategory: 'ACCIONES',
      image: require('../res/image/no-entender.png'),
      video: `${uri}/no-entender.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NO HACER CASO',
      search_name_es: 'NO HACER CASO',
      subcategory: 'ACCIONES',
      image: require('../res/image/no-hacer-caso.png'),
      video: `${uri}/no-hacer-caso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NO SABER',
      search_name_es: 'NO SABER',
      subcategory: 'ACCIONES',
      image: require('../res/image/no-saber.png'),
      video: `${uri}/no-saber.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OBEDECER',
      search_name_es: 'OBEDECER',
      subcategory: 'ACCIONES',
      image: require('../res/image/obedecer.png'),
      video: `${uri}/obedecer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OLVIDAR',
      search_name_es: 'OLVIDAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/olvidar.png'),
      video: `${uri}/olvidar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PENSAR',
      search_name_es: 'PENSAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/pensar.png'),
      video: `${uri}/pensar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PERDER',
      search_name_es: 'PERDER',
      subcategory: 'ACCIONES',
      image: require('../res/image/perder.png'),
      video: `${uri}/perder.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PORTARSE MAL',
      search_name_es: 'PORTARSE MAL',
      subcategory: 'ACCIONES',
      image: require('../res/image/portarse-mal.png'),
      video: `${uri}/portarse-mal.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PREGUNTAR',
      search_name_es: 'PREGUNTAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/preguntar.png'),
      video: `${uri}/preguntar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RECORDAR',
      search_name_es: 'RECORDAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/recordar.png'),
      video: `${uri}/recordar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RESPETAR',
      search_name_es: 'RESPETAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/respetar.png'),
      video: `${uri}/respetar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SABER',
      search_name_es: 'SABER',
      subcategory: 'ACCIONES',
      image: require('../res/image/saber.png'),
      video: `${uri}/saber.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TIRAR',
      search_name_es: 'TIRAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/tirar.png'),
      video: `${uri}/tirar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TRAER',
      search_name_es: 'TRAER',
      subcategory: 'ACCIONES',
      image: require('../res/image/traer.png'),
      video: `${uri}/traer.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VOLVER',
      search_name_es: 'VOLVER',
      subcategory: 'ACCIONES',
      image: require('../res/image/volver.png'),
      video: `${uri}/volver.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BIOLOGÍA',
      search_name_es: 'BIOLOGIA',
      subcategory: 'MATERIAS',
      image: require('../res/image/biologia.png'),
      video: `${uri}/biologia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CIENCIA',
      search_name_es: 'CIENCIA',
      subcategory: 'MATERIAS',
      image: require('../res/image/ciencia.png'),
      video: `${uri}/ciencia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CIENCIAS NATURALES',
      search_name_es: 'CIENCIAS NATURALES',
      subcategory: 'MATERIAS',
      image: require('../res/image/ciencias-naturales.png'),
      video: `${uri}/ciencias-naturales.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CIENCIAS SOCIALES',
      search_name_es: 'CIENCIAS SOCIALES',
      subcategory: 'MATERIAS',
      image: require('../res/image/ciencias-sociales.png'),
      video: `${uri}/ciencias-sociales.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DIVISIÓN',
      search_name_es: 'DIVISION',
      subcategory: 'MATERIAS',
      image: require('../res/image/division.png'),
      video: `${uri}/division.mp4`,
      downloaded: false,
    },
    {
      name_es: 'EDUCACIÓN FÍSICA',
      search_name_es: 'EDUCACION FISICA',
      subcategory: 'MATERIAS',
      image: require('../res/image/educacion-fisica.png'),
      video: `${uri}/educacion-fisica.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FÍSICA',
      search_name_es: 'FISICA',
      subcategory: 'MATERIAS',
      image: require('../res/image/fisica.png'),
      video: `${uri}/fisica.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HIMNO NACIONAL ARGENTINO',
      search_name_es: 'HIMNO NACIONAL ARGENTINO',
      subcategory: 'MATERIAS',
      image: require('../res/image/himno-nacional-argentino.png'),
      video: `${uri}/himno-nacional-argentino.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HISTORIA',
      search_name_es: 'HISTORIA',
      subcategory: 'MATERIAS',
      image: require('../res/image/historia.png'),
      video: `${uri}/historia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MATEMÁTICA',
      search_name_es: 'MATEMATICA',
      subcategory: 'MATERIAS',
      image: require('../res/image/matematica.png'),
      video: `${uri}/matematica.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MATERIAS',
      search_name_es: 'MATERIAS',
      subcategory: 'MATERIAS',
      image: require('../res/image/las-materias.png'),
      video: `${uri}/las-materias.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MULTIPLICACIÓN',
      search_name_es: 'MULTIPLICACION',
      subcategory: 'MATERIAS',
      image: require('../res/image/multiplicacion.png'),
      video: `${uri}/multiplicacion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PRÁCTICAS DEL LENGUAJE',
      search_name_es: 'PRACTICAS DEL LENGUAJE',
      subcategory: 'MATERIAS',
      image: require('../res/image/practicas-del-lenguaje.png'),
      video: `${uri}/practicas-del-lenguaje.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RESTA',
      search_name_es: 'RESTA',
      subcategory: 'MATERIAS',
      image: require('../res/image/resta.png'),
      video: `${uri}/resta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SUMA',
      search_name_es: 'SUMA',
      subcategory: 'MATERIAS',
      image: require('../res/image/suma.png'),
      video: `${uri}/suma.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TOTAL',
      search_name_es: 'TOTAL',
      subcategory: 'MATERIAS',
      image: require('../res/image/total.png'),
      video: `${uri}/total.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CURIOSO',
      search_name_es: 'CURIOSO',
      subcategory: 'ACTITUD',
      image: require('../res/image/curioso.png'),
      video: `${uri}/curioso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DISTRAÍDO',
      search_name_es: 'DISTRAIDO',
      subcategory: 'ACTITUD',
      image: require('../res/image/distraido.png'),
      video: `${uri}/distraido.mp4`,
      downloaded: false,
    },
    {
      name_es: 'IMPORTANTE',
      search_name_es: 'IMPORTANTE',
      subcategory: 'ACTITUD',
      image: require('../res/image/importante.png'),
      video: `${uri}/importante.mp4`,
      downloaded: false,
    },
    {
      name_es: 'INTELIGENTE',
      search_name_es: 'INTELIGENTE',
      subcategory: 'ACTITUD',
      image: require('../res/image/inteligente.png'),
      video: `${uri}/inteligente.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TRAVIESO',
      search_name_es: 'TRAVIESO',
      subcategory: 'ACTITUD',
      image: require('../res/image/travieso.png'),
      video: `${uri}/travieso.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESCONDIDAS',
      search_name_es: 'ESCONDIDAS',
      subcategory: 'RECREO',
      image: require('../res/image/escondidas.png'),
      video: `${uri}/escondidas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HAMACA',
      search_name_es: 'HAMACA',
      subcategory: 'RECREO',
      image: require('../res/image/hamaca.png'),
      video: `${uri}/hamaca.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PELOTA',
      search_name_es: 'PELOTA',
      subcategory: 'RECREO',
      image: require('../res/image/pelota.png'),
      video: `${uri}/pelota.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RECREO',
      search_name_es: 'RECREO',
      subcategory: 'RECREO',
      image: require('../res/image/el-recreo.png'),
      video: `${uri}/el-recreo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SALTAR LA SOGA',
      search_name_es: 'SALTAR LA SOGA',
      subcategory: 'RECREO',
      image: require('../res/image/saltar-la-soga.png'),
      video: `${uri}/saltar-la-soga.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TOBOGÁN',
      search_name_es: 'TOBOGAN',
      subcategory: 'RECREO',
      image: require('../res/image/tobogan.png'),
      video: `${uri}/tobogan.mp4`,
      downloaded: false,
    },
  ],
});
