export const sports = uri => ({
  name_es: 'DEPORTES',
  icon: require('../res/icon/deportes.png'),
  hasSubcategories: true,
  videos: [
    {
      name_es: 'ARTES MARCIALES',
      search_name_es: 'ARTES MARCIALES',
      subcategory: 'DEPORTES',
      image: require('../res/image/artes-marciales.png'),
      video: `${uri}/artes-marciales.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ATLETISMO',
      search_name_es: 'ATLETISMO',
      subcategory: 'DEPORTES',
      image: require('../res/image/atletismo.png'),
      video: `${uri}/atletismo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AUTOMOVILISMO',
      search_name_es: 'AUTOMOVILISMO',
      subcategory: 'DEPORTES',
      image: require('../res/image/automovilismo.png'),
      video: `${uri}/automovilismo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BÁSQUET',
      search_name_es: 'BASQUET',
      subcategory: 'DEPORTES',
      image: require('../res/image/basquet.png'),
      video: `${uri}/basquet.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BOWLING',
      search_name_es: 'BOWLING',
      subcategory: 'DEPORTES',
      image: require('../res/image/bowling.png'),
      video: `${uri}/bowling.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BUCEO',
      search_name_es: 'BUCEO',
      subcategory: 'DEPORTES',
      image: require('../res/image/buceo.png'),
      video: `${uri}/buceo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAMPEONATO',
      search_name_es: 'CAMPEONATO',
      subcategory: 'DEPORTES',
      image: require('../res/image/campeonato.png'),
      video: `${uri}/campeonato.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CICLISMO',
      search_name_es: 'CICLISMO',
      subcategory: 'DEPORTES',
      image: require('../res/image/ciclismo.png'),
      video: `${uri}/ciclismo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'DEPORTES',
      search_name_es: 'DEPORTES',
      subcategory: 'DEPORTES',
      image: require('../res/image/deportes.png'),
      video: `${uri}/deportes.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FÚTBOL',
      search_name_es: 'FUTBOL',
      subcategory: 'DEPORTES',
      image: require('../res/image/futbol.png'),
      video: `${uri}/futbol.mp4`,
      downloaded: false,
    },
    {
      name_es: 'GOLF',
      search_name_es: 'GOLF',
      subcategory: 'DEPORTES',
      image: require('../res/image/golf.png'),
      video: `${uri}/golf.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HANDBOL',
      search_name_es: 'HANDBOL',
      subcategory: 'DEPORTES',
      image: require('../res/image/handbol.png'),
      video: `${uri}/handbol.mp4`,
      downloaded: false,
    },
    {
      name_es: 'HOCKEY',
      search_name_es: 'HOCKEY',
      subcategory: 'DEPORTES',
      image: require('../res/image/hockey.png'),
      video: `${uri}/hockey.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NATACIÓN',
      search_name_es: 'NATACION',
      subcategory: 'DEPORTES',
      image: require('../res/image/natacion.png'),
      video: `${uri}/natacion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MARATÓN',
      search_name_es: 'MARATON',
      subcategory: 'DEPORTES',
      image: require('../res/image/maraton.png'),
      video: `${uri}/maraton.mp4`,
      downloaded: false,
    },
    {
      name_es: 'OLIMPIADAS',
      search_name_es: 'OLIMPIADAS',
      subcategory: 'DEPORTES',
      image: require('../res/image/olimpiadas.png'),
      video: `${uri}/olimpiadas.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAPI FÚTBOL',
      search_name_es: 'PAPI FUTBOL',
      subcategory: 'DEPORTES',
      image: require('../res/image/papi-futbol.png'),
      video: `${uri}/papi-futbol.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PARACAIDISMO',
      search_name_es: 'PARACAIDISMO',
      subcategory: 'DEPORTES',
      image: require('../res/image/paracaidismo.png'),
      video: `${uri}/paracaidismo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PATINES',
      search_name_es: 'PATINES',
      subcategory: 'DEPORTES',
      image: require('../res/image/patines.png'),
      video: `${uri}/patines.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RUGBY',
      search_name_es: 'RUGBY',
      subcategory: 'DEPORTES',
      image: require('../res/image/rugby.png'),
      video: `${uri}/rugby.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SURF',
      search_name_es: 'SURF',
      subcategory: 'DEPORTES',
      image: require('../res/image/surf.png'),
      video: `${uri}/surf.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TENIS',
      search_name_es: 'TENIS',
      subcategory: 'DEPORTES',
      image: require('../res/image/tenis.png'),
      video: `${uri}/tenis.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VOLEIBOL',
      search_name_es: 'VOLEIBOL',
      subcategory: 'DEPORTES',
      image: require('../res/image/voleibol.png'),
      video: `${uri}/voleibol.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CORRER',
      search_name_es: 'CORRER',
      subcategory: 'ACCIONES',
      image: require('../res/image/correr.png'),
      video: `${uri}/correr.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NADAR',
      search_name_es: 'NADAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/nadar.png'),
      video: `${uri}/nadar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NAVEGAR',
      search_name_es: 'NAVEGAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/navegar.png'),
      video: `${uri}/navegar.mp4`,
      downloaded: false,
    },
  ],
});
