export const street = uri => ({
  name_es: 'EN LA CALLE',
  icon: require('../res/icon/en-la-calle.png'),
  hasSubcategories: true,
  videos: [
    {
      name_es: 'DINERO',
      search_name_es: 'DINERO',
      subcategory: 'OTROS',
      image: require('../res/image/dinero.png'),
      video: `${uri}/dinero.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PERSONA',
      search_name_es: 'PERSONA',
      subcategory: 'OTROS',
      image: require('../res/image/persona.png'),
      video: `${uri}/persona.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SEMÁFORO',
      search_name_es: 'SEMAFORO',
      subcategory: 'OTROS',
      image: require('../res/image/semaforo.png'),
      video: `${uri}/semaforo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ACOMPAÑAR',
      search_name_es: 'ACOMPAÑAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/acompanar.png'),
      video: `${uri}/acompanar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAMINAR',
      search_name_es: 'CAMINAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/caminar.png'),
      video: `${uri}/caminar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COMPRAR',
      search_name_es: 'COMPRAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/comprar.png'),
      video: `${uri}/comprar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CRUZAR LA CALLE',
      search_name_es: 'CRUZAR LA CALLE',
      subcategory: 'ACCIONES',
      image: require('../res/image/cruzar-la-calle.png'),
      video: `${uri}/cruzar-la-calle.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PAGAR',
      search_name_es: 'PAGAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/pagar.png'),
      video: `${uri}/pagar.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PASEAR',
      search_name_es: 'PASEAR',
      subcategory: 'ACCIONES',
      image: require('../res/image/pasear.png'),
      video: `${uri}/pasear.mp4`,
      downloaded: false,
    },
    {
      name_es: 'VENDER',
      search_name_es: 'VENDER',
      subcategory: 'ACCIONES',
      image: require('../res/image/vender.png'),
      video: `${uri}/vender.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ALMACÉN',
      search_name_es: 'ALMACEN',
      subcategory: 'LUGARES',
      image: require('../res/image/almacen.png'),
      video: `${uri}/almacen.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BANCO',
      search_name_es: 'BANCO',
      subcategory: 'LUGARES',
      image: require('../res/image/banco.png'),
      video: `${uri}/banco.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CINE',
      search_name_es: 'CINE',
      subcategory: 'LUGARES',
      image: require('../res/image/cine.png'),
      video: `${uri}/cine.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CORREO',
      search_name_es: 'CORREO',
      subcategory: 'LUGARES',
      image: require('../res/image/correo.png'),
      video: `${uri}/correo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'ESQUINA',
      search_name_es: 'ESQUINA',
      subcategory: 'LUGARES',
      image: require('../res/image/esquina.png'),
      video: `${uri}/esquina.mp4`,
      downloaded: false,
    },
    {
      name_es: 'FÁBRICA',
      search_name_es: 'FABRICA',
      subcategory: 'LUGARES',
      image: require('../res/image/fabrica.png'),
      video: `${uri}/fabrica.mp4`,
      downloaded: false,
    },
    {
      name_es: 'KIOSCO',
      search_name_es: 'KIOSCO',
      subcategory: 'LUGARES',
      image: require('../res/image/kiosco.png'),
      video: `${uri}/kiosco.mp4`,
      downloaded: false,
    },
    {
      name_es: 'NEGOCIO',
      search_name_es: 'NEGOCIO',
      subcategory: 'LUGARES',
      image: require('../res/image/negocio.png'),
      video: `${uri}/negocio.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PANADERÍA',
      search_name_es: 'PANADERIA',
      subcategory: 'LUGARES',
      image: require('../res/image/panaderia.png'),
      video: `${uri}/panaderia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PLAZA',
      search_name_es: 'PLAZA',
      subcategory: 'LUGARES',
      image: require('../res/image/plaza.png'),
      video: `${uri}/plaza.mp4`,
      downloaded: false,
    },
    {
      name_es: 'PUENTE',
      search_name_es: 'PUENTE',
      subcategory: 'LUGARES',
      image: require('../res/image/puente.png'),
      video: `${uri}/puente.mp4`,
      downloaded: false,
    },
    {
      name_es: 'RESTAURANTE',
      search_name_es: 'RESTAURANTE',
      subcategory: 'LUGARES',
      image: require('../res/image/restaurante.png'),
      video: `${uri}/restaurante.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SUPERMERCADO',
      search_name_es: 'SUPERMERCADO',
      subcategory: 'LUGARES',
      image: require('../res/image/supermercado.png'),
      video: `${uri}/supermercado.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AMBULANCIA',
      search_name_es: 'AMBULANCIA',
      subcategory: 'MEDIOS DE TRANSPORTE',
      image: require('../res/image/ambulancia.png'),
      video: `${uri}/ambulancia.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AUTO',
      search_name_es: 'AUTO',
      subcategory: 'MEDIOS DE TRANSPORTE',
      image: require('../res/image/auto.png'),
      video: `${uri}/auto.mp4`,
      downloaded: false,
    },
    {
      name_es: 'AVIÓN',
      search_name_es: 'AVION',
      subcategory: 'MEDIOS DE TRANSPORTE',
      image: require('../res/image/avion.png'),
      video: `${uri}/avion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'BICICLETA',
      search_name_es: 'BICICLETA',
      subcategory: 'MEDIOS DE TRANSPORTE',
      image: require('../res/image/bicicleta.png'),
      video: `${uri}/bicicleta.mp4`,
      downloaded: false,
    },
    {
      name_es: 'CAMIÓN',
      search_name_es: 'CAMION',
      subcategory: 'MEDIOS DE TRANSPORTE',
      image: require('../res/image/camion.png'),
      video: `${uri}/camion.mp4`,
      downloaded: false,
    },
    {
      name_es: 'COLECTIVO',
      search_name_es: 'COLECTIVO',
      subcategory: 'MEDIOS DE TRANSPORTE',
      image: require('../res/image/colectivo.png'),
      video: `${uri}/colectivo.mp4`,
      downloaded: false,
    },
    {
      name_es: 'MOTO',
      search_name_es: 'MOTO',
      subcategory: 'MEDIOS DE TRANSPORTE',
      image: require('../res/image/moto.png'),
      video: `${uri}/moto.mp4`,
      downloaded: false,
    },
    {
      name_es: 'SUBTE',
      search_name_es: 'SUBTE',
      subcategory: 'MEDIOS DE TRANSPORTE',
      image: require('../res/image/subte.png'),
      video: `${uri}/subte.mp4`,
      downloaded: false,
    },
    {
      name_es: 'TREN',
      search_name_es: 'TREN',
      subcategory: 'MEDIOS DE TRANSPORTE',
      image: require('../res/image/tren.png'),
      video: `${uri}/tren.mp4`,
      downloaded: false,
    },
  ],
});
