const YouTubeUri = 'https://youtu.be';
export default {
  categories: [
    {
      name_es: 'ASOCIACIONES DE SORDOS EN ARGENTINA',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'AAS - ASOCIACIÓN ARGENTINA DE SORDOMUDAS – CASA HOGAR',
          search_name_es: 'AAS - ASOCIACIÓN ARGENTINA DE SORDOMUDAS – CASA HOGAR',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/x_OuMEKCFGg`,
          downloaded: false,
        },
        {
          name_es: 'ASAM - ASOCIACIÓN DE SORDOMUDOS DE AYUDA MUTUA',
          search_name_es: 'ASAM - ASOCIACIÓN DE SORDOMUDOS DE AYUDA MUTUA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/qD4kpfAhR_4`,
          downloaded: false,
        },
        {
          name_es: 'ASO - ASOCIACIÓN ARGENTINA DE SORDOS',
          search_name_es: 'ASO - ASOCIACIÓN ARGENTINA DE SORDOS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/0lTfhv25H_E`,
          downloaded: false,
        },
        {
          name_es: 'ASG ASOCIACIÓN DE SORDOS DE GUALEGUAYCHÚ',
          search_name_es: 'ASG ASOCIACIÓN DE SORDOS DE GUALEGUAYCHÚ',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/UNEevS1fltU`,
          downloaded: false,
        },
        {
          name_es: 'ASLP - ASOCIACIÓN DE SORDOMUDOS LA PLATA',
          search_name_es: 'ASLP - ASOCIACIÓN DE SORDOMUDOS LA PLATA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/tazBXv_moX0`,
          downloaded: false,
        },
        {
          name_es: 'ASCH - ASOCIACIÓN DE SORDOS CHUBUTENSES',
          search_name_es: 'ASCH - ASOCIACIÓN DE SORDOS CHUBUTENSES',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/4Ny4PYIsvyg`,
          downloaded: false,
        },
        {
          name_es: 'ASMAR - ASOCIACIÓN DE SORDOS DE MAR DEL PLATA',
          search_name_es: 'ASMAR - ASOCIACIÓN DE SORDOS DE MAR DEL PLATA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/fd5XfnbeOZs`,
          downloaded: false,
        },
        {
          name_es: 'ASM ASOCIACIÓN DE SORDOS DE MENDOZA',
          search_name_es: 'ASM ASOCIACIÓN DE SORDOS DE MENDOZA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/zxQ0MZ9VNm0`,
          downloaded: false,
        },
        {
          name_es: 'MSM - MOVIMIENTOS SORDOS DE MENDOZA',
          search_name_es: 'MSM - MOVIMIENTOS SORDOS DE MENDOZA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/zDt5Su21m_Y`,
          downloaded: false,
        },
        {
          name_es: 'ASAMR - ASOCIACIÓN DE SORDOMUDOS DE AYUDA MUTUA ROSARIO',
          search_name_es: 'ASAMR - ASOCIACIÓN DE SORDOMUDOS DE AYUDA MUTUA ROSARIO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/LcarQlFDnRc`,
          downloaded: false,
        },
        {
          name_es: 'ASN - ASOCIACIÓN DE SORDOS DE NEUQUÉN',
          search_name_es: 'ASN - ASOCIACIÓN DE SORDOS DE NEUQUÉN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/azOdKZUSxaE`,
          downloaded: false,
        },
        {
          name_es: 'OCS - ORGANIZACIÓN CORDOBESA DE SORDOS',
          search_name_es: 'OCS - ORGANIZACIÓN CORDOBESA DE SORDOS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/MOoTQ2TC7mA`,
          downloaded: false,
        },
        {
          name_es: 'ASPS - ASOCIACIÓN DE SORDOS DE LA PROVINCIA DE SALTa',
          search_name_es: 'ASPS - ASOCIACIÓN DE SORDOS DE LA PROVINCIA DE SALTA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/-TU0P3rIk3c`,
          downloaded: false,
        },
        {
          name_es: 'ASORSAFE - ASOCIACIÓN DE SORDOS DE SANTA FE',
          search_name_es: 'ASORSAFE - ASOCIACIÓN DE SORDOS DE SANTA FE',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/p_GRur-3Khc`,
          downloaded: false,
        },
        {
          name_es: 'ASSJ - ASOCIACIÓN DE SORDOMUDOS DE SAN JUAN',
          search_name_es: 'ASSJ - ASOCIACIÓN DE SORDOMUDOS DE SAN JUAN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/UGD2lfanQSU`,
          downloaded: false,
        },
        {
          name_es: 'ATS - ASOCIACIÓN TUCUMANA DE SORDOS',
          search_name_es: 'ATS - ASOCIACIÓN TUCUMANA DE SORDOS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/A86rK_Tjwbs`,
          downloaded: false,
        },
        {
          name_es: 'CSCDSR - CÍRCULO SOCIAL, CULTURAL Y DEPORTIVO DE SORDOMUDOS DE ROSARIO',
          search_name_es: 'CSCDSR - CÍRCULO SOCIAL, CULTURAL Y DEPORTIVO DE SORDOMUDOS DE ROSARIO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/0k4AcJVbm2E`,
          downloaded: false,
        },
        {
          name_es: 'UAS - UNIÓN ARGENTINA DE SORDOMUDOS',
          search_name_es: 'UAS - UNIÓN ARGENTINA DE SORDOMUDOS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/eaiMy3-TsoE`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'BARRIOS Y ZONAS',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'AGRONOMÍA',
          search_name_es: 'AGRONOMÍA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/u0dskxw59As`,
          downloaded: false,
        },
        {
          name_es: 'ALMAGRO',
          search_name_es: 'ALMAGRO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/GGeaVSMfWQY`,
          downloaded: false,
        },
        {
          name_es: 'AVELLANEDA',
          search_name_es: 'AVELLANEDA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/zmbfW5DLIKk`,
          downloaded: false,
        },
        {
          name_es: 'BANFIELD',
          search_name_es: 'BANFIELD',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/kdriwPzwVqI`,
          downloaded: false,
        },
        {
          name_es: 'BARRACAS',
          search_name_es: 'BARRACAS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/eATXVncdqP0`,
          downloaded: false,
        },
        {
          name_es: 'BARRIO',
          search_name_es: 'BARRIO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/8W3yFSbuMy0`,
          downloaded: false,
        },
        {
          name_es: 'BELGRANO',
          search_name_es: 'BELGRANO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/bNugocCCc7k`,
          downloaded: false,
        },
        {
          name_es: 'BOEDO',
          search_name_es: 'BOEDO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/AwqztbFGFl8`,
          downloaded: false,
        },
        {
          name_es: 'CABA',
          search_name_es: 'CABA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/SfeeSDKwnh8`,
          downloaded: false,
        },
        {
          name_es: 'CABALLITO',
          search_name_es: 'CABALLITO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/O4ayA476BuQ`,
          downloaded: false,
        },
        {
          name_es: 'CHACARITA',
          search_name_es: 'CHACARITA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/8TZSmVeW-Tw`,
          downloaded: false,
        },
        {
          name_es: 'CONSTITUCIÓN',
          search_name_es: 'CONSTITUCIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/z75k8QSvXxA`,
          downloaded: false,
        },
        {
          name_es: 'CONURBANO',
          search_name_es: 'CONURBANO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/2i7acxlnCMc`,
          downloaded: false,
        },
        {
          name_es: 'FLORES',
          search_name_es: 'FLORES',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/2g6nTaK_BXc`,
          downloaded: false,
        },
        {
          name_es: 'ITUZAINGÓ',
          search_name_es: 'ITUZAINGÓ',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/mN9hCULrVdM`,
          downloaded: false,
        },
        {
          name_es: 'LA MATANZA',
          search_name_es: 'LA MATANZA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/YAYPCe76RZw`,
          downloaded: false,
        },
        {
          name_es: 'LAFERRERE',
          search_name_es: 'LAFERRERE',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/pa_mpyE05pw`,
          downloaded: false,
        },
        {
          name_es: 'LANÚS',
          search_name_es: 'LANÚS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/OkWnZULX1mA`,
          downloaded: false,
        },
        {
          name_es: 'LINIERS',
          search_name_es: 'LINIERS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/JmPshUJYVDc`,
          downloaded: false,
        },
        {
          name_es: 'LOMAS DE ZAMORA',
          search_name_es: 'LOMAS DE ZAMORA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/E3vW0-RpPVw`,
          downloaded: false,
        },
        {
          name_es: 'MATADEROS',
          search_name_es: 'MATADEROS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/_QkjhUSXSBg`,
          downloaded: false,
        },
        {
          name_es: 'MERLO',
          search_name_es: 'MERLO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/74PmkL4gDuk`,
          downloaded: false,
        },
        {
          name_es: 'MORENO',
          search_name_es: 'MORENO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/HPGQxi-i7nY`,
          downloaded: false,
        },
        {
          name_es: 'MORÓN',
          search_name_es: 'MORÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/hWOcrwOt8l0`,
          downloaded: false,
        },
        {
          name_es: 'PALERMO',
          search_name_es: 'PALERMO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/9kObQY2HL68`,
          downloaded: false,
        },
        {
          name_es: 'POMPEYA',
          search_name_es: 'POMPEYA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/beUfdAPDjOg`,
          downloaded: false,
        },
        {
          name_es: 'QUILMES',
          search_name_es: 'QUILMES',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/pfchqEF37ZQ`,
          downloaded: false,
        },
        {
          name_es: 'RAMOS MEJÍA',
          search_name_es: 'RAMOS MEJÍA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/CGGOF-0MfKk`,
          downloaded: false,
        },
        {
          name_es: 'RECOLETA',
          search_name_es: 'RECOLETA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/Is907n3mbsk`,
          downloaded: false,
        },
        {
          name_es: 'RETIRO',
          search_name_es: 'RETIRO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/n98Bl8Tanok`,
          downloaded: false,
        },
        {
          name_es: 'SAN ISIDRO',
          search_name_es: 'SAN ISIDRO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/WlKq17aMaDY`,
          downloaded: false,
        },
        {
          name_es: 'SAN JUSTO',
          search_name_es: 'SAN JUSTO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/Bj09CMyCnbo`,
          downloaded: false,
        },
        {
          name_es: 'SAN MARTÍN',
          search_name_es: 'SAN MARTÍN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/_QTWdBfDHBQ`,
          downloaded: false,
        },
        {
          name_es: 'SAN MIGUEL',
          search_name_es: 'SAN MIGUEL',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/wZv3pwepal0`,
          downloaded: false,
        },
        {
          name_es: 'SAN TELMO',
          search_name_es: 'SAN TELMO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/5sx7L1MCNIc`,
          downloaded: false,
        },
        {
          name_es: 'TEMPERLEY',
          search_name_es: 'TEMPERLEY',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/ho9EiDlmkgY`,
          downloaded: false,
        },
        {
          name_es: 'TIGRE',
          search_name_es: 'TIGRE',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/5QrDkzR295Q`,
          downloaded: false,
        },
        {
          name_es: 'VILLA DEL PARQUE',
          search_name_es: 'VILLA DEL PARQUE',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/P4f2D2aQ4Yo`,
          downloaded: false,
        },
        {
          name_es: 'VILLA DEVOTO',
          search_name_es: 'VILLA DEVOTO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/ogOXqXU9DY8`,
          downloaded: false,
        },
        {
          name_es: 'VILLA LUGANO',
          search_name_es: 'VILLA LUGANO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/GvaaIGbuudg`,
          downloaded: false,
        },
        {
          name_es: 'VILLA URQUIZA',
          search_name_es: 'VILLA URQUIZA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/zLeFZlJu86U`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'COMUNIDAD SORDA',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'AFILIACIÓN',
          search_name_es: 'AFILIACIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/T_kRJ2xJnqw`,
          downloaded: false,
        },
        {
          name_es: 'APROBACIÓN',
          search_name_es: 'APROBACIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/OHwWeQJVcRY`,
          downloaded: false,
        },
        {
          name_es: 'ASAMBLEA',
          search_name_es: 'ASAMBLEA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/mVG7x6-u3hI`,
          downloaded: false,
        },
        {
          name_es: 'ASOCIACIÓN',
          search_name_es: 'ASOCIACIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/QdUm9t-ycgc`,
          downloaded: false,
        },
        {
          name_es: 'CAS - CONFEDERACIÓN ARGENTINA DE SORDOS',
          search_name_es: 'CAS - CONFEDERACIÓN ARGENTINA DE SORDOS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/3T0ZsE0H0ZA`,
          downloaded: false,
        },
        {
          name_es: 'COMISIÓN DIRECTIVA',
          search_name_es: 'COMISIÓN DIRECTIVA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/cz3-9y-eEVI`,
          downloaded: false,
        },
        {
          name_es: 'COMUNIDAD SORDA',
          search_name_es: 'COMUNIDAD SORDA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/rrcHwRm8JXk`,
          downloaded: false,
        },
        {
          name_es: 'CUD - CERTIFICADO ÚNICO DE DISCAPACIDAD',
          search_name_es: 'CUD - CERTIFICADO ÚNICO DE DISCAPACIDAD',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/56aw-S4az80`,
          downloaded: false,
        },
        {
          name_es: 'CULTURA',
          search_name_es: 'CULTURA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/oYF--HYfwUs`,
          downloaded: false,
        },
        {
          name_es: 'DESAPROBACIÓN',
          search_name_es: 'DESAPROBACIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/VI53VBj6LkE`,
          downloaded: false,
        },
        {
          name_es: 'FEDERACIÓN',
          search_name_es: 'FEDERACIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/mrZ_6h-xGcA`,
          downloaded: false,
        },
        {
          name_es: 'FUNDACIÓN',
          search_name_es: 'FUNDACIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/xWRX3pDzmLw`,
          downloaded: false,
        },
        {
          name_es: 'FUNDASOR',
          search_name_es: 'FUNDASOR',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/eDaT1aMJOvQ`,
          downloaded: false,
        },
        {
          name_es: 'IDENTIDAD',
          search_name_es: 'IDENTIDAD',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/sVKqnu3hskY`,
          downloaded: false,
        },
        {
          name_es: 'IDIOMA',
          search_name_es: 'IDIOMA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/s2X5s9p9hw8`,
          downloaded: false,
        },
        {
          name_es: 'INSTITUCIÓN',
          search_name_es: 'INSTITUCIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/HiQ3xq3IAmY`,
          downloaded: false,
        },
        {
          name_es: 'LENGUA DE SEÑAS ARGENTINA',
          search_name_es: 'LENGUA DE SEÑAS ARGENTINA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/MksOSK7fK4g`,
          downloaded: false,
        },
        {
          name_es: 'LENGUAJE',
          search_name_es: 'LENGUAJE',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/OhBR4zvRUPs`,
          downloaded: false,
        },
        {
          name_es: 'PENSIÓN',
          search_name_es: 'PENSIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/VEOkgoBQDgE`,
          downloaded: false,
        },
        {
          name_es: 'PERSONERÍA JURÍDICA',
          search_name_es: 'PERSONERÍA JURÍDICA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/hMV0WY2qNX0`,
          downloaded: false,
        },
        {
          name_es: 'PROYECTO',
          search_name_es: 'PROYECTO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/bruvWeTHDCw`,
          downloaded: false,
        },
        {
          name_es: 'SISTEMA DE SEÑAS INTERNACIONAL',
          search_name_es: 'SISTEMA DE SEÑAS INTERNACIONAL',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/3IyZD44uHXI`,
          downloaded: false,
        },
        {
          name_es: 'SOLICITAR',
          search_name_es: 'SOLICITAR',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/n-xXfWnbAls`,
          downloaded: false,
        },
        {
          name_es: 'TRÁMITES',
          search_name_es: 'TRÁMITES',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/63tjX08pCBQ`,
          downloaded: false,
        },
        {
          name_es: 'VOLUNTARIADO',
          search_name_es: 'VOLUNTARIADO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/UNIzpacU5us`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'CONVENCION SOBRE LOS DERECHOS DE LAS PERSONAS CON DISCAPACIDAD',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'ACCESIBILIDAD',
          search_name_es: 'ACCESIBILIDAD',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/https://youtu.be/gfTzMV2oLeA`,
          downloaded: false,
        },
        {
          name_es: 'ADECUACIÓN',
          search_name_es: 'ADECUACIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/https://youtu.be/7x63f7H_gp8`,
          downloaded: false,
        },
        {
          name_es: 'APOYO',
          search_name_es: 'APOYO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/https://youtu.be/--oDoqNEmrQ`,
          downloaded: false,
        },
        {
          name_es: 'ARTÍCULOS',
          search_name_es: 'ARTÍCULOS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/https://youtu.be/VuwwYo1WxfY`,
          downloaded: false,
        },
        {
          name_es: 'AUTONOMÍA',
          search_name_es: 'AUTONOMÍA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/https://youtu.be/SlGF7SsyM7U`,
          downloaded: false,
        },
        {
          name_es: 'BARRERAS',
          search_name_es: 'BARRERAS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/https://youtu.be/UoGJ8lTtuO0`,
          downloaded: false,
        },
        {
          name_es: 'CONGRESO',
          search_name_es: 'CONGRESO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/https://youtu.be/PZTBywDjiUQ`,
          downloaded: false,
        },
        {
          name_es: 'CONVENCIÓN SOBRE LOS DERECHOS DE LAS PERSONAS CON DISCAPACIDAD',
          search_name_es: 'CONVENCIÓN SOBRE LOS DERECHOS DE LAS PERSONAS CON DISCAPACIDAD',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/https://youtu.be/HYmwK9SFUuk`,
          downloaded: false,
        },
        {
          name_es: 'CUMPLIMIENTO',
          search_name_es: 'CUMPLIMIENTO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/https://youtu.be/MGb0auqyJqQ`,
          downloaded: false,
        },
        {
          name_es: 'DEBATE',
          search_name_es: 'DEBATE',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/https://youtu.be/bDZNqt4gk5c`,
          downloaded: false,
        },
        {
          name_es: 'DENUNCIAR',
          search_name_es: 'DENUNCIAR',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/sAx4s6XEj48`,
          downloaded: false,
        },
        {
          name_es: 'DERECHOS',
          search_name_es: 'DERECHOS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/rFWHFXUCpUE`,
          downloaded: false,
        },
        {
          name_es: 'DIPUTADOS',
          search_name_es: 'DIPUTADOS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/LX9zXp7Bj2A`,
          downloaded: false,
        },
        {
          name_es: 'ELECCIONES',
          search_name_es: 'ELECCIONES',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/iFHG4WVj2Wg`,
          downloaded: false,
        },
        {
          name_es: 'ELEGIR',
          search_name_es: 'ELEGIR',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/Sk0UQaHzUxg`,
          downloaded: false,
        },
        {
          name_es: 'EMPODERAMIENTO',
          search_name_es: 'EMPODERAMIENTO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/mLxrnwIDMqc`,
          downloaded: false,
        },
        {
          name_es: 'ENCUESTA',
          search_name_es: 'ENCUESTA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/f2lS9m2aBBs`,
          downloaded: false,
        },
        {
          name_es: 'EQUIDAD',
          search_name_es: 'EQUIDAD',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/I7vxWAdh-Jc`,
          downloaded: false,
        },
        {
          name_es: 'ESTADO',
          search_name_es: 'ESTADO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/CwwmGwlvVXs`,
          downloaded: false,
        },
        {
          name_es: 'GOBIERNO',
          search_name_es: 'GOBIERNO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/nMurd5kVJVs`,
          downloaded: false,
        },
        {
          name_es: 'IGUALDAD',
          search_name_es: 'IGUALDAD',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/uFTUYfAx-lU`,
          downloaded: false,
        },
        {
          name_es: 'INCLUSIÓN',
          search_name_es: 'INCLUSIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/5-g9R6tDQ44`,
          downloaded: false,
        },
        {
          name_es: 'INFORMACIÓN',
          search_name_es: 'INFORMACIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/fUS7VA1rlPI`,
          downloaded: false,
        },
        {
          name_es: 'JUSTICIA',
          search_name_es: 'JUSTICIA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/SaKAKo32r8Q`,
          downloaded: false,
        },
        {
          name_es: 'LEY',
          search_name_es: 'LEY',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/d2sJjgpm38s`,
          downloaded: false,
        },
        {
          name_es: 'LUCHA',
          search_name_es: 'LUCHA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/mtVBdg4ZsGE`,
          downloaded: false,
        },
        {
          name_es: 'MERCOSUR - MERCADO COMÚN DEL SUR',
          search_name_es: 'MERCOSUR - MERCADO COMÚN DEL SUR',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/LpwjEpbaRZk`,
          downloaded: false,
        },
        {
          name_es: 'NECESIDADES',
          search_name_es: 'NECESIDADES',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/-XgXV5PkOFs`,
          downloaded: false,
        },
        {
          name_es: 'NORMAS',
          search_name_es: 'NORMAS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/KJYDFCOqwW8`,
          downloaded: false,
        },
        {
          name_es: 'OBJETIVO',
          search_name_es: 'OBJETIVO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/3apG8t8dlrk`,
          downloaded: false,
        },
        {
          name_es: 'PARTICIPACIÓN',
          search_name_es: 'PARTICIPACIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/CcKV06wVfzM`,
          downloaded: false,
        },
        {
          name_es: 'POLÍTICA',
          search_name_es: 'POLÍTICA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/FqCE15a4Ink`,
          downloaded: false,
        },
        {
          name_es: 'PROTECCIÓN',
          search_name_es: 'PROTECCIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/12TQ8cqdAvk`,
          downloaded: false,
        },
        {
          name_es: 'RECLAMAR',
          search_name_es: 'RECLAMAR',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/W0DwfSL8rwg`,
          downloaded: false,
        },
        {
          name_es: 'RECONOCIMIENTO',
          search_name_es: 'RECONOCIMIENTO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/COgd8FOcK8Q`,
          downloaded: false,
        },
        {
          name_es: 'REGLAMENTACIÓN',
          search_name_es: 'REGLAMENTACIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/04Vumx9rGzY`,
          downloaded: false,
        },
        {
          name_es: 'RESPONSABILIDAD',
          search_name_es: 'RESPONSABILIDAD',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/eUuXYokDqrA`,
          downloaded: false,
        },
        {
          name_es: 'SENADORES',
          search_name_es: 'SENADORES',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/PoXKwDppNMA`,
          downloaded: false,
        },
        {
          name_es: 'SERVICIO',
          search_name_es: 'SERVICIO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/NdJ73261loQ`,
          downloaded: false,
        },
        {
          name_es: 'SOCIEDAD',
          search_name_es: 'SOCIEDAD',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/vT65AVCnm-U`,
          downloaded: false,
        },
        {
          name_es: 'TOMAR CONCIENCIA',
          search_name_es: 'TOMAR CONCIENCIA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/Yygr7xgjcJQ`,
          downloaded: false,
        },
        {
          name_es: 'VISIBILIZAR',
          search_name_es: 'VISIBILIZAR',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/n3_CIoSABR8`,
          downloaded: false,
        },
        {
          name_es: 'VOTAR',
          search_name_es: 'VOTAR',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/Vr7VAFBSUkw`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'DEPORTES',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'ARTES MARCIALES',
          search_name_es: 'ARTES MARCIALES',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/RMHl7SS7vx0`,
          downloaded: false,
        },
        {
          name_es: 'ATLETISMO',
          search_name_es: 'ATLETISMO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/WtAn9kha_8o`,
          downloaded: false,
        },
        {
          name_es: 'AUTOMOVILISMO',
          search_name_es: 'AUTOMOVILISMO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/wvwmiZfeGAs`,
          downloaded: false,
        },
        {
          name_es: 'BASQUET',
          search_name_es: 'BASQUET',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/n8KBwphWmj0`,
          downloaded: false,
        },
        {
          name_es: 'BOWLING',
          search_name_es: 'BOWLING',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/tah7p73h9kI`,
          downloaded: false,
        },
        {
          name_es: 'CAMPEONATO',
          search_name_es: 'CAMPEONATO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/xhe1dVA7tfI`,
          downloaded: false,
        },
        {
          name_es: 'CICLISMO',
          search_name_es: 'CICLISMO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/3ksw99hgWwE`,
          downloaded: false,
        },
        {
          name_es: 'DEPORTES',
          search_name_es: 'DEPORTES',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/nTT1XFMX00M`,
          downloaded: false,
        },
        {
          name_es: 'GOLF',
          search_name_es: 'GOLF',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/bO1ovkIXqBI`,
          downloaded: false,
        },
        {
          name_es: 'HANDBOL',
          search_name_es: 'HANDBOL',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/nGGPMsZgB5E`,
          downloaded: false,
        },
        {
          name_es: 'HOCKEY',
          search_name_es: 'HOCKEY',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/qHNJe8kqeNM`,
          downloaded: false,
        },
        {
          name_es: 'NATACIÓN',
          search_name_es: 'Natación',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/jzccHqJCQLQ`,
          downloaded: false,
        },
        {
          name_es: 'OLIMPIADAS',
          search_name_es: 'Olimpiadas',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/9Su7zTB61wQ`,
          downloaded: false,
        },
        {
          name_es: 'PAPI FÚTBOL',
          search_name_es: 'PAPI FÚTBOL',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/qiYEQ_JfRHM`,
          downloaded: false,
        },
        {
          name_es: 'PATINES',
          search_name_es: 'PATINES',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/Q4K3Tzo6zKo`,
          downloaded: false,
        },
        {
          name_es: 'RUGBY',
          search_name_es: 'RUGBY',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/2XIWV5SdvkE`,
          downloaded: false,
        },
        {
          name_es: 'SURF',
          search_name_es: 'SURF',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/bNGT08JGv-c`,
          downloaded: false,
        },
        {
          name_es: 'TENIS',
          search_name_es: 'TENIS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/8hrEFUDfIEg`,
          downloaded: false,
        },
        {
          name_es: 'VOLEIBOL',
          search_name_es: 'VOLEIBOL',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/vvY4hvA0Os8`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'EDUCACION',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'CAPACITACIÓN',
          search_name_es: 'CAPACITACIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/9Q1O8mvZ0KY`,
          downloaded: false,
        },
        {
          name_es: 'CARRERA',
          search_name_es: 'CARRERA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/0SITRwwW2vc`,
          downloaded: false,
        },
        {
          name_es: 'CURSO',
          search_name_es: 'CURSO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/_7mOA_Yk6jk`,
          downloaded: false,
        },
        {
          name_es: 'EDUCACIÓN',
          search_name_es: 'EDUCACIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/4cKEI3n0qvo`,
          downloaded: false,
        },
        {
          name_es: 'EXAMEN',
          search_name_es: 'EXAMEN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/iAxVttz2KsE`,
          downloaded: false,
        },
        {
          name_es: 'FORMACIÓN',
          search_name_es: 'FORMACIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/ncU2sSvf6io`,
          downloaded: false,
        },
        {
          name_es: 'JORNADA',
          search_name_es: 'JORNADA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/A0r8QPEMDtQ`,
          downloaded: false,
        },
        {
          name_es: 'NOTA',
          search_name_es: 'NOTA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/T0_pzwEoO1A`,
          downloaded: false,
        },
        {
          name_es: 'PLANIFICACIÓN',
          search_name_es: 'Planificación',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/6nLzxdp-nKw`,
          downloaded: false,
        },
        {
          name_es: 'PRIMARIA',
          search_name_es: 'Primaria',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/nSjrrYJFboA`,
          downloaded: false,
        },
        {
          name_es: 'SECUNDARIA',
          search_name_es: 'SECUNDARIA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/MU6UsjXKSzg`,
          downloaded: false,
        },
        {
          name_es: 'TEMA',
          search_name_es: 'TEMA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/oAiVT2ApsyU`,
          downloaded: false,
        },
        {
          name_es: 'TERCIARIA',
          search_name_es: 'Terciaria',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/5rpsQHcHrAg`,
          downloaded: false,
        },
        {
          name_es: 'TRABAJO PRÁCTICO',
          search_name_es: 'TRABAJO PRÁCTICO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/3SiPI5w2YuE`,
          downloaded: false,
        },
        {
          name_es: 'UNIVERSIDAD',
          search_name_es: 'UNIVERSIDAD',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/2CejdW8F0TM`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'EL HOSPITAL',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'Autorización',
          search_name_es: 'Autorización',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/l0e1e-ppIB4`,
          downloaded: false,
        },
        {
          name_es: 'Clínica',
          search_name_es: 'Clínica',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/bt4l7yBIwc8`,
          downloaded: false,
        },
        {
          name_es: 'Embarazo',
          search_name_es: 'Embarazo',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/E70ZEtE_3WY`,
          downloaded: false,
        },
        {
          name_es: 'Enfermedades',
          search_name_es: 'Enfermedades',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/7-uTN05Hn_I`,
          downloaded: false,
        },
        {
          name_es: 'Internación',
          search_name_es: 'Internación',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/tB6Xm-f5zfw`,
          downloaded: false,
        },
        {
          name_es: 'Médico Cirujano',
          search_name_es: 'Médico Cirujano',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/e7HXvnGFclU`,
          downloaded: false,
        },
        {
          name_es: 'Médico Ginecólogo',
          search_name_es: 'Médico Ginecólogo',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/6ciXV0GmW4s`,
          downloaded: false,
        },
        {
          name_es: 'Médico Odontólogo',
          search_name_es: 'Médico Odontólogo',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/gieMKjH4PDI`,
          downloaded: false,
        },
        {
          name_es: 'Médico Oftalmólogo',
          search_name_es: 'Médico Oftalmólogo',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/2L_kXMuQkC8`,
          downloaded: false,
        },
        {
          name_es: 'Médico Trumatólogo',
          search_name_es: 'Médico Trumatólogo',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/844NCGMCkyg`,
          downloaded: false,
        },
        {
          name_es: 'Obra Social',
          search_name_es: 'Obra Social',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/Vp1zcO5Mfp0`,
          downloaded: false,
        },
        {
          name_es: 'Privada',
          search_name_es: 'Privada',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/7-fKexXS88w`,
          downloaded: false,
        },
        {
          name_es: 'Pública',
          search_name_es: 'Pública',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/1ZkkYvw1SHY`,
          downloaded: false,
        },
        {
          name_es: 'Resonancia',
          search_name_es: 'Resonancia',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/-A-pgNEIbS0`,
          downloaded: false,
        },
        {
          name_es: 'Test HIV',
          search_name_es: 'Test HIV',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/ASBfROtzDK8`,
          downloaded: false,
        },
        {
          name_es: 'Tratamiento',
          search_name_es: 'Tratamiento',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/a--B7Igx6FM`,
          downloaded: false,
        },
        {
          name_es: 'Yeso',
          search_name_es: 'Yeso',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/p2CEN-KIIt4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'EDUCACIÓN SEXUAL INTEGRAL',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'ABUSO',
          search_name_es: 'ABUSO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/S4H-Zu-AWLY`,
          downloaded: false,
        },
        {
          name_es: 'ACOSO',
          search_name_es: 'ACOSO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/oIYXnlaz6TI`,
          downloaded: false,
        },
        {
          name_es: 'BISEXUAL',
          search_name_es: 'BISEXUAL',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/70EcBpZ2Rcs`,
          downloaded: false,
        },
        {
          name_es: 'BULLYING',
          search_name_es: 'BULLYING',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/wukJVs29usg`,
          downloaded: false,
        },
        {
          name_es: 'COMUNIDAD LGTBIQ',
          search_name_es: 'COMUNIDAD LGTBIQ',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/Xs3S5oO9MrI`,
          downloaded: false,
        },
        {
          name_es: 'DIVERSIDAD',
          search_name_es: 'DIVERSIDAD',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/wVxNnQL85Qc`,
          downloaded: false,
        },
        {
          name_es: 'EDUCACIÓN SEXUAL INTEGRAL ESI',
          search_name_es: 'EDUCACIÓN SEXUAL INTEGRAL ESI',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/HVeN18unpag`,
          downloaded: false,
        },
        {
          name_es: 'EMPATÍA',
          search_name_es: 'EMPATÍA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/ltuZsCMn03Q`,
          downloaded: false,
        },
        {
          name_es: 'GAY',
          search_name_es: 'GAY',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/Dwf1xksDMY4`,
          downloaded: false,
        },
        {
          name_es: 'GÉNERO',
          search_name_es: 'GÉNERO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/uzFeoe56L1Y`,
          downloaded: false,
        },
        {
          name_es: 'HETEROSEXUAL',
          search_name_es: 'HETEROSEXUAL',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/pbaJMlD6xF8`,
          downloaded: false,
        },
        {
          name_es: 'LESBIANA',
          search_name_es: 'LESBIANA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/Hy3tJODOWMI`,
          downloaded: false,
        },
        {
          name_es: 'NI UNA MENOS',
          search_name_es: 'NI UNA MENOS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/hIHjWgLESJ4`,
          downloaded: false,
        },
        {
          name_es: 'TRANSEXUAL',
          search_name_es: 'TRANSEXUAL',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/QoJB9eCWheI`,
          downloaded: false,
        },
        {
          name_es: 'TRAVESTI',
          search_name_es: 'TRAVESTI',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/FFYLJOO_4Z0`,
          downloaded: false,
        },
        {
          name_es: 'VIOLENCIA',
          search_name_es: 'VIOLENCIA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/w9LCMKEHwhs`,
          downloaded: false,
        },
        {
          name_es: 'VIOLENCIA ECONÓMICA',
          search_name_es: 'VIOLENCIA ECONÓMICA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/o94q4VYJT_k`,
          downloaded: false,
        },
        {
          name_es: 'VIOLENCIA FÍSICA',
          search_name_es: 'VIOLENCIA FÍSICA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/GmawpOPmwjE`,
          downloaded: false,
        },
        {
          name_es: 'VIOLENCIA PSICOLÓGICA',
          search_name_es: 'VIOLENCIA PSICOLÓGICA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/F4N5WY-rDRg`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'FAMILIA',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'BISABUELO',
          search_name_es: 'BISABUELO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/n_7ZC8sJNDA`,
          downloaded: false,
        },
        {
          name_es: 'CUÑADO',
          search_name_es: 'CUÑADO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/bMbt3LGEop4`,
          downloaded: false,
        },
        {
          name_es: 'GEMELOS',
          search_name_es: 'GEMELOS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/n1J-BgOFVfQ`,
          downloaded: false,
        },
        {
          name_es: 'HIJASTRO',
          search_name_es: 'HIJASTRO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/qkyknCaUrYw`,
          downloaded: false,
        },
        {
          name_es: 'MADRASTRA',
          search_name_es: 'MADRASTRA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/nZ7O0_uI1dQ`,
          downloaded: false,
        },
        {
          name_es: 'MADRINA',
          search_name_es: 'MADRINA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/Q1VeLvQqUNM`,
          downloaded: false,
        },
        {
          name_es: 'MELLIZOS',
          search_name_es: 'MELLIZOS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/lp4p9Q4MVts`,
          downloaded: false,
        },
        {
          name_es: 'NOVIO',
          search_name_es: 'NOVIO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/d30ncvaVg70`,
          downloaded: false,
        },
        {
          name_es: 'PADRASTRO',
          search_name_es: 'PADRASTRO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/vBkyFDA56WA`,
          downloaded: false,
        },
        {
          name_es: 'PADRINO',
          search_name_es: 'PADRINO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/mRBLynO7INQ`,
          downloaded: false,
        },
        {
          name_es: 'PAREJA',
          search_name_es: 'PAREJA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/OQ3uwQBph7I`,
          downloaded: false,
        },
        {
          name_es: 'SOBRINO',
          search_name_es: 'SOBRINO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/-0v4B9FpEGA`,
          downloaded: false,
        },
        {
          name_es: 'SUEGRO',
          search_name_es: 'SUEGRO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/gScx9Fo-mRM`,
          downloaded: false,
        },
        {
          name_es: 'VIEJO',
          search_name_es: 'VIEJO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/Se5pKKubI0k`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'NOCIONES DE LA COMUNIDAD SORDA',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'LS 1',
          search_name_es: 'LS 1',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/01cUvV4wCzs`,
          downloaded: false,
        },
        {
          name_es: 'LS 2',
          search_name_es: 'LS 2',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/0FsNha0LVQE`,
          downloaded: false,
        },
        {
          name_es: 'LSA',
          search_name_es: 'LSA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/7QXAyS3Kr9A`,
          downloaded: false,
        },
        {
          name_es: '19/09',
          search_name_es: '19/09',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/ZW-1y5tZcXg`,
          downloaded: false,
        },
        {
          name_es: '23/09',
          search_name_es: '23/09',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/G4PYxGjxD9A`,
          downloaded: false,
        },
        {
          name_es: 'FAMILIAS',
          search_name_es: 'FAMILIAS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/verT0Kxj-uE`,
          downloaded: false,
        },
        {
          name_es: 'Ley 26.378',
          search_name_es: 'Ley 26.378',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/h5erx1Y9vvs`,
          downloaded: false,
        },
        {
          name_es: 'TECNOLOGÍA',
          search_name_es: 'TECNOLOGÍA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/BowW9e-xXyU`,
          downloaded: false,
        },
        {
          name_es: 'DEPORTES',
          search_name_es: 'DEPORTES',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/VxiiAyHRoNU`,
          downloaded: false,
        },
        {
          name_es: 'CUD',
          search_name_es: 'CUD',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/RSqvM5hH6G4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'JUEGOS',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'AJEDREZ',
          search_name_es: 'AJEDREZ',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/yt1k3dh5uaw`,
          downloaded: false,
        },
        {
          name_es: 'CARTAS',
          search_name_es: 'CARTAS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/Z8THpuVSQ1Q`,
          downloaded: false,
        },
        {
          name_es: 'DADOS',
          search_name_es: 'DADOS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/CZ2kjMNsUWk`,
          downloaded: false,
        },
        {
          name_es: 'DAMAS',
          search_name_es: 'DAMAS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/3xHvmVsz86k`,
          downloaded: false,
        },
        {
          name_es: 'DOMINÓ',
          search_name_es: 'DOMINÓ',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/a7QVsNAfJmI`,
          downloaded: false,
        },
        {
          name_es: 'JUEGOS',
          search_name_es: 'JUEGOS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/sMv5Agg8Tdc`,
          downloaded: false,
        },
        {
          name_es: 'PLAYSTATION',
          search_name_es: 'PLAYSTATION',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/HWWGagnjBRU`,
          downloaded: false,
        },
        {
          name_es: 'POOL',
          search_name_es: 'POOL',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/lrLKfGRdOWg`,
          downloaded: false,
        },
        {
          name_es: 'ROMPECABEZAS',
          search_name_es: 'ROMPECABEZAS',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/pik6q8vYNnY`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'MEDIDAS',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'CANTIDAD',
          search_name_es: 'CANTIDAD',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/rIWUeu8332o`,
          downloaded: false,
        },
        {
          name_es: 'KILO',
          search_name_es: 'KILO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/k7OQc88A9FQ`,
          downloaded: false,
        },
        {
          name_es: 'LITRO',
          search_name_es: 'LITRO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/B0OSvUo9Ow0`,
          downloaded: false,
        },
        {
          name_es: 'MILLÓN',
          search_name_es: 'MILLÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/8tcOeOjaIVs`,
          downloaded: false,
        },
        {
          name_es: 'PESO',
          search_name_es: 'PESO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/Grl9PPEgP3w`,
          downloaded: false,
        },
        {
          name_es: 'PORCENTAJE',
          search_name_es: 'PORCENTAJE',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/UcTm5X_m6l8`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'OTROS PAÍSES',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'ÁFRICA',
          search_name_es: 'ÁFRICA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/mKCewZWx3is`,
          downloaded: false,
        },
        {
          name_es: 'AMÉRICA',
          search_name_es: 'AMÉRICA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/np_A_4EyUQQ`,
          downloaded: false,
        },
        {
          name_es: 'AMÉRICA CENTRAL',
          search_name_es: 'AMÉRICA CENTRAL',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/1DediiBRJVo`,
          downloaded: false,
        },
        {
          name_es: 'AMÉRICA DEL NORTE',
          search_name_es: 'AMÉRICA DEL NORTE',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/PYxzTmeDUkc`,
          downloaded: false,
        },
        {
          name_es: 'ASIA',
          search_name_es: 'ASIA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/xm7f8I-zqlY`,
          downloaded: false,
        },
        {
          name_es: 'EUROPA',
          search_name_es: 'EUROPA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/_BRpYFvBf3U`,
          downloaded: false,
        },
        {
          name_es: 'LATINOAMÉRICA',
          search_name_es: 'LATINOAMÉRICA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/eH6Fl6hSjS0`,
          downloaded: false,
        },
        {
          name_es: 'OCEANÍA',
          search_name_es: 'OCEANÍA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/gaCWJloqHLU`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'TECNOLOGÍA',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'ADJUNTAR',
          search_name: 'ADJUNTAR',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/_3ODlLGtB64`,
          downloaded: false,
        },
        {
          name_es: 'BLOG',
          search_name: 'BLOG',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/qG9_R1yborE`,
          downloaded: false,
        },
        {
          name_es: 'DRIVE',
          search_name: 'DRIVE',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/fxkasr8CM8c`,
          downloaded: false,
        },
        {
          name_es: 'EMAIL',
          search_name: 'EMAIL',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/bPHTo4hwiQQ`,
          downloaded: false,
        },
        {
          name_es: 'ESCÁNER',
          search_name: 'ESCÁNER',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/RVU1WyWtKRY`,
          downloaded: false,
        },
        {
          name_es: 'FACEBOOK',
          search_name: 'FACEBOOK',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/sCs3sB37lso`,
          downloaded: false,
        },
        {
          name_es: 'GOOGLE',
          search_name: 'GOOGLE',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/edL9Lt7Xbqs`,
          downloaded: false,
        },
        {
          name_es: 'INSTAGRAM',
          search_name: 'INSTAGRAM',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/cbsVLJTKg5Q`,
          downloaded: false,
        },
        {
          name_es: 'MEMORIA',
          search_name: 'MEMORIA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/wWygIkPyTjY`,
          downloaded: false,
        },
        {
          name_es: 'NETFLIX',
          search_name: 'NETFLIX',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/88_E_h_0hJQ`,
          downloaded: false,
        },
        {
          name_es: 'NOTEBOOK',
          search_name: 'NOTEBOOK',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/UoKk6hIgYs0`,
          downloaded: false,
        },
        {
          name_es: 'PÁGINA WEB',
          search_name: 'PÁGINA WEB',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/BIKmuhZsfJw`,
          downloaded: false,
        },
        {
          name_es: 'PENDRIVE',
          search_name: 'PENDRIVE',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/wf-ZzfcNeYs`,
          downloaded: false,
        },
        {
          name_es: 'PROYECTOR',
          search_name: 'PROYECTOR',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/JFIwXdHhGWI`,
          downloaded: false,
        },
        {
          name_es: 'TABLET',
          search_name: 'TABLET',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/GBacsL5rTSI`,
          downloaded: false,
        },
        {
          name_es: 'TWITTER',
          search_name: 'TWITTER',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/bUS6pacHdk0`,
          downloaded: false,
        },
        {
          name_es: 'VIDEO',
          search_name: 'VIDEO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/oRqb7PSu7W4`,
          downloaded: false,
        },
        {
          name_es: 'VIDEOLLAMADA',
          search_name: 'VIDEOLLAMADA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/RBlX6mvGFAg`,
          downloaded: false,
        },
        {
          name_es: 'WHATSAPP',
          search_name: 'WHATSAPP',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/RT1Ed9dBrO0`,
          downloaded: false,
        },
        {
          name_es: 'WIFI',
          search_name: 'WIFI',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/AYTokD4A2NQ`,
          downloaded: false,
        },
        {
          name_es: 'YOUTUBE',
          search_name: 'YOUTUBE',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/FLL08ypUEko`,
          downloaded: false,
        },
        {
          name_es: 'ZOOM',
          search_name: 'ZOOM',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/PFDz8chkeRo`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'TIEMPO LIBRE',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'ACTIVIDAD',
          search_name_es: 'ACTIVIDAD',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/5p8RUwJVsSg`,
          downloaded: false,
        },
        {
          name_es: 'ALQUILAR',
          search_name_es: 'ALQUILAR',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/BJ9PhptVjYY`,
          downloaded: false,
        },
        {
          name_es: 'CLUB',
          search_name_es: 'CLUB',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/5tx2sus8psA`,
          downloaded: false,
        },
        {
          name_es: 'DESCANSAR',
          search_name_es: 'DESCANSAR',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/u3mwBvtgRhU`,
          downloaded: false,
        },
        {
          name_es: 'GIMNASIA',
          search_name_es: 'GIMNASIA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/LY6_pUgWr-4`,
          downloaded: false,
        },
        {
          name_es: 'MEDITACIÓN',
          search_name_es: 'MEDITACIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/ejfNpqaSy8Y`,
          downloaded: false,
        },
        {
          name_es: 'MUSEO',
          search_name_es: 'MUSEO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/u2ZIeliFM7g`,
          downloaded: false,
        },
        {
          name_es: 'RECREACIÓN',
          search_name_es: 'RECREACIÓN',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/2dew16rp0pQ`,
          downloaded: false,
        },
        {
          name_es: 'TEATRO',
          search_name_es: 'TEATRO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/ss1DYtJ7K1s`,
          downloaded: false,
        },
        {
          name_es: 'TIEMPO LIBRE',
          search_name_es: 'TIEMPO LIBRE',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/txHi-1ZamzE`,
          downloaded: false,
        },
        {
          name_es: 'TYouTubeUriSMO',
          search_name_es: 'TYouTubeUriSMO',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/6GETAkBoskc`,
          downloaded: false,
        },
        {
          name_es: 'VISITA GUIADA',
          search_name_es: 'VISITA GUIADA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/Vfc1KM9Vkzk`,
          downloaded: false,
        },
        {
          name_es: 'YOGA',
          search_name_es: 'YOGA',
          image: require('./res/image/image.png'),
          video: `${YouTubeUri}/6MD7hj6EpGE`,
          downloaded: false,
        },
      ],
    },
  ],
};
