const uri = 'https://dane-videos.s3.us-east-2.amazonaws.com';
export default {
  categories: [
    {
      name_es: 'ASOCIACIONES DE SORDOS EN ARGENTINA',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'AAS - Asociación Argentina de Sordomudas – Casa Hogar',
          search_name_es: 'AAS - Asociación Argentina de Sordomudas – Casa Hogar',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ASAM - Asociación de Sordomudos de Ayuda Mutua',
          search_name_es: 'ASAM - Asociación de Sordomudos de Ayuda Mutua',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ASO - Asociación Argentina de Sordos',
          search_name_es: 'ASO - Asociación Argentina de Sordos',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ASG Asociación de Sordos de Gualeguaychú',
          search_name_es: 'ASG Asociación de Sordos de Gualeguaychú',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ASLP - Asociación de Sordomudos La Plata',
          search_name_es: 'ASLP - Asociación de Sordomudos La Plata',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ASCH - Asociación de Sordos Chubutenses',
          search_name_es: 'ASCH - Asociación de Sordos Chubutenses',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ASMAR - Asociación de Sordos de Mar del Plata',
          search_name_es: 'ASMAR - Asociación de Sordos de Mar del Plata',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ASM Asociación de Sordos de Mendoza',
          search_name_es: 'ASM Asociación de Sordos de Mendoza',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MSM - Movimientos Sordos de Mendoza',
          search_name_es: 'MSM - Movimientos Sordos de Mendoza',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ASAMR - Asociación de Sordomudos de Ayuda Mutua Rosario',
          search_name_es: 'ASAMR - Asociación de Sordomudos de Ayuda Mutua Rosario',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ASN - Asociación de Sordos de Neuquén',
          search_name_es: 'ASN - Asociación de Sordos de Neuquén',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'OCS - Organización Cordobesa de Sordos',
          search_name_es: 'OCS - Organización Cordobesa de Sordos',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ASPS - Asociación de Sordos de la Provincia de Salta',
          search_name_es: 'ASPS - Asociación de Sordos de la Provincia de Salta',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ASORSAFE - Asociación de Sordos de Santa Fe',
          search_name_es: 'ASORSAFE - Asociación de Sordos de Santa Fe',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ASSJ - Asociación de Sordomudos de San Juan',
          search_name_es: 'ASSJ - Asociación de Sordomudos de San Juan',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ATS - Asociación Tucumana de Sordos',
          search_name_es: 'ATS - Asociación Tucumana de Sordos',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'CSCDSR - Círculo Social, Cultural y Deportivo de Sordomudos de Rosario',
          search_name_es: 'CSCDSR - Círculo Social, Cultural y Deportivo de Sordomudos de Rosario',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'UAS - Unión Argentina de Sordomudos',
          search_name_es: 'UAS - Unión Argentina de Sordomudos',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'BARRIOS Y ZONAS',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'Agronomía',
          search_name_es: 'Agronomía',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Almagro',
          search_name_es: 'Almagro',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Avellaneda',
          search_name_es: 'Avellaneda',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Banfield',
          search_name_es: 'Banfield',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Barracas',
          search_name_es: 'Barracas',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Barrio',
          search_name_es: 'Barrio',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Belgrano',
          search_name_es: 'Belgrano',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Boedo',
          search_name_es: 'Boedo',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'CABA',
          search_name_es: 'CABA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Caballito',
          search_name_es: 'Caballito',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Chacarita',
          search_name_es: 'Chacarita',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Constitución',
          search_name_es: 'Constitución',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Conurbano',
          search_name_es: 'Conurbano',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Flores',
          search_name_es: 'Flores',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Ituzaingó',
          search_name_es: 'Ituzaingó',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'La Matanza',
          search_name_es: 'La Matanza',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Laferrere',
          search_name_es: 'Laferrere',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Lanús',
          search_name_es: 'Lanús',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Liniers',
          search_name_es: 'Liniers',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Lomas de Zamora',
          search_name_es: 'Lomas de Zamora',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Mataderos',
          search_name_es: 'Mataderos',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Merlo',
          search_name_es: 'Merlo',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Moreno',
          search_name_es: 'Moreno',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Morón',
          search_name_es: 'Morón',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Palermo',
          search_name_es: 'Palermo',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Pompeya',
          search_name_es: 'Pompeya',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Quilmes',
          search_name_es: 'Quilmes',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Ramos Mejía',
          search_name_es: 'Ramos Mejía',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Recoleta',
          search_name_es: 'Recoleta',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Retiro',
          search_name_es: 'Retiro',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'San Isidro',
          search_name_es: 'San Isidro',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'San Justo',
          search_name_es: 'San Justo',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'San Martín',
          search_name_es: 'San Martín',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'San Miguel',
          search_name_es: 'San Miguel',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'San Telmo',
          search_name_es: 'San Telmo',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Temperley',
          search_name_es: 'Temperley',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Tigre',
          search_name_es: 'Tigre',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Villa del Parque',
          search_name_es: 'Villa del Parque',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Villa Devoto',
          search_name_es: 'Villa Devoto',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Villa Lugano',
          search_name_es: 'Villa Lugano',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Villa Urquiza',
          search_name_es: 'Villa Urquiza',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'COMUNIDAD SORDA',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'Afiliación',
          search_name_es: 'Afiliación',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Aprobación',
          search_name_es: 'Aprobación',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Asamblea',
          search_name_es: 'Asamblea',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Asociación',
          search_name_es: 'Asociación',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'CAS - Confederación Argentina de Sordos',
          search_name_es: 'CAS - Confederación Argentina de Sordos',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Comisión Directiva',
          search_name_es: 'Comisión Directiva',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Comunidad Sorda',
          search_name_es: 'Comunidad Sorda',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'CUD - Certificado Único de Discapacidad',
          search_name_es: 'CUD - Certificado Único de Discapacidad',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Cultura',
          search_name_es: 'Cultura',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Desaprobación',
          search_name_es: 'Desaprobación',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Federación',
          search_name_es: 'Federación',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Fundación',
          search_name_es: 'Fundación',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'FUNDASOR',
          search_name_es: 'FUNDASOR',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Identidad',
          search_name_es: 'Identidad',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Idioma',
          search_name_es: 'Idioma',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Institución',
          search_name_es: 'Institución',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Lengua de Señas Argentina',
          search_name_es: 'Lengua de Señas Argentina',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Lenguaje',
          search_name_es: 'Lenguaje',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Pensión',
          search_name_es: 'Pensión',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Personería Jurídica',
          search_name_es: 'Personería Jurídica',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Proyecto',
          search_name_es: 'Proyecto',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Sistema de Señas Internacional',
          search_name_es: 'Sistema de Señas Internacional',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Solicitar',
          search_name_es: 'Solicitar',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Trámites',
          search_name_es: 'Trámites',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Voluntariado',
          search_name_es: 'Voluntariado',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'CONVENCION SOBRE LOS DERECHOS DE LAS PERSONAS CON DISCAPACIDAD',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'Accesibilidad',
          search_name_es: 'Accesibilidad',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Adecuación',
          search_name_es: 'Adecuación',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Apoyo',
          search_name_es: 'Apoyo',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Artículos',
          search_name_es: 'Artículos',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Autonomía',
          search_name_es: 'Autonomía',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Barreras',
          search_name_es: 'Barreras',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Congreso',
          search_name_es: 'Congreso',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Convención sobre los Derechos de las Personas con Discapacidad',
          search_name_es: 'Convención sobre los Derechos de las Personas con Discapacidad',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Cumplimiento',
          search_name_es: 'Cumplimiento',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Debate',
          search_name_es: 'Debate',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Denunciar',
          search_name_es: 'Denunciar',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Derechos',
          search_name_es: 'Derechos',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Diputados',
          search_name_es: 'Diputados',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Elecciones',
          search_name_es: 'Elecciones',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Elegir',
          search_name_es: 'Elegir',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Empoderamiento',
          search_name_es: 'Empoderamiento',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Encuesta',
          search_name_es: 'Encuesta',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Equidad',
          search_name_es: 'Equidad',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Estado',
          search_name_es: 'Estado',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Gobierno',
          search_name_es: 'Gobierno',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Igualdad',
          search_name_es: 'Igualdad',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Inclusión',
          search_name_es: 'Inclusión',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Información',
          search_name_es: 'Información',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Justicia',
          search_name_es: 'Justicia',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Ley',
          search_name_es: 'Ley',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Lucha',
          search_name_es: 'Lucha',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MERCOSUR - Mercado Común del Sur',
          search_name_es: 'MERCOSUR - Mercado Común del Sur',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Necesidades',
          search_name_es: 'Necesidades',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Normas',
          search_name_es: 'Normas',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Objetivo',
          search_name_es: 'Objetivo',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Participación',
          search_name_es: 'Participación',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Política',
          search_name_es: 'Política',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Protección',
          search_name_es: 'Protección',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Reclamar',
          search_name_es: 'Reclamar',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Reconocimiento',
          search_name_es: 'Reconocimiento',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Reglamentación',
          search_name_es: 'Reglamentación',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Responsabilidad',
          search_name_es: 'Responsabilidad',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Senadores',
          search_name_es: 'Senadores',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Servicio',
          search_name_es: 'Servicio',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Sociedad',
          search_name_es: 'Sociedad',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Tomar Conciencia',
          search_name_es: 'Tomar Conciencia',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Visibilizar',
          search_name_es: 'Visibilizar',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Votar',
          search_name_es: 'Votar',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'DEPORTES',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'Artes Marciales',
          search_name_es: 'Artes Marciales',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Atletismo',
          search_name_es: 'Atletismo',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Automovilismo',
          search_name_es: 'Automovilismo',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Basquet',
          search_name_es: 'Basquet',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Bowling',
          search_name_es: 'Bowling',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Campeonato',
          search_name_es: 'Campeonato',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Ciclismo',
          search_name_es: 'Ciclismo',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Deportes',
          search_name_es: 'Deportes',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Golf',
          search_name_es: 'Golf',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'HandBol',
          search_name_es: 'HandBol',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Hockey',
          search_name_es: 'Hockey',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Natación',
          search_name_es: 'Natación',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Olimpiadas',
          search_name_es: 'Olimpiadas',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Papi Fútbol',
          search_name_es: 'Papi Fútbol',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Patines',
          search_name_es: 'Patines',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Rugby',
          search_name_es: 'Rugby',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Surf',
          search_name_es: 'Surf',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Tenis',
          search_name_es: 'Tenis',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Voleibol',
          search_name_es: 'Voleibol',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'EDUCACION',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'Capacitación',
          search_name_es: 'Capacitación',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Carrera',
          search_name_es: 'Carrera',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Curso',
          search_name_es: 'Curso',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Educación',
          search_name_es: 'Educación',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Examen',
          search_name_es: 'Examen',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Formación',
          search_name_es: 'Formación',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Jornada',
          search_name_es: 'Jornada',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Nota',
          search_name_es: 'Nota',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Planificación',
          search_name_es: 'Planificación',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Primaria',
          search_name_es: 'Primaria',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Secundaria',
          search_name_es: 'Secundaria',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Tema',
          search_name_es: 'Tema',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Terciaria',
          search_name_es: 'Terciaria',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Trabajo Práctico',
          search_name_es: 'Trabajo Práctico',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Universidad',
          search_name_es: 'Universidad',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'EL HOSPITAL',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'Autorización',
          search_name_es: 'Autorización',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Clínica',
          search_name_es: 'Clínica',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Embarazo',
          search_name_es: 'Embarazo',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Enfermedades',
          search_name_es: 'Enfermedades',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Internación',
          search_name_es: 'Internación',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Médico Cirujano',
          search_name_es: 'Médico Cirujano',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Médico Ginecólogo',
          search_name_es: 'Médico Ginecólogo',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Médico Odontólogo',
          search_name_es: 'Médico Odontólogo',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Médico Oftalmólogo',
          search_name_es: 'Médico Oftalmólogo',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Médico Trumatólogo',
          search_name_es: 'Médico Trumatólogo',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Obra Social',
          search_name_es: 'Obra Social',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Privada',
          search_name_es: 'Privada',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Pública',
          search_name_es: 'Pública',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Resonancia',
          search_name_es: 'Resonancia',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Test HIV',
          search_name_es: 'Test HIV',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Tratamiento',
          search_name_es: 'Tratamiento',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Yeso',
          search_name_es: 'Yeso',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'EDUCACIÓN SEXUAL INTEGRAL',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'ABUSO',
          search_name_es: 'ABUSO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ACOSO',
          search_name_es: 'ACOSO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'BISEXUAL',
          search_name_es: 'BISEXUAL',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'BULLYING',
          search_name_es: 'BULLYING',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'COMUNIDAD LGTBIQ',
          search_name_es: 'COMUNIDAD LGTBIQ',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'DIVERSIDAD',
          search_name_es: 'DIVERSIDAD',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'EDUCACIÓN SEXUAL INTEGRAL ESI',
          search_name_es: 'EDUCACIÓN SEXUAL INTEGRAL ESI',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'EMPATÍA',
          search_name_es: 'EMPATÍA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'GAY',
          search_name_es: 'GAY',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'GÉNERO',
          search_name_es: 'GÉNERO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'HETEROSEXUAL',
          search_name_es: 'HETEROSEXUAL',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'LESBIANA',
          search_name_es: 'LESBIANA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'NI UNA MENOS',
          search_name_es: 'NI UNA MENOS',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'TRANSEXUAL',
          search_name_es: 'TRANSEXUAL',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'TRAVESTI',
          search_name_es: 'TRAVESTI',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'VIOLENCIA',
          search_name_es: 'VIOLENCIA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'VIOLENCIA ECONÓMICA',
          search_name_es: 'VIOLENCIA ECONÓMICA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'VIOLENCIA FÍSICA',
          search_name_es: 'VIOLENCIA FÍSICA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'VIOLENCIA PSICOLÓGICA',
          search_name_es: 'VIOLENCIA PSICOLÓGICA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'FAMILIA',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'BISABUELO',
          search_name_es: 'BISABUELO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'CUÑADO',
          search_name_es: 'CUÑADO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'GEMELOS',
          search_name_es: 'GEMELOS',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'HIJASTRO',
          search_name_es: 'HIJASTRO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MADRASTRA',
          search_name_es: 'MADRASTRA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MADRINA',
          search_name_es: 'MADRINA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MELLIZOS',
          search_name_es: 'MELLIZOS',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'NOVIO',
          search_name_es: 'NOVIO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'PADRASTRO',
          search_name_es: 'PADRASTRO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'PADRINO',
          search_name_es: 'PADRINO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'PAREJA',
          search_name_es: 'PAREJA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'SOBRINO',
          search_name_es: 'SOBRINO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'SUEGRO',
          search_name_es: 'SUEGRO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'VIEJO',
          search_name_es: 'VIEJO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'NOCIONES DE LA COMUNIDAD SORDA',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'LS 1',
          search_name_es: 'LS 1',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'LS 2',
          search_name_es: 'LS 2',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'LSA',
          search_name_es: 'LSA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: '19/09',
          search_name_es: '19/09',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: '23/09',
          search_name_es: '23/09',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'FAMILIAS',
          search_name_es: 'FAMILIAS',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'Ley 26.378',
          search_name_es: 'Ley 26.378',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'TECNOLOGÍA',
          search_name_es: 'TECNOLOGÍA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'DEPORTES',
          search_name_es: 'DEPORTES',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'CUD',
          search_name_es: 'CUD',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'JUEGOS',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'AJEDREZ',
          search_name_es: 'AJEDREZ',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'CARTAS',
          search_name_es: 'CARTAS',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'DADOS',
          search_name_es: 'DADOS',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'DAMAS',
          search_name_es: 'DAMAS',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'DOMINÓ',
          search_name_es: 'DOMINÓ',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'JUEGOS',
          search_name_es: 'JUEGOS',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'PLAYSTATION',
          search_name_es: 'PLAYSTATION',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'POOL',
          search_name_es: 'POOL',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ROMPECABEZAS',
          search_name_es: 'ROMPECABEZAS',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'MEDIDAS',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'CANTIDAD',
          search_name_es: 'CANTIDAD',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'KILO',
          search_name_es: 'KILO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'LITRO',
          search_name_es: 'LITRO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MILLÓN',
          search_name_es: 'MILLÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'PESO',
          search_name_es: 'PESO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'PORCENTAJE',
          search_name_es: 'PORCENTAJE',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'OTROS PAÍSES',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'ÁFRICA',
          search_name_es: 'ÁFRICA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'AMÉRICA',
          search_name_es: 'AMÉRICA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'AMÉRICA CENTRAL',
          search_name_es: 'AMÉRICA CENTRAL',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'AMÉRICA DEL NORTE',
          search_name_es: 'AMÉRICA DEL NORTE',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ASIA',
          search_name_es: 'ASIA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'EUROPA',
          search_name_es: 'EUROPA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'LATINOAMÉRICA',
          search_name_es: 'LATINOAMÉRICA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'OCEANÍA',
          search_name_es: 'OCEANÍA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'TECNOLOGÍA',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'ADJUNTAR',
          search_name: 'ADJUNTAR',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'BLOG',
          search_name: 'BLOG',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'DRIVE',
          search_name: 'DRIVE',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'EMAIL',
          search_name: 'EMAIL',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ESCÁNER',
          search_name: 'ESCÁNER',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'FACEBOOK',
          search_name: 'FACEBOOK',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'GOOGLE',
          search_name: 'GOOGLE',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'INSTAGRAM',
          search_name: 'INSTAGRAM',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MEMORIA',
          search_name: 'MEMORIA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'NETFLIX',
          search_name: 'NETFLIX',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'NOTEBOOK',
          search_name: 'NOTEBOOK',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'PÁGINA WEB',
          search_name: 'PÁGINA WEB',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'PENDRIVE',
          search_name: 'PENDRIVE',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'PROYECTOR',
          search_name: 'PROYECTOR',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'TABLET',
          search_name: 'TABLET',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'TWITTER',
          search_name: 'TWITTER',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'VIDEO',
          search_name: 'VIDEO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'VIDEOLLAMADA',
          search_name: 'VIDEOLLAMADA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'WHATSAPP',
          search_name: 'WHATSAPP',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'WIFI',
          search_name: 'WIFI',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'YOUTUBE',
          search_name: 'YOUTUBE',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ZOOM',
          search_name: 'ZOOM',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'TIEMPO LIBRE',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'ACTIVIDAD',
          search_name_es: 'ACTIVIDAD',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'ALQUILAR',
          search_name_es: 'ALQUILAR',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'CLUB',
          search_name_es: 'CLUB',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'DESCANSAR',
          search_name_es: 'DESCANSAR',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'GIMNASIA',
          search_name_es: 'GIMNASIA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MEDITACIÓN',
          search_name_es: 'MEDITACIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'MUSEO',
          search_name_es: 'MUSEO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'RECREACIÓN',
          search_name_es: 'RECREACIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'TEATRO',
          search_name_es: 'TEATRO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'TIEMPO LIBRE',
          search_name_es: 'TIEMPO LIBRE',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'TURISMO',
          search_name_es: 'TURISMO',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'VISITA GUIADA',
          search_name_es: 'VISITA GUIADA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
        {
          name_es: 'YOGA',
          search_name_es: 'YOGA',
          image: require('./res/image/image.png'),
          video: `${uri}/video.mp4`,
          downloaded: false,
        },
      ],
    },
  ],
};
