const uri = 'https://dane-videos.s3.us-east-2.amazonaws.com';
export default {
  categories: [
    {
      name_es: 'ASOCIACIONES DE SORDOS EN ARGENTINA',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'AAS - ASOCIACIÓN ARGENTINA DE SORDOMUDAS – CASA HOGAR',
          search_name_es: 'AAS - ASOCIACIÓN ARGENTINA DE SORDOMUDAS – CASA HOGAR',
          image: require('./res/image/image.png'),
          video: `${uri}/x_OuMEKCFGg`,
          downloaded: false,
        },
        {
          name_es: 'ASAM - ASOCIACIÓN DE SORDOMUDOS DE AYUDA MUTUA',
          search_name_es: 'ASAM - ASOCIACIÓN DE SORDOMUDOS DE AYUDA MUTUA',
          image: require('./res/image/image.png'),
          video: `${uri}/qD4kpfAhR_4`,
          downloaded: false,
        },
        {
          name_es: 'ASO - ASOCIACIÓN ARGENTINA DE SORDOS',
          search_name_es: 'ASO - ASOCIACIÓN ARGENTINA DE SORDOS',
          image: require('./res/image/image.png'),
          video: `${uri}/0lTfhv25H_E`,
          downloaded: false,
        },
        {
          name_es: 'ASG ASOCIACIÓN DE SORDOS DE GUALEGUAYCHÚ',
          search_name_es: 'ASG ASOCIACIÓN DE SORDOS DE GUALEGUAYCHÚ',
          image: require('./res/image/image.png'),
          video: `${uri}/UNEevS1fltU`,
          downloaded: false,
        },
        {
          name_es: 'ASLP - ASOCIACIÓN DE SORDOMUDOS LA PLATA',
          search_name_es: 'ASLP - ASOCIACIÓN DE SORDOMUDOS LA PLATA',
          image: require('./res/image/image.png'),
          video: `${uri}/tazBXv_moX0`,
          downloaded: false,
        },
        {
          name_es: 'ASCH - ASOCIACIÓN DE SORDOS CHUBUTENSES',
          search_name_es: 'ASCH - ASOCIACIÓN DE SORDOS CHUBUTENSES',
          image: require('./res/image/image.png'),
          video: `${uri}/4Ny4PYIsvyg`,
          downloaded: false,
        },
        {
          name_es: 'ASMAR - ASOCIACIÓN DE SORDOS DE MAR DEL PLATA',
          search_name_es: 'ASMAR - ASOCIACIÓN DE SORDOS DE MAR DEL PLATA',
          image: require('./res/image/image.png'),
          video: `${uri}/fd5XfnbeOZs`,
          downloaded: false,
        },
        {
          name_es: 'ASM ASOCIACIÓN DE SORDOS DE MENDOZA',
          search_name_es: 'ASM ASOCIACIÓN DE SORDOS DE MENDOZA',
          image: require('./res/image/image.png'),
          video: `${uri}/zxQ0MZ9VNm0`,
          downloaded: false,
        },
        {
          name_es: 'MSM - MOVIMIENTOS SORDOS DE MENDOZA',
          search_name_es: 'MSM - MOVIMIENTOS SORDOS DE MENDOZA',
          image: require('./res/image/image.png'),
          video: `${uri}/zDt5Su21m_Y`,
          downloaded: false,
        },
        {
          name_es: 'ASAMR - ASOCIACIÓN DE SORDOMUDOS DE AYUDA MUTUA ROSARIO',
          search_name_es: 'ASAMR - ASOCIACIÓN DE SORDOMUDOS DE AYUDA MUTUA ROSARIO',
          image: require('./res/image/image.png'),
          video: `${uri}/LcarQlFDnRc`,
          downloaded: false,
        },
        {
          name_es: 'ASN - ASOCIACIÓN DE SORDOS DE NEUQUÉN',
          search_name_es: 'ASN - ASOCIACIÓN DE SORDOS DE NEUQUÉN',
          image: require('./res/image/image.png'),
          video: `${uri}/azOdKZUSxaE`,
          downloaded: false,
        },
        {
          name_es: 'OCS - ORGANIZACIÓN CORDOBESA DE SORDOS',
          search_name_es: 'OCS - ORGANIZACIÓN CORDOBESA DE SORDOS',
          image: require('./res/image/image.png'),
          video: `${uri}/MOoTQ2TC7mA`,
          downloaded: false,
        },
        {
          name_es: 'ASPS - ASOCIACIÓN DE SORDOS DE LA PROVINCIA DE SALTa',
          search_name_es: 'ASPS - ASOCIACIÓN DE SORDOS DE LA PROVINCIA DE SALTA',
          image: require('./res/image/image.png'),
          video: `${uri}/-TU0P3rIk3c`,
          downloaded: false,
        },
        {
          name_es: 'ASORSAFE - ASOCIACIÓN DE SORDOS DE SANTA FE',
          search_name_es: 'ASORSAFE - ASOCIACIÓN DE SORDOS DE SANTA FE',
          image: require('./res/image/image.png'),
          video: `${uri}/p_GRur-3Khc`,
          downloaded: false,
        },
        {
          name_es: 'ASSJ - ASOCIACIÓN DE SORDOMUDOS DE SAN JUAN',
          search_name_es: 'ASSJ - ASOCIACIÓN DE SORDOMUDOS DE SAN JUAN',
          image: require('./res/image/image.png'),
          video: `${uri}/UGD2lfanQSU`,
          downloaded: false,
        },
        {
          name_es: 'ATS - ASOCIACIÓN TUCUMANA DE SORDOS',
          search_name_es: 'ATS - ASOCIACIÓN TUCUMANA DE SORDOS',
          image: require('./res/image/image.png'),
          video: `${uri}/A86rK_Tjwbs`,
          downloaded: false,
        },
        {
          name_es: 'CSCDSR - CÍRCULO SOCIAL, CULTURAL Y DEPORTIVO DE SORDOMUDOS DE ROSARIO',
          search_name_es: 'CSCDSR - CÍRCULO SOCIAL, CULTURAL Y DEPORTIVO DE SORDOMUDOS DE ROSARIO',
          image: require('./res/image/image.png'),
          video: `${uri}/0k4AcJVbm2E`,
          downloaded: false,
        },
        {
          name_es: 'UAS - UNIÓN ARGENTINA DE SORDOMUDOS',
          search_name_es: 'UAS - UNIÓN ARGENTINA DE SORDOMUDOS',
          image: require('./res/image/image.png'),
          video: `${uri}/eaiMy3-TsoE`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'BARRIOS Y ZONAS',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'AGRONOMÍA',
          search_name_es: 'AGRONOMÍA',
          image: require('./res/image/image.png'),
          video: `${uri}/u0dskxw59As`,
          downloaded: false,
        },
        {
          name_es: 'ALMAGRO',
          search_name_es: 'ALMAGRO',
          image: require('./res/image/image.png'),
          video: `${uri}/GGeaVSMfWQY`,
          downloaded: false,
        },
        {
          name_es: 'AVELLANEDA',
          search_name_es: 'AVELLANEDA',
          image: require('./res/image/image.png'),
          video: `${uri}/zmbfW5DLIKk`,
          downloaded: false,
        },
        {
          name_es: 'BANFIELD',
          search_name_es: 'BANFIELD',
          image: require('./res/image/image.png'),
          video: `${uri}/kdriwPzwVqI`,
          downloaded: false,
        },
        {
          name_es: 'BARRACAS',
          search_name_es: 'BARRACAS',
          image: require('./res/image/image.png'),
          video: `${uri}/eATXVncdqP0`,
          downloaded: false,
        },
        {
          name_es: 'BARRIO',
          search_name_es: 'BARRIO',
          image: require('./res/image/image.png'),
          video: `${uri}/8W3yFSbuMy0`,
          downloaded: false,
        },
        {
          name_es: 'BELGRANO',
          search_name_es: 'BELGRANO',
          image: require('./res/image/image.png'),
          video: `${uri}/bNugocCCc7k`,
          downloaded: false,
        },
        {
          name_es: 'BOEDO',
          search_name_es: 'BOEDO',
          image: require('./res/image/image.png'),
          video: `${uri}/AwqztbFGFl8`,
          downloaded: false,
        },
        {
          name_es: 'CABA',
          search_name_es: 'CABA',
          image: require('./res/image/image.png'),
          video: `${uri}/SfeeSDKwnh8`,
          downloaded: false,
        },
        {
          name_es: 'CABALLITO',
          search_name_es: 'CABALLITO',
          image: require('./res/image/image.png'),
          video: `${uri}/O4ayA476BuQ`,
          downloaded: false,
        },
        {
          name_es: 'CHACARITA',
          search_name_es: 'CHACARITA',
          image: require('./res/image/image.png'),
          video: `${uri}/8TZSmVeW-Tw`,
          downloaded: false,
        },
        {
          name_es: 'CONSTITUCIÓN',
          search_name_es: 'CONSTITUCIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/z75k8QSvXxA`,
          downloaded: false,
        },
        {
          name_es: 'CONURBANO',
          search_name_es: 'CONURBANO',
          image: require('./res/image/image.png'),
          video: `${uri}/2i7acxlnCMc`,
          downloaded: false,
        },
        {
          name_es: 'FLORES',
          search_name_es: 'FLORES',
          image: require('./res/image/image.png'),
          video: `${uri}/2g6nTaK_BXc`,
          downloaded: false,
        },
        {
          name_es: 'ITUZAINGÓ',
          search_name_es: 'ITUZAINGÓ',
          image: require('./res/image/image.png'),
          video: `${uri}/mN9hCULrVdM`,
          downloaded: false,
        },
        {
          name_es: 'LA MATANZA',
          search_name_es: 'LA MATANZA',
          image: require('./res/image/image.png'),
          video: `${uri}/YAYPCe76RZw`,
          downloaded: false,
        },
        {
          name_es: 'LAFERRERE',
          search_name_es: 'LAFERRERE',
          image: require('./res/image/image.png'),
          video: `${uri}/pa_mpyE05pw`,
          downloaded: false,
        },
        {
          name_es: 'LANÚS',
          search_name_es: 'LANÚS',
          image: require('./res/image/image.png'),
          video: `${uri}/OkWnZULX1mA`,
          downloaded: false,
        },
        {
          name_es: 'LINIERS',
          search_name_es: 'LINIERS',
          image: require('./res/image/image.png'),
          video: `${uri}/JmPshUJYVDc`,
          downloaded: false,
        },
        {
          name_es: 'LOMAS DE ZAMORA',
          search_name_es: 'LOMAS DE ZAMORA',
          image: require('./res/image/image.png'),
          video: `${uri}/E3vW0-RpPVw`,
          downloaded: false,
        },
        {
          name_es: 'MATADEROS',
          search_name_es: 'MATADEROS',
          image: require('./res/image/image.png'),
          video: `${uri}/_QkjhUSXSBg`,
          downloaded: false,
        },
        {
          name_es: 'MERLO',
          search_name_es: 'MERLO',
          image: require('./res/image/image.png'),
          video: `${uri}/74PmkL4gDuk`,
          downloaded: false,
        },
        {
          name_es: 'MORENO',
          search_name_es: 'MORENO',
          image: require('./res/image/image.png'),
          video: `${uri}/HPGQxi-i7nY`,
          downloaded: false,
        },
        {
          name_es: 'MORÓN',
          search_name_es: 'MORÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/hWOcrwOt8l0`,
          downloaded: false,
        },
        {
          name_es: 'PALERMO',
          search_name_es: 'PALERMO',
          image: require('./res/image/image.png'),
          video: `${uri}/9kObQY2HL68`,
          downloaded: false,
        },
        {
          name_es: 'POMPEYA',
          search_name_es: 'POMPEYA',
          image: require('./res/image/image.png'),
          video: `${uri}/beUfdAPDjOg`,
          downloaded: false,
        },
        {
          name_es: 'QUILMES',
          search_name_es: 'QUILMES',
          image: require('./res/image/image.png'),
          video: `${uri}/pfchqEF37ZQ`,
          downloaded: false,
        },
        {
          name_es: 'RAMOS MEJÍA',
          search_name_es: 'RAMOS MEJÍA',
          image: require('./res/image/image.png'),
          video: `${uri}/CGGOF-0MfKk`,
          downloaded: false,
        },
        {
          name_es: 'RECOLETA',
          search_name_es: 'RECOLETA',
          image: require('./res/image/image.png'),
          video: `${uri}/Is907n3mbsk`,
          downloaded: false,
        },
        {
          name_es: 'RETIRO',
          search_name_es: 'RETIRO',
          image: require('./res/image/image.png'),
          video: `${uri}/n98Bl8Tanok`,
          downloaded: false,
        },
        {
          name_es: 'SAN ISIDRO',
          search_name_es: 'SAN ISIDRO',
          image: require('./res/image/image.png'),
          video: `${uri}/WlKq17aMaDY`,
          downloaded: false,
        },
        {
          name_es: 'SAN JUSTO',
          search_name_es: 'SAN JUSTO',
          image: require('./res/image/image.png'),
          video: `${uri}/Bj09CMyCnbo`,
          downloaded: false,
        },
        {
          name_es: 'SAN MARTÍN',
          search_name_es: 'SAN MARTÍN',
          image: require('./res/image/image.png'),
          video: `${uri}/_QTWdBfDHBQ`,
          downloaded: false,
        },
        {
          name_es: 'SAN MIGUEL',
          search_name_es: 'SAN MIGUEL',
          image: require('./res/image/image.png'),
          video: `${uri}/wZv3pwepal0`,
          downloaded: false,
        },
        {
          name_es: 'SAN TELMO',
          search_name_es: 'SAN TELMO',
          image: require('./res/image/image.png'),
          video: `${uri}/5sx7L1MCNIc`,
          downloaded: false,
        },
        {
          name_es: 'TEMPERLEY',
          search_name_es: 'TEMPERLEY',
          image: require('./res/image/image.png'),
          video: `${uri}/ho9EiDlmkgY`,
          downloaded: false,
        },
        {
          name_es: 'TIGRE',
          search_name_es: 'TIGRE',
          image: require('./res/image/image.png'),
          video: `${uri}/5QrDkzR295Q`,
          downloaded: false,
        },
        {
          name_es: 'VILLA DEL PARQUE',
          search_name_es: 'VILLA DEL PARQUE',
          image: require('./res/image/image.png'),
          video: `${uri}/P4f2D2aQ4Yo`,
          downloaded: false,
        },
        {
          name_es: 'VILLA DEVOTO',
          search_name_es: 'VILLA DEVOTO',
          image: require('./res/image/image.png'),
          video: `${uri}/ogOXqXU9DY8`,
          downloaded: false,
        },
        {
          name_es: 'VILLA LUGANO',
          search_name_es: 'VILLA LUGANO',
          image: require('./res/image/image.png'),
          video: `${uri}/GvaaIGbuudg`,
          downloaded: false,
        },
        {
          name_es: 'VILLA URQUIZA',
          search_name_es: 'VILLA URQUIZA',
          image: require('./res/image/image.png'),
          video: `${uri}/zLeFZlJu86U`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'COMUNIDAD SORDA',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'AFILIACIÓN',
          search_name_es: 'AFILIACIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/T_kRJ2xJnqw`,
          downloaded: false,
        },
        {
          name_es: 'APROBACIÓN',
          search_name_es: 'APROBACIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/OHwWeQJVcRY`,
          downloaded: false,
        },
        {
          name_es: 'ASAMBLEA',
          search_name_es: 'ASAMBLEA',
          image: require('./res/image/image.png'),
          video: `${uri}/mVG7x6-u3hI`,
          downloaded: false,
        },
        {
          name_es: 'ASOCIACIÓN',
          search_name_es: 'ASOCIACIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/QdUm9t-ycgc`,
          downloaded: false,
        },
        {
          name_es: 'CAS - CONFEDERACIÓN ARGENTINA DE SORDOS',
          search_name_es: 'CAS - CONFEDERACIÓN ARGENTINA DE SORDOS',
          image: require('./res/image/image.png'),
          video: `${uri}/3T0ZsE0H0ZA`,
          downloaded: false,
        },
        {
          name_es: 'COMISIÓN DIRECTIVA',
          search_name_es: 'COMISIÓN DIRECTIVA',
          image: require('./res/image/image.png'),
          video: `${uri}/cz3-9y-eEVI`,
          downloaded: false,
        },
        {
          name_es: 'COMUNIDAD SORDA',
          search_name_es: 'COMUNIDAD SORDA',
          image: require('./res/image/image.png'),
          video: `${uri}/rrcHwRm8JXk`,
          downloaded: false,
        },
        {
          name_es: 'CUD - CERTIFICADO ÚNICO DE DISCAPACIDAD',
          search_name_es: 'CUD - CERTIFICADO ÚNICO DE DISCAPACIDAD',
          image: require('./res/image/image.png'),
          video: `${uri}/56aw-S4az80`,
          downloaded: false,
        },
        {
          name_es: 'CULTURA',
          search_name_es: 'CULTURA',
          image: require('./res/image/image.png'),
          video: `${uri}/oYF--HYfwUs`,
          downloaded: false,
        },
        {
          name_es: 'DESAPROBACIÓN',
          search_name_es: 'DESAPROBACIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/VI53VBj6LkE`,
          downloaded: false,
        },
        {
          name_es: 'FEDERACIÓN',
          search_name_es: 'FEDERACIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/mrZ_6h-xGcA`,
          downloaded: false,
        },
        {
          name_es: 'FUNDACIÓN',
          search_name_es: 'FUNDACIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/xWRX3pDzmLw`,
          downloaded: false,
        },
        {
          name_es: 'FUNDASOR',
          search_name_es: 'FUNDASOR',
          image: require('./res/image/image.png'),
          video: `${uri}/eDaT1aMJOvQ`,
          downloaded: false,
        },
        {
          name_es: 'IDENTIDAD',
          search_name_es: 'IDENTIDAD',
          image: require('./res/image/image.png'),
          video: `${uri}/sVKqnu3hskY`,
          downloaded: false,
        },
        {
          name_es: 'IDIOMA',
          search_name_es: 'IDIOMA',
          image: require('./res/image/image.png'),
          video: `${uri}/s2X5s9p9hw8`,
          downloaded: false,
        },
        {
          name_es: 'INSTITUCIÓN',
          search_name_es: 'INSTITUCIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/HiQ3xq3IAmY`,
          downloaded: false,
        },
        {
          name_es: 'LENGUA DE SEÑAS ARGENTINA',
          search_name_es: 'LENGUA DE SEÑAS ARGENTINA',
          image: require('./res/image/image.png'),
          video: `${uri}/MksOSK7fK4g`,
          downloaded: false,
        },
        {
          name_es: 'LENGUAJE',
          search_name_es: 'LENGUAJE',
          image: require('./res/image/image.png'),
          video: `${uri}/OhBR4zvRUPs`,
          downloaded: false,
        },
        {
          name_es: 'PENSIÓN',
          search_name_es: 'PENSIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/VEOkgoBQDgE`,
          downloaded: false,
        },
        {
          name_es: 'PERSONERÍA JURÍDICA',
          search_name_es: 'PERSONERÍA JURÍDICA',
          image: require('./res/image/image.png'),
          video: `${uri}/hMV0WY2qNX0`,
          downloaded: false,
        },
        {
          name_es: 'PROYECTO',
          search_name_es: 'PROYECTO',
          image: require('./res/image/image.png'),
          video: `${uri}/bruvWeTHDCw`,
          downloaded: false,
        },
        {
          name_es: 'SISTEMA DE SEÑAS INTERNACIONAL',
          search_name_es: 'SISTEMA DE SEÑAS INTERNACIONAL',
          image: require('./res/image/image.png'),
          video: `${uri}/3IyZD44uHXI`,
          downloaded: false,
        },
        {
          name_es: 'SOLICITAR',
          search_name_es: 'SOLICITAR',
          image: require('./res/image/image.png'),
          video: `${uri}/n-xXfWnbAls`,
          downloaded: false,
        },
        {
          name_es: 'TRÁMITES',
          search_name_es: 'TRÁMITES',
          image: require('./res/image/image.png'),
          video: `${uri}/63tjX08pCBQ`,
          downloaded: false,
        },
        {
          name_es: 'VOLUNTARIADO',
          search_name_es: 'VOLUNTARIADO',
          image: require('./res/image/image.png'),
          video: `${uri}/UNIzpacU5us`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'CONVENCION SOBRE LOS DERECHOS DE LAS PERSONAS CON DISCAPACIDAD',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'ACCESIBILIDAD',
          search_name_es: 'ACCESIBILIDAD',
          image: require('./res/image/image.png'),
          video: `${uri}/https://youtu.be/gfTzMV2oLeA`,
          downloaded: false,
        },
        {
          name_es: 'ADECUACIÓN',
          search_name_es: 'ADECUACIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/https://youtu.be/7x63f7H_gp8`,
          downloaded: false,
        },
        {
          name_es: 'APOYO',
          search_name_es: 'APOYO',
          image: require('./res/image/image.png'),
          video: `${uri}/https://youtu.be/--oDoqNEmrQ`,
          downloaded: false,
        },
        {
          name_es: 'ARTÍCULOS',
          search_name_es: 'ARTÍCULOS',
          image: require('./res/image/image.png'),
          video: `${uri}/https://youtu.be/VuwwYo1WxfY`,
          downloaded: false,
        },
        {
          name_es: 'AUTONOMÍA',
          search_name_es: 'AUTONOMÍA',
          image: require('./res/image/image.png'),
          video: `${uri}/https://youtu.be/SlGF7SsyM7U`,
          downloaded: false,
        },
        {
          name_es: 'BARRERAS',
          search_name_es: 'BARRERAS',
          image: require('./res/image/image.png'),
          video: `${uri}/https://youtu.be/UoGJ8lTtuO0`,
          downloaded: false,
        },
        {
          name_es: 'CONGRESO',
          search_name_es: 'CONGRESO',
          image: require('./res/image/image.png'),
          video: `${uri}/https://youtu.be/PZTBywDjiUQ`,
          downloaded: false,
        },
        {
          name_es: 'CONVENCIÓN SOBRE LOS DERECHOS DE LAS PERSONAS CON DISCAPACIDAD',
          search_name_es: 'CONVENCIÓN SOBRE LOS DERECHOS DE LAS PERSONAS CON DISCAPACIDAD',
          image: require('./res/image/image.png'),
          video: `${uri}/https://youtu.be/HYmwK9SFUuk`,
          downloaded: false,
        },
        {
          name_es: 'CUMPLIMIENTO',
          search_name_es: 'CUMPLIMIENTO',
          image: require('./res/image/image.png'),
          video: `${uri}/https://youtu.be/MGb0auqyJqQ`,
          downloaded: false,
        },
        {
          name_es: 'DEBATE',
          search_name_es: 'DEBATE',
          image: require('./res/image/image.png'),
          video: `${uri}/https://youtu.be/bDZNqt4gk5c`,
          downloaded: false,
        },
        {
          name_es: 'DENUNCIAR',
          search_name_es: 'DENUNCIAR',
          image: require('./res/image/image.png'),
          video: `${uri}/sAx4s6XEj48`,
          downloaded: false,
        },
        {
          name_es: 'DERECHOS',
          search_name_es: 'DERECHOS',
          image: require('./res/image/image.png'),
          video: `${uri}/rFWHFXUCpUE`,
          downloaded: false,
        },
        {
          name_es: 'DIPUTADOS',
          search_name_es: 'DIPUTADOS',
          image: require('./res/image/image.png'),
          video: `${uri}/LX9zXp7Bj2A`,
          downloaded: false,
        },
        {
          name_es: 'ELECCIONES',
          search_name_es: 'ELECCIONES',
          image: require('./res/image/image.png'),
          video: `${uri}/iFHG4WVj2Wg`,
          downloaded: false,
        },
        {
          name_es: 'ELEGIR',
          search_name_es: 'ELEGIR',
          image: require('./res/image/image.png'),
          video: `${uri}/Sk0UQaHzUxg`,
          downloaded: false,
        },
        {
          name_es: 'EMPODERAMIENTO',
          search_name_es: 'EMPODERAMIENTO',
          image: require('./res/image/image.png'),
          video: `${uri}/mLxrnwIDMqc`,
          downloaded: false,
        },
        {
          name_es: 'ENCUESTA',
          search_name_es: 'ENCUESTA',
          image: require('./res/image/image.png'),
          video: `${uri}/f2lS9m2aBBs`,
          downloaded: false,
        },
        {
          name_es: 'EQUIDAD',
          search_name_es: 'EQUIDAD',
          image: require('./res/image/image.png'),
          video: `${uri}/I7vxWAdh-Jc`,
          downloaded: false,
        },
        {
          name_es: 'ESTADO',
          search_name_es: 'ESTADO',
          image: require('./res/image/image.png'),
          video: `${uri}/CwwmGwlvVXs`,
          downloaded: false,
        },
        {
          name_es: 'GOBIERNO',
          search_name_es: 'GOBIERNO',
          image: require('./res/image/image.png'),
          video: `${uri}/nMurd5kVJVs`,
          downloaded: false,
        },
        {
          name_es: 'IGUALDAD',
          search_name_es: 'IGUALDAD',
          image: require('./res/image/image.png'),
          video: `${uri}/uFTUYfAx-lU`,
          downloaded: false,
        },
        {
          name_es: 'INCLUSIÓN',
          search_name_es: 'INCLUSIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/5-g9R6tDQ44`,
          downloaded: false,
        },
        {
          name_es: 'INFORMACIÓN',
          search_name_es: 'INFORMACIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/fUS7VA1rlPI`,
          downloaded: false,
        },
        {
          name_es: 'JUSTICIA',
          search_name_es: 'JUSTICIA',
          image: require('./res/image/image.png'),
          video: `${uri}/SaKAKo32r8Q`,
          downloaded: false,
        },
        {
          name_es: 'LEY',
          search_name_es: 'LEY',
          image: require('./res/image/image.png'),
          video: `${uri}/d2sJjgpm38s`,
          downloaded: false,
        },
        {
          name_es: 'LUCHA',
          search_name_es: 'LUCHA',
          image: require('./res/image/image.png'),
          video: `${uri}/mtVBdg4ZsGE`,
          downloaded: false,
        },
        {
          name_es: 'MERCOSUR - MERCADO COMÚN DEL SUR',
          search_name_es: 'MERCOSUR - MERCADO COMÚN DEL SUR',
          image: require('./res/image/image.png'),
          video: `${uri}/LpwjEpbaRZk`,
          downloaded: false,
        },
        {
          name_es: 'NECESIDADES',
          search_name_es: 'NECESIDADES',
          image: require('./res/image/image.png'),
          video: `${uri}/-XgXV5PkOFs`,
          downloaded: false,
        },
        {
          name_es: 'NORMAS',
          search_name_es: 'NORMAS',
          image: require('./res/image/image.png'),
          video: `${uri}/KJYDFCOqwW8`,
          downloaded: false,
        },
        {
          name_es: 'OBJETIVO',
          search_name_es: 'OBJETIVO',
          image: require('./res/image/image.png'),
          video: `${uri}/3apG8t8dlrk`,
          downloaded: false,
        },
        {
          name_es: 'PARTICIPACIÓN',
          search_name_es: 'PARTICIPACIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/CcKV06wVfzM`,
          downloaded: false,
        },
        {
          name_es: 'POLÍTICA',
          search_name_es: 'POLÍTICA',
          image: require('./res/image/image.png'),
          video: `${uri}/FqCE15a4Ink`,
          downloaded: false,
        },
        {
          name_es: 'PROTECCIÓN',
          search_name_es: 'PROTECCIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/12TQ8cqdAvk`,
          downloaded: false,
        },
        {
          name_es: 'RECLAMAR',
          search_name_es: 'RECLAMAR',
          image: require('./res/image/image.png'),
          video: `${uri}/W0DwfSL8rwg`,
          downloaded: false,
        },
        {
          name_es: 'RECONOCIMIENTO',
          search_name_es: 'RECONOCIMIENTO',
          image: require('./res/image/image.png'),
          video: `${uri}/COgd8FOcK8Q`,
          downloaded: false,
        },
        {
          name_es: 'REGLAMENTACIÓN',
          search_name_es: 'REGLAMENTACIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/04Vumx9rGzY`,
          downloaded: false,
        },
        {
          name_es: 'RESPONSABILIDAD',
          search_name_es: 'RESPONSABILIDAD',
          image: require('./res/image/image.png'),
          video: `${uri}/eUuXYokDqrA`,
          downloaded: false,
        },
        {
          name_es: 'SENADORES',
          search_name_es: 'SENADORES',
          image: require('./res/image/image.png'),
          video: `${uri}/PoXKwDppNMA`,
          downloaded: false,
        },
        {
          name_es: 'SERVICIO',
          search_name_es: 'SERVICIO',
          image: require('./res/image/image.png'),
          video: `${uri}/NdJ73261loQ`,
          downloaded: false,
        },
        {
          name_es: 'SOCIEDAD',
          search_name_es: 'SOCIEDAD',
          image: require('./res/image/image.png'),
          video: `${uri}/vT65AVCnm-U`,
          downloaded: false,
        },
        {
          name_es: 'TOMAR CONCIENCIA',
          search_name_es: 'TOMAR CONCIENCIA',
          image: require('./res/image/image.png'),
          video: `${uri}/Yygr7xgjcJQ`,
          downloaded: false,
        },
        {
          name_es: 'VISIBILIZAR',
          search_name_es: 'VISIBILIZAR',
          image: require('./res/image/image.png'),
          video: `${uri}/n3_CIoSABR8`,
          downloaded: false,
        },
        {
          name_es: 'VOTAR',
          search_name_es: 'VOTAR',
          image: require('./res/image/image.png'),
          video: `${uri}/Vr7VAFBSUkw`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'DEPORTES',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'ARTES MARCIALES',
          search_name_es: 'ARTES MARCIALES',
          image: require('./res/image/image.png'),
          video: `${uri}/RMHl7SS7vx0`,
          downloaded: false,
        },
        {
          name_es: 'ATLETISMO',
          search_name_es: 'ATLETISMO',
          image: require('./res/image/image.png'),
          video: `${uri}/WtAn9kha_8o`,
          downloaded: false,
        },
        {
          name_es: 'AUTOMOVILISMO',
          search_name_es: 'AUTOMOVILISMO',
          image: require('./res/image/image.png'),
          video: `${uri}/wvwmiZfeGAs`,
          downloaded: false,
        },
        {
          name_es: 'BASQUET',
          search_name_es: 'BASQUET',
          image: require('./res/image/image.png'),
          video: `${uri}/n8KBwphWmj0`,
          downloaded: false,
        },
        {
          name_es: 'BOWLING',
          search_name_es: 'BOWLING',
          image: require('./res/image/image.png'),
          video: `${uri}/tah7p73h9kI`,
          downloaded: false,
        },
        {
          name_es: 'CAMPEONATO',
          search_name_es: 'CAMPEONATO',
          image: require('./res/image/image.png'),
          video: `${uri}/xhe1dVA7tfI`,
          downloaded: false,
        },
        {
          name_es: 'CICLISMO',
          search_name_es: 'CICLISMO',
          image: require('./res/image/image.png'),
          video: `${uri}/3ksw99hgWwE`,
          downloaded: false,
        },
        {
          name_es: 'DEPORTES',
          search_name_es: 'DEPORTES',
          image: require('./res/image/image.png'),
          video: `${uri}/nTT1XFMX00M`,
          downloaded: false,
        },
        {
          name_es: 'GOLF',
          search_name_es: 'GOLF',
          image: require('./res/image/image.png'),
          video: `${uri}/bO1ovkIXqBI`,
          downloaded: false,
        },
        {
          name_es: 'HANDBOL',
          search_name_es: 'HANDBOL',
          image: require('./res/image/image.png'),
          video: `${uri}/nGGPMsZgB5E`,
          downloaded: false,
        },
        {
          name_es: 'HOCKEY',
          search_name_es: 'HOCKEY',
          image: require('./res/image/image.png'),
          video: `${uri}/qHNJe8kqeNM`,
          downloaded: false,
        },
        {
          name_es: 'NATACIÓN',
          search_name_es: 'Natación',
          image: require('./res/image/image.png'),
          video: `${uri}/jzccHqJCQLQ`,
          downloaded: false,
        },
        {
          name_es: 'OLIMPIADAS',
          search_name_es: 'Olimpiadas',
          image: require('./res/image/image.png'),
          video: `${uri}/9Su7zTB61wQ`,
          downloaded: false,
        },
        {
          name_es: 'PAPI FÚTBOL',
          search_name_es: 'PAPI FÚTBOL',
          image: require('./res/image/image.png'),
          video: `${uri}/qiYEQ_JfRHM`,
          downloaded: false,
        },
        {
          name_es: 'PATINES',
          search_name_es: 'PATINES',
          image: require('./res/image/image.png'),
          video: `${uri}/Q4K3Tzo6zKo`,
          downloaded: false,
        },
        {
          name_es: 'RUGBY',
          search_name_es: 'RUGBY',
          image: require('./res/image/image.png'),
          video: `${uri}/2XIWV5SdvkE`,
          downloaded: false,
        },
        {
          name_es: 'SURF',
          search_name_es: 'SURF',
          image: require('./res/image/image.png'),
          video: `${uri}/bNGT08JGv-c`,
          downloaded: false,
        },
        {
          name_es: 'TENIS',
          search_name_es: 'TENIS',
          image: require('./res/image/image.png'),
          video: `${uri}/8hrEFUDfIEg`,
          downloaded: false,
        },
        {
          name_es: 'VOLEIBOL',
          search_name_es: 'VOLEIBOL',
          image: require('./res/image/image.png'),
          video: `${uri}/vvY4hvA0Os8`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'EDUCACION',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'CAPACITACIÓN',
          search_name_es: 'CAPACITACIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/9Q1O8mvZ0KY`,
          downloaded: false,
        },
        {
          name_es: 'CARRERA',
          search_name_es: 'CARRERA',
          image: require('./res/image/image.png'),
          video: `${uri}/0SITRwwW2vc`,
          downloaded: false,
        },
        {
          name_es: 'CURSO',
          search_name_es: 'CURSO',
          image: require('./res/image/image.png'),
          video: `${uri}/_7mOA_Yk6jk`,
          downloaded: false,
        },
        {
          name_es: 'EDUCACIÓN',
          search_name_es: 'EDUCACIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/4cKEI3n0qvo`,
          downloaded: false,
        },
        {
          name_es: 'EXAMEN',
          search_name_es: 'EXAMEN',
          image: require('./res/image/image.png'),
          video: `${uri}/iAxVttz2KsE`,
          downloaded: false,
        },
        {
          name_es: 'FORMACIÓN',
          search_name_es: 'FORMACIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/ncU2sSvf6io`,
          downloaded: false,
        },
        {
          name_es: 'JORNADA',
          search_name_es: 'JORNADA',
          image: require('./res/image/image.png'),
          video: `${uri}/A0r8QPEMDtQ`,
          downloaded: false,
        },
        {
          name_es: 'NOTA',
          search_name_es: 'NOTA',
          image: require('./res/image/image.png'),
          video: `${uri}/T0_pzwEoO1A`,
          downloaded: false,
        },
        {
          name_es: 'PLANIFICACIÓN',
          search_name_es: 'Planificación',
          image: require('./res/image/image.png'),
          video: `${uri}/6nLzxdp-nKw`,
          downloaded: false,
        },
        {
          name_es: 'PRIMARIA',
          search_name_es: 'Primaria',
          image: require('./res/image/image.png'),
          video: `${uri}/nSjrrYJFboA`,
          downloaded: false,
        },
        {
          name_es: 'SECUNDARIA',
          search_name_es: 'SECUNDARIA',
          image: require('./res/image/image.png'),
          video: `${uri}/MU6UsjXKSzg`,
          downloaded: false,
        },
        {
          name_es: 'TEMA',
          search_name_es: 'TEMA',
          image: require('./res/image/image.png'),
          video: `${uri}/oAiVT2ApsyU`,
          downloaded: false,
        },
        {
          name_es: 'TERCIARIA',
          search_name_es: 'Terciaria',
          image: require('./res/image/image.png'),
          video: `${uri}/5rpsQHcHrAg`,
          downloaded: false,
        },
        {
          name_es: 'TRABAJO PRÁCTICO',
          search_name_es: 'TRABAJO PRÁCTICO',
          image: require('./res/image/image.png'),
          video: `${uri}/3SiPI5w2YuE`,
          downloaded: false,
        },
        {
          name_es: 'UNIVERSIDAD',
          search_name_es: 'UNIVERSIDAD',
          image: require('./res/image/image.png'),
          video: `${uri}/2CejdW8F0TM`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'EL HOSPITAL',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'Autorización',
          search_name_es: 'Autorización',
          image: require('./res/image/image.png'),
          video: `${uri}/l0e1e-ppIB4`,
          downloaded: false,
        },
        {
          name_es: 'Clínica',
          search_name_es: 'Clínica',
          image: require('./res/image/image.png'),
          video: `${uri}/bt4l7yBIwc8`,
          downloaded: false,
        },
        {
          name_es: 'Embarazo',
          search_name_es: 'Embarazo',
          image: require('./res/image/image.png'),
          video: `${uri}/E70ZEtE_3WY`,
          downloaded: false,
        },
        {
          name_es: 'Enfermedades',
          search_name_es: 'Enfermedades',
          image: require('./res/image/image.png'),
          video: `${uri}/7-uTN05Hn_I`,
          downloaded: false,
        },
        {
          name_es: 'Internación',
          search_name_es: 'Internación',
          image: require('./res/image/image.png'),
          video: `${uri}/tB6Xm-f5zfw`,
          downloaded: false,
        },
        {
          name_es: 'Médico Cirujano',
          search_name_es: 'Médico Cirujano',
          image: require('./res/image/image.png'),
          video: `${uri}/e7HXvnGFclU`,
          downloaded: false,
        },
        {
          name_es: 'Médico Ginecólogo',
          search_name_es: 'Médico Ginecólogo',
          image: require('./res/image/image.png'),
          video: `${uri}/6ciXV0GmW4s`,
          downloaded: false,
        },
        {
          name_es: 'Médico Odontólogo',
          search_name_es: 'Médico Odontólogo',
          image: require('./res/image/image.png'),
          video: `${uri}/gieMKjH4PDI`,
          downloaded: false,
        },
        {
          name_es: 'Médico Oftalmólogo',
          search_name_es: 'Médico Oftalmólogo',
          image: require('./res/image/image.png'),
          video: `${uri}/2L_kXMuQkC8`,
          downloaded: false,
        },
        {
          name_es: 'Médico Trumatólogo',
          search_name_es: 'Médico Trumatólogo',
          image: require('./res/image/image.png'),
          video: `${uri}/844NCGMCkyg`,
          downloaded: false,
        },
        {
          name_es: 'Obra Social',
          search_name_es: 'Obra Social',
          image: require('./res/image/image.png'),
          video: `${uri}/Vp1zcO5Mfp0`,
          downloaded: false,
        },
        {
          name_es: 'Privada',
          search_name_es: 'Privada',
          image: require('./res/image/image.png'),
          video: `${uri}/7-fKexXS88w`,
          downloaded: false,
        },
        {
          name_es: 'Pública',
          search_name_es: 'Pública',
          image: require('./res/image/image.png'),
          video: `${uri}/1ZkkYvw1SHY`,
          downloaded: false,
        },
        {
          name_es: 'Resonancia',
          search_name_es: 'Resonancia',
          image: require('./res/image/image.png'),
          video: `${uri}/-A-pgNEIbS0`,
          downloaded: false,
        },
        {
          name_es: 'Test HIV',
          search_name_es: 'Test HIV',
          image: require('./res/image/image.png'),
          video: `${uri}/ASBfROtzDK8`,
          downloaded: false,
        },
        {
          name_es: 'Tratamiento',
          search_name_es: 'Tratamiento',
          image: require('./res/image/image.png'),
          video: `${uri}/a--B7Igx6FM`,
          downloaded: false,
        },
        {
          name_es: 'Yeso',
          search_name_es: 'Yeso',
          image: require('./res/image/image.png'),
          video: `${uri}/p2CEN-KIIt4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'EDUCACIÓN SEXUAL INTEGRAL',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'ABUSO',
          search_name_es: 'ABUSO',
          image: require('./res/image/image.png'),
          video: `${uri}/S4H-Zu-AWLY`,
          downloaded: false,
        },
        {
          name_es: 'ACOSO',
          search_name_es: 'ACOSO',
          image: require('./res/image/image.png'),
          video: `${uri}/oIYXnlaz6TI`,
          downloaded: false,
        },
        {
          name_es: 'BISEXUAL',
          search_name_es: 'BISEXUAL',
          image: require('./res/image/image.png'),
          video: `${uri}/70EcBpZ2Rcs`,
          downloaded: false,
        },
        {
          name_es: 'BULLYING',
          search_name_es: 'BULLYING',
          image: require('./res/image/image.png'),
          video: `${uri}/wukJVs29usg`,
          downloaded: false,
        },
        {
          name_es: 'COMUNIDAD LGTBIQ',
          search_name_es: 'COMUNIDAD LGTBIQ',
          image: require('./res/image/image.png'),
          video: `${uri}/Xs3S5oO9MrI`,
          downloaded: false,
        },
        {
          name_es: 'DIVERSIDAD',
          search_name_es: 'DIVERSIDAD',
          image: require('./res/image/image.png'),
          video: `${uri}/wVxNnQL85Qc`,
          downloaded: false,
        },
        {
          name_es: 'EDUCACIÓN SEXUAL INTEGRAL ESI',
          search_name_es: 'EDUCACIÓN SEXUAL INTEGRAL ESI',
          image: require('./res/image/image.png'),
          video: `${uri}/HVeN18unpag`,
          downloaded: false,
        },
        {
          name_es: 'EMPATÍA',
          search_name_es: 'EMPATÍA',
          image: require('./res/image/image.png'),
          video: `${uri}/ltuZsCMn03Q`,
          downloaded: false,
        },
        {
          name_es: 'GAY',
          search_name_es: 'GAY',
          image: require('./res/image/image.png'),
          video: `${uri}/Dwf1xksDMY4`,
          downloaded: false,
        },
        {
          name_es: 'GÉNERO',
          search_name_es: 'GÉNERO',
          image: require('./res/image/image.png'),
          video: `${uri}/uzFeoe56L1Y`,
          downloaded: false,
        },
        {
          name_es: 'HETEROSEXUAL',
          search_name_es: 'HETEROSEXUAL',
          image: require('./res/image/image.png'),
          video: `${uri}/pbaJMlD6xF8`,
          downloaded: false,
        },
        {
          name_es: 'LESBIANA',
          search_name_es: 'LESBIANA',
          image: require('./res/image/image.png'),
          video: `${uri}/Hy3tJODOWMI`,
          downloaded: false,
        },
        {
          name_es: 'NI UNA MENOS',
          search_name_es: 'NI UNA MENOS',
          image: require('./res/image/image.png'),
          video: `${uri}/hIHjWgLESJ4`,
          downloaded: false,
        },
        {
          name_es: 'TRANSEXUAL',
          search_name_es: 'TRANSEXUAL',
          image: require('./res/image/image.png'),
          video: `${uri}/QoJB9eCWheI`,
          downloaded: false,
        },
        {
          name_es: 'TRAVESTI',
          search_name_es: 'TRAVESTI',
          image: require('./res/image/image.png'),
          video: `${uri}/FFYLJOO_4Z0`,
          downloaded: false,
        },
        {
          name_es: 'VIOLENCIA',
          search_name_es: 'VIOLENCIA',
          image: require('./res/image/image.png'),
          video: `${uri}/w9LCMKEHwhs`,
          downloaded: false,
        },
        {
          name_es: 'VIOLENCIA ECONÓMICA',
          search_name_es: 'VIOLENCIA ECONÓMICA',
          image: require('./res/image/image.png'),
          video: `${uri}/o94q4VYJT_k`,
          downloaded: false,
        },
        {
          name_es: 'VIOLENCIA FÍSICA',
          search_name_es: 'VIOLENCIA FÍSICA',
          image: require('./res/image/image.png'),
          video: `${uri}/GmawpOPmwjE`,
          downloaded: false,
        },
        {
          name_es: 'VIOLENCIA PSICOLÓGICA',
          search_name_es: 'VIOLENCIA PSICOLÓGICA',
          image: require('./res/image/image.png'),
          video: `${uri}/F4N5WY-rDRg`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'FAMILIA',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'BISABUELO',
          search_name_es: 'BISABUELO',
          image: require('./res/image/image.png'),
          video: `${uri}/n_7ZC8sJNDA`,
          downloaded: false,
        },
        {
          name_es: 'CUÑADO',
          search_name_es: 'CUÑADO',
          image: require('./res/image/image.png'),
          video: `${uri}/bMbt3LGEop4`,
          downloaded: false,
        },
        {
          name_es: 'GEMELOS',
          search_name_es: 'GEMELOS',
          image: require('./res/image/image.png'),
          video: `${uri}/n1J-BgOFVfQ`,
          downloaded: false,
        },
        {
          name_es: 'HIJASTRO',
          search_name_es: 'HIJASTRO',
          image: require('./res/image/image.png'),
          video: `${uri}/qkyknCaUrYw`,
          downloaded: false,
        },
        {
          name_es: 'MADRASTRA',
          search_name_es: 'MADRASTRA',
          image: require('./res/image/image.png'),
          video: `${uri}/nZ7O0_uI1dQ`,
          downloaded: false,
        },
        {
          name_es: 'MADRINA',
          search_name_es: 'MADRINA',
          image: require('./res/image/image.png'),
          video: `${uri}/Q1VeLvQqUNM`,
          downloaded: false,
        },
        {
          name_es: 'MELLIZOS',
          search_name_es: 'MELLIZOS',
          image: require('./res/image/image.png'),
          video: `${uri}/lp4p9Q4MVts`,
          downloaded: false,
        },
        {
          name_es: 'NOVIO',
          search_name_es: 'NOVIO',
          image: require('./res/image/image.png'),
          video: `${uri}/d30ncvaVg70`,
          downloaded: false,
        },
        {
          name_es: 'PADRASTRO',
          search_name_es: 'PADRASTRO',
          image: require('./res/image/image.png'),
          video: `${uri}/vBkyFDA56WA`,
          downloaded: false,
        },
        {
          name_es: 'PADRINO',
          search_name_es: 'PADRINO',
          image: require('./res/image/image.png'),
          video: `${uri}/mRBLynO7INQ`,
          downloaded: false,
        },
        {
          name_es: 'PAREJA',
          search_name_es: 'PAREJA',
          image: require('./res/image/image.png'),
          video: `${uri}/OQ3uwQBph7I`,
          downloaded: false,
        },
        {
          name_es: 'SOBRINO',
          search_name_es: 'SOBRINO',
          image: require('./res/image/image.png'),
          video: `${uri}/-0v4B9FpEGA`,
          downloaded: false,
        },
        {
          name_es: 'SUEGRO',
          search_name_es: 'SUEGRO',
          image: require('./res/image/image.png'),
          video: `${uri}/gScx9Fo-mRM`,
          downloaded: false,
        },
        {
          name_es: 'VIEJO',
          search_name_es: 'VIEJO',
          image: require('./res/image/image.png'),
          video: `${uri}/Se5pKKubI0k`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'NOCIONES DE LA COMUNIDAD SORDA',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'LS 1',
          search_name_es: 'LS 1',
          image: require('./res/image/image.png'),
          video: `${uri}/01cUvV4wCzs`,
          downloaded: false,
        },
        {
          name_es: 'LS 2',
          search_name_es: 'LS 2',
          image: require('./res/image/image.png'),
          video: `${uri}/0FsNha0LVQE`,
          downloaded: false,
        },
        {
          name_es: 'LSA',
          search_name_es: 'LSA',
          image: require('./res/image/image.png'),
          video: `${uri}/7QXAyS3Kr9A`,
          downloaded: false,
        },
        {
          name_es: '19/09',
          search_name_es: '19/09',
          image: require('./res/image/image.png'),
          video: `${uri}/ZW-1y5tZcXg`,
          downloaded: false,
        },
        {
          name_es: '23/09',
          search_name_es: '23/09',
          image: require('./res/image/image.png'),
          video: `${uri}/G4PYxGjxD9A`,
          downloaded: false,
        },
        {
          name_es: 'FAMILIAS',
          search_name_es: 'FAMILIAS',
          image: require('./res/image/image.png'),
          video: `${uri}/verT0Kxj-uE`,
          downloaded: false,
        },
        {
          name_es: 'Ley 26.378',
          search_name_es: 'Ley 26.378',
          image: require('./res/image/image.png'),
          video: `${uri}/h5erx1Y9vvs`,
          downloaded: false,
        },
        {
          name_es: 'TECNOLOGÍA',
          search_name_es: 'TECNOLOGÍA',
          image: require('./res/image/image.png'),
          video: `${uri}/BowW9e-xXyU`,
          downloaded: false,
        },
        {
          name_es: 'DEPORTES',
          search_name_es: 'DEPORTES',
          image: require('./res/image/image.png'),
          video: `${uri}/VxiiAyHRoNU`,
          downloaded: false,
        },
        {
          name_es: 'CUD',
          search_name_es: 'CUD',
          image: require('./res/image/image.png'),
          video: `${uri}/RSqvM5hH6G4`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'JUEGOS',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'AJEDREZ',
          search_name_es: 'AJEDREZ',
          image: require('./res/image/image.png'),
          video: `${uri}/yt1k3dh5uaw`,
          downloaded: false,
        },
        {
          name_es: 'CARTAS',
          search_name_es: 'CARTAS',
          image: require('./res/image/image.png'),
          video: `${uri}/Z8THpuVSQ1Q`,
          downloaded: false,
        },
        {
          name_es: 'DADOS',
          search_name_es: 'DADOS',
          image: require('./res/image/image.png'),
          video: `${uri}/CZ2kjMNsUWk`,
          downloaded: false,
        },
        {
          name_es: 'DAMAS',
          search_name_es: 'DAMAS',
          image: require('./res/image/image.png'),
          video: `${uri}/3xHvmVsz86k`,
          downloaded: false,
        },
        {
          name_es: 'DOMINÓ',
          search_name_es: 'DOMINÓ',
          image: require('./res/image/image.png'),
          video: `${uri}/a7QVsNAfJmI`,
          downloaded: false,
        },
        {
          name_es: 'JUEGOS',
          search_name_es: 'JUEGOS',
          image: require('./res/image/image.png'),
          video: `${uri}/sMv5Agg8Tdc`,
          downloaded: false,
        },
        {
          name_es: 'PLAYSTATION',
          search_name_es: 'PLAYSTATION',
          image: require('./res/image/image.png'),
          video: `${uri}/HWWGagnjBRU`,
          downloaded: false,
        },
        {
          name_es: 'POOL',
          search_name_es: 'POOL',
          image: require('./res/image/image.png'),
          video: `${uri}/lrLKfGRdOWg`,
          downloaded: false,
        },
        {
          name_es: 'ROMPECABEZAS',
          search_name_es: 'ROMPECABEZAS',
          image: require('./res/image/image.png'),
          video: `${uri}/pik6q8vYNnY`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'MEDIDAS',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'CANTIDAD',
          search_name_es: 'CANTIDAD',
          image: require('./res/image/image.png'),
          video: `${uri}/rIWUeu8332o`,
          downloaded: false,
        },
        {
          name_es: 'KILO',
          search_name_es: 'KILO',
          image: require('./res/image/image.png'),
          video: `${uri}/k7OQc88A9FQ`,
          downloaded: false,
        },
        {
          name_es: 'LITRO',
          search_name_es: 'LITRO',
          image: require('./res/image/image.png'),
          video: `${uri}/B0OSvUo9Ow0`,
          downloaded: false,
        },
        {
          name_es: 'MILLÓN',
          search_name_es: 'MILLÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/8tcOeOjaIVs`,
          downloaded: false,
        },
        {
          name_es: 'PESO',
          search_name_es: 'PESO',
          image: require('./res/image/image.png'),
          video: `${uri}/Grl9PPEgP3w`,
          downloaded: false,
        },
        {
          name_es: 'PORCENTAJE',
          search_name_es: 'PORCENTAJE',
          image: require('./res/image/image.png'),
          video: `${uri}/UcTm5X_m6l8`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'OTROS PAÍSES',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'ÁFRICA',
          search_name_es: 'ÁFRICA',
          image: require('./res/image/image.png'),
          video: `${uri}/mKCewZWx3is`,
          downloaded: false,
        },
        {
          name_es: 'AMÉRICA',
          search_name_es: 'AMÉRICA',
          image: require('./res/image/image.png'),
          video: `${uri}/np_A_4EyUQQ`,
          downloaded: false,
        },
        {
          name_es: 'AMÉRICA CENTRAL',
          search_name_es: 'AMÉRICA CENTRAL',
          image: require('./res/image/image.png'),
          video: `${uri}/1DediiBRJVo`,
          downloaded: false,
        },
        {
          name_es: 'AMÉRICA DEL NORTE',
          search_name_es: 'AMÉRICA DEL NORTE',
          image: require('./res/image/image.png'),
          video: `${uri}/PYxzTmeDUkc`,
          downloaded: false,
        },
        {
          name_es: 'ASIA',
          search_name_es: 'ASIA',
          image: require('./res/image/image.png'),
          video: `${uri}/xm7f8I-zqlY`,
          downloaded: false,
        },
        {
          name_es: 'EUROPA',
          search_name_es: 'EUROPA',
          image: require('./res/image/image.png'),
          video: `${uri}/_BRpYFvBf3U`,
          downloaded: false,
        },
        {
          name_es: 'LATINOAMÉRICA',
          search_name_es: 'LATINOAMÉRICA',
          image: require('./res/image/image.png'),
          video: `${uri}/eH6Fl6hSjS0`,
          downloaded: false,
        },
        {
          name_es: 'OCEANÍA',
          search_name_es: 'OCEANÍA',
          image: require('./res/image/image.png'),
          video: `${uri}/gaCWJloqHLU`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'TECNOLOGÍA',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'ADJUNTAR',
          search_name: 'ADJUNTAR',
          image: require('./res/image/adjuntar.png'),
          video: `${uri}/_3ODlLGtB64`,
          downloaded: false,
        },
        {
          name_es: 'BLOG',
          search_name: 'BLOG',
          image: require('./res/image/blog.png'),
          video: `${uri}/qG9_R1yborE`,
          downloaded: false,
        },
        {
          name_es: 'DRIVE',
          search_name: 'DRIVE',
          image: require('./res/image/drive.png'),
          video: `${uri}/fxkasr8CM8c`,
          downloaded: false,
        },
        {
          name_es: 'EMAIL',
          search_name: 'EMAIL',
          image: require('./res/image/email.png'),
          video: `${uri}/bPHTo4hwiQQ`,
          downloaded: false,
        },
        {
          name_es: 'ESCÁNER',
          search_name: 'ESCÁNER',
          image: require('./res/image/scanner.png'),
          video: `${uri}/RVU1WyWtKRY`,
          downloaded: false,
        },
        {
          name_es: 'FACEBOOK',
          search_name: 'FACEBOOK',
          image: require('./res/image/facebook.png'),
          video: `${uri}/sCs3sB37lso`,
          downloaded: false,
        },
        {
          name_es: 'GOOGLE',
          search_name: 'GOOGLE',
          image: require('./res/image/google.png'),
          video: `${uri}/edL9Lt7Xbqs`,
          downloaded: false,
        },
        {
          name_es: 'INSTAGRAM',
          search_name: 'INSTAGRAM',
          image: require('./res/image/instagram.png'),
          video: `${uri}/cbsVLJTKg5Q`,
          downloaded: false,
        },
        {
          name_es: 'MEMORIA',
          search_name: 'MEMORIA',
          image: require('./res/image/memoria.png'),
          video: `${uri}/wWygIkPyTjY`,
          downloaded: false,
        },
        {
          name_es: 'NETFLIX',
          search_name: 'NETFLIX',
          image: require('./res/image/netflix.png'),
          video: `${uri}/88_E_h_0hJQ`,
          downloaded: false,
        },
        {
          name_es: 'NOTEBOOK',
          search_name: 'NOTEBOOK',
          image: require('./res/image/notebook.png'),
          video: `${uri}/UoKk6hIgYs0`,
          downloaded: false,
        },
        {
          name_es: 'PÁGINA WEB',
          search_name: 'PÁGINA WEB',
          image: require('./res/image/pagina-web.png'),
          video: `${uri}/BIKmuhZsfJw`,
          downloaded: false,
        },
        {
          name_es: 'PENDRIVE',
          search_name: 'PENDRIVE',
          image: require('./res/image/pendrive.png'),
          video: `${uri}/wf-ZzfcNeYs`,
          downloaded: false,
        },
        {
          name_es: 'PROYECTOR',
          search_name: 'PROYECTOR',
          image: require('./res/image/proyector.png'),
          video: `${uri}/JFIwXdHhGWI`,
          downloaded: false,
        },
        {
          name_es: 'TABLET',
          search_name: 'TABLET',
          image: require('./res/image/tablet.png'),
          video: `${uri}/GBacsL5rTSI`,
          downloaded: false,
        },
        {
          name_es: 'TWITTER',
          search_name: 'TWITTER',
          image: require('./res/image/twitter.png'),
          video: `${uri}/bUS6pacHdk0`,
          downloaded: false,
        },
        {
          name_es: 'VIDEO',
          search_name: 'VIDEO',
          image: require('./res/image/video.png'),
          video: `${uri}/oRqb7PSu7W4`,
          downloaded: false,
        },
        {
          name_es: 'VIDEOLLAMADA',
          search_name: 'VIDEOLLAMADA',
          image: require('./res/image/video-llamada.png'),
          video: `${uri}/RBlX6mvGFAg`,
          downloaded: false,
        },
        {
          name_es: 'WHATSAPP',
          search_name: 'WHATSAPP',
          image: require('./res/image/whatsapp.png'),
          video: `${uri}/RT1Ed9dBrO0`,
          downloaded: false,
        },
        {
          name_es: 'WIFI',
          search_name: 'WIFI',
          image: require('./res/image/wifi.png'),
          video: `${uri}/AYTokD4A2NQ`,
          downloaded: false,
        },
        {
          name_es: 'YOUTUBE',
          search_name: 'YOUTUBE',
          image: require('./res/image/youtube.png'),
          video: `${uri}/FLL08ypUEko`,
          downloaded: false,
        },
        {
          name_es: 'ZOOM',
          search_name: 'ZOOM',
          image: require('./res/image/zoom.png'),
          video: `${uri}/PFDz8chkeRo`,
          downloaded: false,
        },
      ],
    },
    {
      name_es: 'TIEMPO LIBRE',
      icon: require('./res/icon/icon.png'),
      videos: [
        {
          name_es: 'ACTIVIDAD',
          search_name_es: 'ACTIVIDAD',
          image: require('./res/image/image.png'),
          video: `${uri}/5p8RUwJVsSg`,
          downloaded: false,
        },
        {
          name_es: 'ALQUILAR',
          search_name_es: 'ALQUILAR',
          image: require('./res/image/image.png'),
          video: `${uri}/BJ9PhptVjYY`,
          downloaded: false,
        },
        {
          name_es: 'CLUB',
          search_name_es: 'CLUB',
          image: require('./res/image/image.png'),
          video: `${uri}/5tx2sus8psA`,
          downloaded: false,
        },
        {
          name_es: 'DESCANSAR',
          search_name_es: 'DESCANSAR',
          image: require('./res/image/image.png'),
          video: `${uri}/u3mwBvtgRhU`,
          downloaded: false,
        },
        {
          name_es: 'GIMNASIA',
          search_name_es: 'GIMNASIA',
          image: require('./res/image/image.png'),
          video: `${uri}/LY6_pUgWr-4`,
          downloaded: false,
        },
        {
          name_es: 'MEDITACIÓN',
          search_name_es: 'MEDITACIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/ejfNpqaSy8Y`,
          downloaded: false,
        },
        {
          name_es: 'MUSEO',
          search_name_es: 'MUSEO',
          image: require('./res/image/image.png'),
          video: `${uri}/u2ZIeliFM7g`,
          downloaded: false,
        },
        {
          name_es: 'RECREACIÓN',
          search_name_es: 'RECREACIÓN',
          image: require('./res/image/image.png'),
          video: `${uri}/2dew16rp0pQ`,
          downloaded: false,
        },
        {
          name_es: 'TEATRO',
          search_name_es: 'TEATRO',
          image: require('./res/image/image.png'),
          video: `${uri}/ss1DYtJ7K1s`,
          downloaded: false,
        },
        {
          name_es: 'TIEMPO LIBRE',
          search_name_es: 'TIEMPO LIBRE',
          image: require('./res/image/image.png'),
          video: `${uri}/txHi-1ZamzE`,
          downloaded: false,
        },
        {
          name_es: 'TuriSMO',
          search_name_es: 'TuriSMO',
          image: require('./res/image/image.png'),
          video: `${uri}/6GETAkBoskc`,
          downloaded: false,
        },
        {
          name_es: 'VISITA GUIADA',
          search_name_es: 'VISITA GUIADA',
          image: require('./res/image/image.png'),
          video: `${uri}/Vfc1KM9Vkzk`,
          downloaded: false,
        },
        {
          name_es: 'YOGA',
          search_name_es: 'YOGA',
          image: require('./res/image/image.png'),
          video: `${uri}/6MD7hj6EpGE`,
          downloaded: false,
        },
      ],
    },
  ],
};
