{
    name_es: 'EL HOSPITAL',
    search_name_es: 'EL HOSPITAL',
    image: require('./res/image/el-hospital.png'),
    video: `${uri}/el-hospital.mp4`,
    downloaded: false,
  },
  {
    name_es: 'MÉDICO',
    search_name_es: 'MEDICO',
    image: require('./res/image/medico.png'),
    video: `${uri}/medico.mp4`,
    downloaded: false,
  },
  {
    name_es: 'REVISAR',
    search_name_es: 'REVISAR',
    image: require('./res/image/revisar.png'),
    video: `${uri}/revisar.mp4`,
    downloaded: false,
  },
  {
    name_es: 'ENFERMERA',
    search_name_es: 'ENFERMERA',
    image: require('./res/image/enfermera.png'),
    video: `${uri}/enfermera.mp4`,
    downloaded: false,
  },
  {
    name_es: 'OCULISTA',
    search_name_es: 'OCULISTA',
    image: require('./res/image/oculista.png'),
    video: `${uri}/oculista.mp4`,
    downloaded: false,
  },
  {
    name_es: 'HACER ANÁLISIS',
    search_name_es: 'HACER ANALISIS',
    image: require('./res/image/hacer-analisis.png'),
    video: `${uri}/hacer-analisis.mp4`,
    downloaded: false,
  },
  {
    name_es: 'PSICÓLOGO',
    search_name_es: 'PSICOLOGO',
    image: require('./res/image/psicologo.png'),
    video: `${uri}/psicologo.mp4`,
    downloaded: false,
  },
  {
    name_es: 'ANTEOJOS',
    search_name_es: 'ANTEOJOS',
    image: require('./res/image/anteojos.png'),
    video: `${uri}/anteojos.mp4`,
    downloaded: false,
  },
  {
    name_es: 'AUDÍFONO',
    search_name_es: 'AUDIFONO',
    image: require('./res/image/audifono.png'),
    video: `${uri}/audifono.mp4`,
    downloaded: false,
  },
  {
    name_es: 'DENTISTA',
    search_name_es: 'DENTISTA',
    image: require('./res/image/dentista.png'),
    video: `${uri}/dentista.mp4`,
    downloaded: false,
  },
  {
    name_es: 'FONOAUDIÓLOGA',
    search_name_es: 'FONOAUDIOLOGA',
    image: require('./res/image/fonoaudiologa.png'),
    video: `${uri}/fonoaudiologa.mp4`,
    downloaded: false,
  },
  {
    name_es: 'IMPLANTE COCLEAR',
    search_name_es: 'IMPLANTE COCLEAR',
    image: require('./res/image/implante-coclear.png'),
    video: `${uri}/implante-coclear.mp4`,
    downloaded: false,
  },
  {
    name_es: 'GUARDIA',
    search_name_es: 'GUARDIA',
    image: require('./res/image/guardia.png'),
    video: `${uri}/guardia.mp4`,
    downloaded: false,
  },
  {
    name_es: 'SACAR RADIOGRAFÍA',
    search_name_es: 'SACAR RADIOGRAFIA',
    image: require('./res/image/sacar-radiografia.png'),
    video: `${uri}/sacar-radiografia.mp4`,
    downloaded: false,
  },